### ISSUE TITLE
Format a double dash as an em-dash

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1005]
**Is your feature request related to a problem? Please describe.**
Currently a double dash, `--`, is formatted as two en-dashes/hyphens "––" in Thunder.

**Describe the solution you'd like**
 I think that a double dash should be formatted as one long [em-dash](https://www.thesaurus.com/e/grammar/em-dash/), "—".

**Describe alternatives you've considered**
One could possibly escape this behavior with backslashes as `\-\-`

**Additional context**
The browser Lemmy-UI formats a double dash as an em-dash.

**Comment by Glazed** [comment]
You can type `&mdash;` to get an em-dash.

I wonder if it works here: &mdash;

**Comment by K4LCIFER** [comment]
I've been thinking about this issue, and, honestly, I think it may be better to not implement it. I was initially proposing it because the Lemmy UI does it, but I now think that the idea isn't really a great one to begin with. It's not like people are without an em dash — one's phone keyboard most likely has it hidden under a long press of the en dash, and a qwerty keyboard, if it doesn't have a dedicated key for it, can create it by using the compose key. And it certainly could present as unexpected behaviour for someone.

**Comment by Glazed** [comment]
> one's phone keyboard most likely has it hidden under a long press of the en dash

Well, TIL! Thank you! I've been typing the HTML token whenever I needed it.

To be pedantic, I think the default character is a hyphen, and a long press on my keyboard (OpenBoard) shows em-dash, underscore, and en-dash. As well as a small dot.

![Screenshot_20240304-130932](https://github.com/thunder-app/thunder/assets/1869438/3b27348e-edc5-4d75-9a78-9e408cb21011)

But, again, thank you!
