### ISSUE TITLE
Indicate when a community is locked

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1022]
**Is your feature request related to a problem? Please describe.**
Currently there is no visual indication that a community is locked beyond simply lacking the button to make a post.

**Describe the solution you'd like**
I think it would be good to have a visual indicator that a community is locked -- similar to that of a post when it is locked. A simple padlock, or text saying "community locked to collaboration" or something would suffice.

**Describe alternatives you've considered**
None.

**Additional context**
An example is [!lemmyworld@lemmy.world](https://lemmy.world/c/lemmyworld). The comumnity is locked to posts other than mods, but there is no visual indication that it is locked other than you don't have the button to create a post.

**Comment by hjiangsu** [comment]
Thanks for the feature request! One way to show this information is to place it in the community header when navigating to a community. Do you think something like this will suffice?

@micahmo I'd like to get your thoughts as well!

![IMG_1564](https://github.com/thunder-app/thunder/assets/30667958/f996554b-f586-4413-ba29-0c2f986e0840)

**Comment by K4LCIFER** [comment]
I like the look of that lock icon! I am somewhat concerned, however, that, if the lock icon is placed within the logo, it could be accidentally mistaken as part of the logo. Perhaps it would be better to give it a more isolated spot on the community header bar?

**Comment by hjiangsu** [comment]
Do you think it would be better suited to be part of the statistics portion of the header? (e.g., beside the number of posts)

<img width="261" alt="image" src="https://github.com/thunder-app/thunder/assets/30667958/aa5cf625-d32e-4342-8011-e0ad7ff034fe">

**Comment by K4LCIFER** [comment]
Yeah, perhaps to the right of the calendar icon would be a good spot for it? Unfortunately, I don't have a whole lot of experience in UI design, so I'm not sure how much my opinion is worth.

I think it could still be possible to keep the lock on the community logo, as you originally had, just so long as long as it's possible to make it obvious that the lock itself isn't a part of the logo.

**Comment by micahmo** [comment]
I like this feature, and I am fine with the implementation as part of the community icon. Since it cuts into the logo, I _think_ it's obviously not part of it. But I also wouldn't mind if it's part of the stats area.

P.S. There's another change that I think would be nice here. When a post is locked, we change the reply button to a lock icon, and when pressed, we show a snackbar indicating that the post is locked. It might be nice to apply the same treatment to the new post button in locked communities!

**Comment by K4LCIFER** [comment]
> When a post is locked, we change the reply button to a lock icon, and when pressed, we show a snackbar indicating that the post is locked.

I completely agree!

**Comment by hjiangsu** [comment]
Sorry it took me so long to get back to this! I added some initial moderating related features in https://github.com/thunder-app/thunder/pull/1063 which allowed me to work on getting the lock on the FAB.

This is the final result that I have. I've opted to keep the lock icon as part of the community, and added the lock status to the FAB to indicate that posting is restricted. Any further thoughts?

| | |
|-|-|
|![simulator_screenshot_633DA583-6659-4F6A-A6DC-9F4FDBF6EB5F](https://github.com/thunder-app/thunder/assets/30667958/767fbf3b-7412-4d5e-a902-fb3b8958ac08) |  ![simulator_screenshot_3EFEADC6-8D30-4FCF-9C0C-63EB35F767F6](https://github.com/thunder-app/thunder/assets/30667958/f20ff0e2-2caf-4496-89af-6ef3cb996059)|
