### ISSUE TITLE
Some communities are out of order in the subscription drawer

### ISSUE THREAD

**Issue by orangeNgreen** [thunder-app/thunder#1023]
**Description**  
Some communities seem to be out of order in the Subscriptions drawer. 

**How to Reproduce**  
1. Subscribe to a lot of communities. 
2. Swipe open the Subscription drawer. 
3. Scroll through. Some communities may be out of alphabetical order. 

**Expected Behavior**  
Communities should be in alphabetical order by name in the Subscription drawer. 

**Screenshots** 
![IMG_2537](https://github.com/thunder-app/thunder/assets/140240648/a9a9f0bf-6465-409d-a97d-723d7d25c16c)

**Device & App Version:**  
 - Device: iPhone 15 Pro
 - OS: iOS 17.2.1
 - App Version 0.2.7

**Comment by micahmo** [comment]
Dev note: I can repro this, and it appears to be related to case comparisons between the community names (not display names). Capital `D` comes before lowercase `a`. I think the comparison should be case-insensitive.

**Comment by hjiangsu** [comment]
Thanks for the issue, and thanks for the double check @micahmo. I can take a look at this further
