### ISSUE TITLE
Option to share from local instance

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1047]
**Is your feature request related to a problem? Please describe.**
Currently, the share-link for a post points at that post's originating instance only.

**Describe the solution you'd like**
It would be helpful to also have an option to share a link that points to the post on the local instance.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by micahmo** [comment]
+1! The same problem is true of sharing comments.
