### ISSUE TITLE
[Feature Request] Support for one handed zoom gesture

### ISSUE THREAD

**Issue by willbennett-kaltura** [thunder-app/thunder#108]
**Is your feature request related to a problem? Please describe.**
Inability to control zoom with a single gesture.

**Describe the solution you'd like**
In other apps, such as RIF, google photos, and many others, you can double tap and hold on the second tap, and then drag up and down to zoom in or out, respectively. This functionality would be very useful inside of the image viewer in Thunder.

**Comment by machinaeZER0** [comment]
I only recently found out this was a thing I could do in some apps and it blew my mind, hahah. Would love to see this implemented!

**Comment by willbennett-kaltura** [comment]
Anyone willing to take a stab at this? I see double tap zooms a little now, but this gesture would make the app a nearly perfect drop in replacement for RIF.

**Comment by micahmo** [comment]
Looks like @CTalvio is working on it in #376.

**Comment by CTalvio** [comment]
Yup. Just got it working, sitting in a PR and waiting for merge 👍

**Comment by hjiangsu** [comment]
This has in fact been merged, but not yet released as a pre-release: #376
