### ISSUE TITLE
Settings search box can't be selected

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#1087]
**Description**  
Tapping the new settings search box shows the tap animation, but the box remains unselected. I tried both with existing app data and with the app's data cleared.

**Device & App Version:**  
 - OS: e.g. Android 13
 - App Version 0.2.9-2

**Comment by micahmo** [comment]
@everdred Any chance you can provide a screen recording to demonstrate what's happening?

**Comment by everdred** [comment]
This should help explain and, to contrast, show that the search box on the community page does work as expected.

https://github.com/thunder-app/thunder/assets/5367819/14f6e8ce-e98b-47ad-a499-90485401750b

**Comment by micahmo** [comment]
Thank you!!
