### ISSUE TITLE
Notification counter is capping at 20 notifications despite there being more than 20 notifications in the inbox

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1099]
**Description**  
An inbox with more than 20 notifications will only display 20 notifications in Thunder

**How to Reproduce**  
1. Gain >20 notifications
2. Observe that the notification counter in Thunder only shows 20

**Expected Behavior**  
I would expect the notification counter to work up to 99 at which point >99 displays as 99+

**Screenshots**  
I can send some comparisons as proof, if need be.

**Device & App Version:**  
 - Device: Google Pixel 6 Pro
 - OS: Android 14
 - App Version: 0.2.8

**Additional Context**  
None.

**Comment by micahmo** [comment]
@K4LCIFER When you say notifications, do you mean system/OS notifications, or do you just mean the number at the bottom of Thunder?

When you go to the inbox tab and scroll down, do more replies load in?

Dev note: https://github.com/thunder-app/thunder/blob/2825b0377623a1940198967c5553486af3807a4e/lib/inbox/bloc/inbox_bloc.dart#L65

**Comment by K4LCIFER** [comment]
> When you say notifications, do you mean system/OS notifications, or do you just mean the number at the bottom of Thunder?

I am referring to this number: 
![share_1526472462482036454](https://github.com/thunder-app/thunder/assets/7829231/1349f193-ad62-492e-88bc-b324ad25eb4b)

> When you go to the inbox tab and scroll down, do more replies load in?

The actual total number of replies (in my case 27) are all in the inbox, but the number still only displays 20.

An interesting note is that when you reply to a notification, the number, 20, will decrement, 19, and then if you drag down to refresh the notification drawer it will increment back to 20. I assume it will keep doing this until the actual total number is less than 20.
