### ISSUE TITLE
Keep post view state after reopening it

### ISSUE THREAD

**Issue by daviessm** [thunder-app/thunder#1113]
**Is your feature request related to a problem? Please describe.**
I have a habit of closing a post's comments and then deciding I'd like to view them again. Currently this re-loads the post when I select it again.

**Describe the solution you'd like**
Hide a post rather than closing it when returning to the post list. If the user selects to view the same post again, re-show the post. If they select a different one, discard it and load the new one.

**Comment by micahmo** [comment]
Is this a dup of #742?

**Comment by daviessm** [comment]
Yep! I also came from Relay.
