### ISSUE TITLE
Feature Request: Show the precise date instead of a relative date for posts and comments 

### ISSUE THREAD

**Issue by dtantono** [thunder-app/thunder#1114]
**Is your feature request related to a problem? Please describe.**
I think it will be great if we can keep tracking our read post accurately on home screen. 

**Describe the solution you'd like**
Is it possible to add a new toggle settings to Show the precise date (i.e: Sun Nov 16 20:14:56 2014 UTC) instead of a relative date (i.e: 7 days ago), for posts and comments?

**Describe alternatives you've considered**
Old Reddit RES

**Additional context**

**Comment by hjiangsu** [comment]
Thanks for the issue! Do you think having an option to long-press on the date to show the precise date works in this scenario? Or would you prefer to show the full time at all times?

It would also be useful to share any screenshots of what you mean to help coordinate the UI (if UI changes are needed)!

**Comment by dtantono** [comment]
a toggle to show fulltime at all times will be nice

**Comment by hjiangsu** [comment]
Update: there is now a PR which adds this setting. In terms of the date format, I've added a way to preselect from a given list of formats.

Attached to the PR #1174 is also a video demo of the feature. Let me know if this is what you were expecting!
