### ISSUE TITLE
Allow sorting notifications oldest to newest

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1118]
### Is Your Feature Request Related to a Problem?

Generally, I try to FIFO my notifications (I answer the oldest ones first). This can be mildly tedious at times, since there is no way to sort so that the oldest notifications appear first.

### Feature Description

I suggest adding a button in the notification drawer to toggle sorting newest to oldest, or oldest to newest.

**Comment by ggichure** [comment]
@K4LCIFER This was worked on in #1373  . 

![Screenshot_20240828-145433_Thunder](https://github.com/user-attachments/assets/82aa658a-65b6-4332-992d-20ebfd440f88)
