### ISSUE TITLE
Option to sort user post history and comment history.

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1119]
### Is Your Feature Request Related to a Problem?

There are currently no ways to sort a user's post history, or comment history.

### Feature Description

It would be nice to have a sort menu button that allows one to sort a user's post history and comment history -- including on one's own profile.

**Comment by micahmo** [comment]
Is this a dup of #664?

**Comment by K4LCIFER** [comment]
> Is this a dup of #664?

Oh, ha, yeah it totally is. My bad! I completely forgot that I had already opened this issue. I should have searched a bit more before making this. I'll close this issue.
