### ISSUE TITLE
When adding a new post, suggested title from URL and selectable language don't work.

### ISSUE THREAD

**Issue by UKFilmNerd** [thunder-app/thunder#1120]
### Bug Description

When I create a new post including a web page URL, the title bar features a drop-down box of a suggested title. I cannot select the suggested title.

Also, some communities want me to specify a language. Again, I can find English in the drop-down list but cannot select it.

### Expected Behaviour

See Bug Description.

### Steps to Reproduce

See Bug Description.

### Additional Context

Works without any issues on my Android 12 phone.

### App Version

0.2.9-3

### Device

Samsung Galaxy Tab A7 (SM-T500)

### OS

Android 12

**Comment by micahmo** [comment]
Could this be the same issue as #951? I've been experiencing this myself lately, although I can't find any rhyme or reason as to why it gets stuck in this mode. But the common denominator is that no `TypeAheadField` suggestions can be tapped (community popup dialog, language selection, and suggested post title all use this widget).

**Comment by hjiangsu** [comment]
Thanks for creating the issue report!

@micahmo  This particular issue involves a tablet rather than a phone, but it may be related as you mentioned! For more context: https://lemmy.world/post/11680419.

**Comment by UKFilmNerd** [comment]
I made a quick video. The tablet is running a little slow because I had to install a third party screen recorder, but hopefully you get the idea.

https://www.youtube.com/watch?v=leoY9sVU7vo

**Comment by hjiangsu** [comment]
Just an update on this, we updated the package which handles the dropdown lists `TypeAheadField` as part of https://github.com/thunder-app/thunder/pull/1243. Since this seems to be an issue related to that package and we've updated that recently, I'll preemptively mark this as done.

Do let me know if you still encounter this once a new nightly is released with these updates!
