### ISSUE TITLE
0.2.9-4 does not start

### ISSUE THREAD

**Issue by cooperaj** [thunder-app/thunder#1123]
### Bug Description

On my Pixel 6 Pro running Android 14 I'm unable to start 0.2.9-4. The app hangs at the logo.

Additionally, attempting to rollback to 0.2.9-3 give me an error that the app package is invalid. I have to uninstall Thunder first then that release installs and functions as I'd expect. 

### Expected Behaviour

Should be seeing a shiny new 0.2.9-4 release. 

### Steps to Reproduce

Install new version.
Start it. 

### App Version

0.2.9-4

### Device

Pixel 6 Pro

### OS

Android 14

**Comment by Fmstrat** [comment]
Same issue, Pixel 6 (non-pro).

**Comment by machinaeZER0** [comment]
This happened to me as well! Pixel 4a over here

**Comment by hjiangsu** [comment]
Hey, thanks for mentioning this. It seems like it's not limited to Android as its affecting some iOS users as well. I'll take a closer look at this and push out a fix when I can!

**Comment by hjiangsu** [comment]
Update: I've released 0.2.9-5 which should fix this issue. If you could try it out and let me know, that would be great. Thanks!

https://github.com/thunder-app/thunder/releases/tag/0.2.9-5

**Comment by Fmstrat** [comment]
Works for me. Thank you, quick action is much appreciated with your free time!

**Comment by machinaeZER0** [comment]
All fixed on my end, thank you! 😄

**Comment by hjiangsu** [comment]
Closing this issue since it seems to be fixed!
