### ISSUE TITLE
Crash when saving image

### ISSUE THREAD

**Issue by X64X2** [thunder-app/thunder#1129]
App crashes when I tried to save an image

**Comment by hjiangsu** [comment]
Thanks for creating this issue! Could I get more information about this?

For example, what version of Thunder are you experiencing this issue on? Do you have a specific device model or OS version? Additionally, are you able to successfully reproduce the issue?

**Comment by sukhmel** [comment]
I think, I had it twice or thrice with 0.2.8 or 0.2.9 by pressing the `downloaded` icon that appears in place of the download button/icon. This doesn't reproduce in 0.3.0-1

**Comment by hjiangsu** [comment]
Thanks for the additional information!

This might be related to https://github.com/thunder-app/thunder/issues/734. v0.2.8 and below used an image download library which caused some `NullPointerException` errors. I migrated to a different image download library in v0.2.9 which _should_ fix those errors.

Keep me updated if you encounter any more crashing in the 0.3.0 nightlies!

**Comment by hjiangsu** [comment]
I'll close this as this issue may have been fixed by my previous comment. Feel free to create a new issue if this is still occurring!
