### ISSUE TITLE
Writting post or comment create a white screen

### ISSUE THREAD

**Issue by Gobtous** [thunder-app/thunder#1135]
### Bug Description

When i write long post or comment, a grey screen appear and i can't type anymore. I have to switch between preview/editing to reset so i can continue and edit my post again.

### Expected Behaviour

Simply write my post.

### Steps to Reproduce

1. Dunno how to reproduce it.

### Additional Context

Dunno how to reproduce as it appears randomly. Maybe it's related with 
* switching app ?
* corrector as lot words are highlighted ?

Well i hope we can find more users to find the source of this bug.

### App Version

0.2.9-5

### Device

Hisense A9 (HLTE556N)

### OS

Android 11

**Comment by hjiangsu** [comment]
I'll close this issue as I have not been able to reproduce this in the latest versions. Please do let me know if this issue is still occurring in v0.4.0!
