### ISSUE TITLE
Cannot build with Flutter 3.19 due to CupertinoLocalizationsEo

### ISSUE THREAD

**Issue by Fmstrat** [thunder-app/thunder#1136]
### Bug Description

When attempting to update the `Dockerfile` to build with Flutter 3.19, I have learned the following error exists:
```
BUILD FAILED in 15s
Gradle task assembleRelease failed with exit code 1
Failed to build for Android. Error: You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

/root/.pub-cache/hosted/pub.dev/l10n_esperanto-2.0.8/lib/src/cupertino.dart:14:7: Error: The non-abstract class 'CupertinoLocalizationsEo' is missing implementations for these members:
 - CupertinoLocalizations.clearButtonLabel
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class CupertinoLocalizationsEo extends GlobalCupertinoLocalizations {
      ^^^^^^^^^^^^^^^^^^^^^^^^
/opt/flutter/packages/flutter/lib/src/cupertino/localizations.dart:256:14: Context: 'CupertinoLocalizations.clearButtonLabel' is defined here.
  String get clearButtonLabel;
             ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.
```

After further research, this is due to the use of Flutter 3.19 (latest stable, released 2/15/24) instead of Flutter 3.16.9.

### Expected Behaviour

Compile with latest version of Flutter

### Steps to Reproduce

1. Update `Dockerfile` to use `https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.0-stable.tar.xz` (this is not the actual issue, I'll have a PR for this once fully tested)
2. `./scripts/docker-build-android.sh`

### Additional Context

This could be done by upgrading Flutter to 3.19, without docker.

### App Version

n/a

### Device

n/a

### OS

n/a

**Comment by hjiangsu** [comment]
Thanks for the report, just for some more context, this seems to originate from https://github.com/deakjahn/l10n_esperanto package! I can create an issue there so that the package author can hopefully provide a fix

**Comment by hjiangsu** [comment]
This has been fixed with this PR: https://github.com/thunder-app/thunder/pull/1167.
