### ISSUE TITLE
IN-PROGRESS: Need feedback - Mark read on scroll

### ISSUE THREAD

**Issue by Fmstrat** [thunder-app/thunder#1138]
### Is Your Feature Request Related to a Problem?

I'm working on a mark read on scroll feature, but I've hit a bit of a roadblock. I'd do a draft PR but the changes are after the Docker updates so it's a little dirty looking compared to `develop` until that is merged in. Here's what the changes look like:

https://github.com/Fmstrat/thunder/compare/docker-updates...Fmstrat:thunder:read-on-scrolling

My problem is, if I scroll far enough to make index `0` mark itself read, `postViewMedias[i].postView.read` is always `false`. I.E. once it's marked read, it shows on screen as read, but it continues to mark itself read over and over every time I scroll. Not just that, everything in the `for` loop before the `index-past` displays the `marked read` message, but doesn't actually mark read.

Is there something being done with state that I'm not understanding that would cause the variable change to not show up for items in the `postViewMedias` array?

Note: I'll be adding a toggle to turn this on or off to settings, just not there yet.

### Feature Description

n/a

### Alternative Solutions

n/a

### Additional Context

n/a

**Comment by Fmstrat** [comment]
Note: I have discovered it's timing. It's almost like the `postViewMedias[i].postView.read` isn't marked `true` until after a couple of seconds. So if you scroll quickly, it keeps marking. I can solve this with a temporary tracking array if needed, but if there's a better way, let me know here. I'll close this if I don't hear back before I'm ready for a PR review. Thanks!

**Comment by micahmo** [comment]
@Fmstrat Thank you so much for working on this! It's a highly requested feature as I'm sure you know.

I think part of the problem is related to how Flutter blocs work and the fact that the events are asynchronous. The logic for your `FeedItemActionedEvent` has _not_ completed by the time the `add` call returns.

https://github.com/Fmstrat/thunder/blob/61b5329e3d5c9eec695f44088f372edcc9129789/lib/feed/view/feed_widget.dart#L77

That said, I tested your code, and I think it's working fine! I scrolled back up and then down again, and this time the `read` flag was correct. I think it's only wrong when you check it right away. Don't even worry about putting the delay in. Just let the event execute asynchronously and move on. Was there something else not working, or were you only concerned about the value being wrong after the call?

Here's a demo of it working great on my system.

https://github.com/thunder-app/thunder/assets/7417301/72bd32ac-e730-43ce-87f8-e75db5c929aa

P.S. I think your `past` threshold could be a little lower, but I'm sure you can tweak and experiment with that.

**Comment by micahmo** [comment]
P.P.S. If you finish this before your Docker updates, you can make a new branch and cherry-pick just the commits for this feature. Or you can make a new branch from this one and rebase to remove the Docker feature. In other words, I'd hate for this to be held up by the Docker PR. 😊

**Comment by Fmstrat** [comment]
Thanks, and yes it works fine for me, I just don't want to spam the API (if that is occurring).

The reason the `past` variable is high is because I only have access to the index of the item being tapped on during the scroll. This could be an item at the top of the list, or the bottom. It may actually need to go higher because if you have more than 7 items in compact mode on screen it can mark read too early if someone scrolls a bottom item slightly. This is exacerbated further in tablet mode.

I'm going to do some optimizations such as checking scroll distance, making `past` dynamic based on compact/comfortable mode and tracking post ids already marked to reduce overhead, along with a toggle in settings, then I'll make the PR, probably tomorrow. Thanks again!

**Comment by micahmo** [comment]
> I just don't want to spam the API

Ok I get what you're saying. If `onUpAction` fires again before the event returns, you could have a timing issue where you mark the same post read multiple times. And the window for this issue could increase as there's more latency for the API call (e.g., bad networks). When I removed my breakpoint and scrolled around quickly I was able to reproduce this.

One thing to note is that we do have an artificial delay in the mark read code. You could add a new parameter to the event and disable this in your case. But even when I removed it, I could still reproduce the issue.

https://github.com/thunder-app/thunder/blob/b2ddd0e9702899fcd884a7fea6b50af4cfddc98e/lib/feed/bloc/feed_bloc.dart#L189-L190

I can even reproduce after a significant amount of time, so now I'm not sure what's going on.

> The reason the `past` variable is high is because I only have access to the index of the item being tapped on during the scroll. This could be an item at the top of the list, or the bottom. It may actually need to go higher because if you have more than 7 items in compact mode on screen it can mark read too early if someone scrolls a bottom item slightly. This is exacerbated further in tablet mode.

Makes sense!

**Comment by Fmstrat** [comment]
Yup. I've decided to go down the road of optimizing the API client to allow for multiple mark on read at once. This way a big scroll in compact mode only needs one API call.

Realistically all multi-tasks like this should probably be handled in a queue with a 2s delay after the final change. In this case there is nothing stopping a user from flicking the screen and hitting a ton at once. But that's a solution for another day.

**Comment by Fmstrat** [comment]
Closing to move conversation to PR.
