### ISSUE TITLE
Show user instance name on posts

### ISSUE THREAD

**Issue by glyph-se** [thunder-app/thunder#1198]
### Is Your Feature Request Related to a Problem?

The same username can exists on many instances, therefore it should be possible to always show the instance name together with the username.

### Feature Description

Currently there is a setting in _Appearance -> Comments -> Show User instance_ . I found no way to show the user instance in neither the post list nor in the post+comment page after opening it. There are however two related options, _Show post author_ and _Show User Display Name_.

### Alternative Solutions

Instead of adding a new _Show User instance_, an alternative would be to extend the _General -> Advanced -> User Format_ with new options that are just _username_ and _display name_ . Then that setting could be applied to more than just the comments.

### Additional Context

I understand that this will take up extra space in the post list, but I believe it would be nice to at least have an option for this. Possible the user can be rendered on its line if that would make it look better, but I don't think that is necessary in all cases, the regular wrapping can probably be used.

**Comment by hjiangsu** [comment]
@micahmo I believe #1227 fixes this issue? I'll mark this with the proper tags - let me know if you think otherwise!

**Comment by micahmo** [comment]
Agreed!
