### ISSUE TITLE
Option to show user profile pictures in post view

### ISSUE THREAD

**Issue by Fxsch** [thunder-app/thunder#1221]
### Feature Description

There's already the option to show the community profile picture on posts in your feed but when I click on a post, I would like to be able to see the profile pictures of the post author and the commenters.

**Comment by iparks99** [comment]
Great idea, I'll start working on this!

**Comment by glyph-se** [comment]
Is this a duplicate of https://github.com/thunder-app/thunder/issues/600 ?
