### ISSUE TITLE
Automatic check for replies

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#125]
**Is your feature request related to a problem? Please describe.**
The app should pull for any notifications on a user defined schedule like once per hour, once every three hours, etc. This would have to be an API call unless the lemmy server supports sending push notifications. In that case this could be done with UnifiedPush

**Describe the solution you'd like**
Thunder should check for notifications

**Comment by hjiangsu** [comment]
Good idea - that is something I want to include as more features are integrated for the inbox! For the near future, my general plans is to support updating of notifications within the app itself (every time you open the app, it'll do a quick fetch of any new notifications and will show up as a small alert in the inbox icon)

I would like to get to push notifications eventually, but that requires a lot more work to set up (might need a dedicated server to poll for new notifications)

**Comment by tcely** [comment]
A lot of the notifications infrastructure is already set up for you by UnifiedPush.

https://github.com/UnifiedPush/flutter-connector

**Comment by trymeouteh** [comment]
> A lot of the notifications infrastructure is already set up for you by UnifiedPush.
> 
> https://github.com/UnifiedPush/flutter-connector

Would be nice if Thunder has its own push notification system and also had the option to use Unified Push and this can be changed with a simple setting in the app.

**Comment by shortwavesurfer2009** [comment]
> > A lot of the notifications infrastructure is already set up for you by UnifiedPush.
> > https://github.com/UnifiedPush/flutter-connector
> 
> Would be nice if Thunder has its own push notification system and also had the option to use Unified Push and this can be changed with a simple setting in the app.

It could be set to poll for new notifications say once per hour unless UnifiedPush is detected. Then thunder could defer to the UnifiedPush provider

**Comment by shortwavesurfer2009** [comment]
I am going to go ahead and close this because the polling every 15 minutes is good enough for me.
