### ISSUE TITLE
Buggy navigation bar animation

### ISSUE THREAD

**Issue by codenyte** [thunder-app/thunder#1257]
### Bug Description

Instead of smoothly jumping from one navigation item to another, it jumps to the navigation item in between, then jumps back and only then jumps to the actual selected navigation items.

https://github.com/thunder-app/thunder/assets/39193783/3b72f3cf-587e-4140-b493-81dc3210e65e

### Expected Behaviour

Smoothly animate jumping from the current navigation item to the selected navigation item

### Steps to Reproduce

1. Click a navigation item
2. Click on another navigation item with one item in between

### Additional Context

I've never seen this bug in any other app that uses a Material 3-style navigation bar, does Thunder use Flutter's [NavigationBar](https://api.flutter.dev/flutter/material/NavigationBar-class.html) component, or does it use a custom implementation?

### App Version

v0.3.0-3

### Device

Pixel 6a

### OS

Android 14 ([GrapheneOS](https://grapheneos.org/))

**Comment by micahmo** [comment]
@codenyte

Thanks for the bug report! Just to clarify, are you talking about how Thunder scrolls through all the pages? For example, if I'm on Feed and I tap on Settings, it will scroll through Search, Account, and Inbox? If that's not what you're talking about, maybe you can submit a screen recording to demonstrate the issue.

BTW, for the other MD3 apps you use which don't have this issue, do they have an animation to scroll to the selected page, or do they just "jump" to it instantly?

**Comment by hjiangsu** [comment]
It sounds like this might be from the "scroll through pages". I was looking more closely at MD3 guidelines, and they seem to mention that the pages should "jump" to the given page instantly.


https://github.com/thunder-app/thunder/assets/30667958/7117fb7b-5fcb-4fff-b3f8-3720f481f367



See here: https://m3.material.io/components/navigation-bar/guidelines#8fdee610-b49b-47e0-85b7-f4abb86333e7

**Comment by hjiangsu** [comment]
> I never realized that this was a feature, not a bug. The scrolling through pages animation doesn't look that bad, it just looks really strange on the navigation bar, which led me to believe it's a bug.

There's currently a way to disable this by going to Settings -> Accessibility -> Reduce Animations. However, this option also does a couple more things which might or might not be desire-able (faster animation when navigating, removing the over-scroll effect, etc.)

I do this this topic brings up a bigger discussion on how closely we should try to abide by MD3 guidelines. One case was with the navigation bar labels (which we switched to be on by default). Should we do the same here?
