### ISSUE TITLE
Filter crossposts

### ISSUE THREAD

**Issue by Offerel** [thunder-app/thunder#1295]
### Is Your Feature Request Related to a Problem?

I don't know if this is possible, but it would be nice, to filter crossposts, so that they appear only once in the subscription feed. Sometimes when I have a lot of similar subscriptions next by each other, the same crsosspost appears multiple times. 

### Feature Description

Filter/remove duplicated crossposts optionally.

**Comment by micahmo** [comment]
This sounds very similar to #469.

**Comment by Offerel** [comment]
Yes, exactly. I close my issue, so we can use the other fr.
