### ISSUE TITLE
Customize Swipe Gesture Colours

### ISSUE THREAD

**Issue by hjiangsu** [thunder-app/thunder#1301]
### Feature Description

There should be a way to customize the colours of the different swipe gestures (upvote/downvote/save/etc). We can do this in a way that is similar to the divider customization (dropdown menu).

The customization should be within the Gestures settings page alongside customization of the swipe actions.

### Additional Context

Original request: https://lemm.ee/comment/11096163

**Comment by micahmo** [comment]
Just a thought here: how about allowing the customization of action colors across the board? This could be in the theming section and we could have a customizable color for upvote, downvote, save, etc. It would apply to the swipe gestures, but it would also apply anywhere that the color is displayed on buttons and icons. Thoughts?

**Comment by hjiangsu** [comment]
> how about allowing the customization of action colors across the board?

I think that makes a lot of sense! I noticed you made a PR for this so I'll take a look at it in a bit
