### ISSUE TITLE
Latest release breaks full height images in tablet mode

### ISSUE THREAD

**Issue by Fmstrat** [thunder-app/thunder#1330]
### Bug Description

When full height images are on in tablet mode, black baras appear around vertically squashed images 

![Screenshot_20240427_221737_Thunder](https://github.com/thunder-app/thunder/assets/971474/739f1876-8eca-46b0-a4dd-e607f4db8e3a)

### Expected Behaviour

The vertically squashed image should take up the full height.

### Steps to Reproduce

- Tablet mode
- Card view
- Full height images

### App Version

0.3.0

### Device

Samsung Tab S9

### OS

Android 14

**Comment by hjiangsu** [comment]
Found the issue, made a PR for it. It'll most likely land on 0.4.0-2 nightly! (already submitted 0.4.0-1 nightly for review before this fix so I won't be able to push it to that one)
