### ISSUE TITLE
Color contrast for OP and mod names

### ISSUE THREAD

**Issue by glyph-se** [thunder-app/thunder#1346]
### Bug Description

Enabling colorized user name or instances doesn't work well together with the background color for OP/mod/self. I think this is an effect of recent changes that applies the colorized name also in the post/comments view.

[Screenshot](https://lemmy.world/pictrs/image/c258a0b4-2244-4405-b3a6-a7371c28bf30.png)

### Expected Behaviour

I expect settings to work together with each other. While I have three proposals as how to resolve this issue, there might be other ways to get it working:

- Change OP/mod background colors so that they work together with the theme colors
- Only display the icon next to the name if colors are set, instead of colorizing the whole name.
- Let OP/mod colors take precedence and override the default color with them

### Steps to Reproduce

1. Change to dark theme
2. Set user name color to theme primary
3. Navigate to a post where there comments from OP and/or mods

### Additional Context

[From this lemmy post.](https://lemmy.world/post/14760286)

Similar issue exist with the green background color on your own name, although one might be expected to know that one :)

### App Version

0.3.0

### Device

Asus Zenfone 9

### OS

Android 13

**Comment by micahmo** [comment]
It looks like this was fixed in 574c285d376faf2877406c29f2c92c698034d18f. See this line.

https://github.com/thunder-app/thunder/blob/436b12f7d9e0aedebcce86c8d6a1e31a89f7269a/lib/shared/chips/user_chip.dart#L93

**Comment by CTalvio** [comment]
I got assigned @hjiangsu ?

**Comment by hjiangsu** [comment]
Ahh sorry, I assigned it to you because it seems like you fixed the issue as per @micahmo's previous comment!
