### ISSUE TITLE
Open post in another account

### ISSUE THREAD

**Issue by wadamT** [thunder-app/thunder#1360]
### Feature Description

When you have account(s) sign in, shows a button to open a post with another account. 
The button can be added in pop out from more options of the post.

- When only one account is sign in, the button is hidden when viewing a post with that account. 

- The button always shows in anonymous instance browsing only when an account is sign in.

- The button is always there when more than one account is sign in.

This can be useful for various purposes especially when you are browsing an instance anonymously and find an interesting post and want to comment or save.

This feature is inspired by Tusky for Mastodon.

![Screenshot_20240509-233240_Tusky](https://github.com/thunder-app/thunder/assets/70312852/2cc8ee96-0939-4ca6-a412-d31504f3010c)

![20240509_235111](https://github.com/thunder-app/thunder/assets/70312852/1a9e7fdf-c4ab-4abd-95e3-5504972ff87f)

**Comment by micahmo** [comment]
I think this issue has a lot of overlap with #341! I'll let you decide if you think it's a duplicate.

BTW, we do have the option to create posts and (soon) comments as any of your logged-in accounts. I realize that's not exactly the same as reloading the whole post as another user, but hopefully it helps!

**Comment by wadamT** [comment]
Yes. I see this has a lot of overlap with #341 and checked #1352. I see different approach taking place to do the same thing. So I will set this duplicate.

**Comment by micahmo** [comment]
Thanks! I definitely like this idea, and I think it adds value beyond the comment feature (e.g., the ability to save/vote, see differently federated comments, etc.).
