### ISSUE TITLE
2-column tablet view

### ISSUE THREAD

**Issue by Fmstrat** [thunder-app/thunder#138]
**Is your feature request related to a problem? Please describe.**
When using a tablet, it would be great to have a 2 column view in the feed display.

**Describe the solution you'd like**
Two columns.

**Describe alternatives you've considered**
One column, and then another one next to it.

**Additional context**
Lots of rows, but two columns.

**Comment by hjiangsu** [comment]
Do you have any examples that I could potentially use to help visualize this?

This is a lower priority right now while I continue to add in more of the core features, but having screenshots will help me start thinking about how the layout can adapt to tablets

**Comment by Fmstrat** [comment]
Yea, I figured you would be focused on things like read-on-scroll and editing comments/etc, this is a nice to have. Maybe if I have time to get familiar enough I'll take this on. I'll go back to Sync as an example. In it's case, swipes are handled inside the "card".
![Screenshot 2023-06-10 21 39 04](https://github.com/hjiangsu/thunder/assets/971474/349fefb5-daa1-4bc7-9cd9-578576a929fc)

**Comment by Fmstrat** [comment]
Since this is merged should it be marked for next release?

**Comment by hjiangsu** [comment]
Yup! I'll mark it down
