### ISSUE TITLE
Video posts are being incorrectly marked as viewed

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#1383]
### Bug Description

Since version 0.4.0-3 posts linking to a video are displaying as viewed in the post feed without having been viewed.

### Expected Behaviour

Posts should only be marked as viewed if actually viewed.

### Steps to Reproduce

1. Upgrade to Thunder 0.4.0-3 
2. Simply view post feed
3. Observe video posts you haven't viewed marked as viewed
4. In some cases, observe Thunder repeatedly marking a video post as viewed and unviewed (see video below)

### Additional Context

`Post View Type` setting is Compact View
`Mark Read On Scroll` is disabled
`Mark Read  After Viewing Media` is enabled

Usually posts are simply appearing greyed out, as with typical viewed posts, but I also noticed this odd behavior after closing and relaunching Thunder:

https://github.com/thunder-app/thunder/assets/5367819/23756bf9-753d-4ed3-bc63-043b772f338f

### App Version

0.4.0-3

### Device

Android 14 device

### OS

Android 14

**Comment by hjiangsu** [comment]
Thanks for the report! I found the issue and I'll apply a hotfix soon.

**Comment by hjiangsu** [comment]
This should now be released in 0.4.0-4. Let me know if this version fixes this issue!

**Comment by everdred** [comment]
Fix confirmed, thank you!

![Screenshot_20240526-160529_Trebuchet](https://github.com/thunder-app/thunder/assets/5367819/41386c39-a4d1-427f-83f8-238682eb6faa)
