### ISSUE TITLE
Integration with Lemmyverse 

### ISSUE THREAD

**Issue by Terkyz** [thunder-app/thunder#14]
**Is your feature request related to a problem? Please describe.**
It's really a problem with Lemmy and the federation, that for users coming from Reddit it's an absolute pain in the ass to understand how the hell Lemmy works and why it's so hard to join a community.

An integration with Lemmyverse would allow users to search for communities all over Lemmy and join the communities they want to join (obviously by converting their instance to the instance they want to join) without the headache.

**Describe the solution you'd like**
An extra button in the "Search communities" function within Thunder that allows to activate the search for communities using Lemmyverse.

**Describe alternatives you've considered**
Doing it manually, although in Jerboa at least was not possible.

**Additional context**
I guess you can consider that this will make Lemmy more accessible to non-technical people?

**Comment by hjiangsu** [comment]
I agree that simplifying the process of finding communities and instances would be good for new users.

However, this is an interesting idea which might need a bit more planning before it can be considered. For example, does Lemmyverse have a public API to access their information?

It would be good to revisit this in the future once some more progress is made with the core functionalities of the app!

**Comment by Terkyz** [comment]
Honestly researching about that I only found that they already use the [Fediverse Explorer API](https://lemmyverse.net/about) with a web crawler, maybe you can integrate the Fediverse Explorer API directly?

**Comment by Poolitzer** [comment]
They provide access to their data via a zip file and in it a json, refreshed daily. If you would be interested in adding this to the app when a proper API is provided, I could see myself coding a small web application for this.

**Comment by hjiangsu** [comment]
Closing this since there is an alternate issue. All further discussions on this can be done in #508
