### ISSUE TITLE
Allow the following of a YouTube video's link

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1419]
### Is Your Feature Request Related to a Problem?

When a YouTube video appears in the feed, one is only able to watch it within Thunder — there is no way to follow the link to an external app (e.g. the YouTube app, a browser, etc.)

### Feature Description

I propose being able to follow the post's link externally.

**Comment by micahmo** [comment]
Hey @K4LCIFER, thanks for the report. Can you try this button?

| ![image](https://github.com/thunder-app/thunder/assets/7417301/6adf7bcb-cf66-4fa8-87e6-504bf25c86ef) |
| - |

**Comment by K4LCIFER** [comment]
> Hey @K4LCIFER, thanks for the report. Can you try this button?

Oh, ha, my bad! I completely missed the existence of that button. I'll close this issue then.

**Comment by micahmo** [comment]
> > Hey @K4LCIFER, thanks for the report. Can you try this button?
> 
> Oh, ha, my bad! I completely missed the existence of that button. I'll close this issue then.

No problem at all, I can see it being easy to miss! Also keep an eye on the other PR which will help with copying/sharing the direct link.
