### ISSUE TITLE
Add some more UI feedback when subscribing to a community

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1423]
### Is Your Feature Request Related to a Problem?

Currently, when you subscribe to a community by tapping on the plus in the circle at the top of a community page, it just shows that you tapped it by highlighting, but doesn't provide any further feedback until the subscription goes through. The main issue with this is that, depending on the server, this could potentially take a while, and the button doesn't change to the subscribed state until the subscription has gone through.

### Feature Description

I propose adding some feedback to show that the request for subscription was successful — the button could change to some intermediary state to show that the request was made, and then change to a subscribed state when the subscription has been successfully completed.

**Comment by micahmo** [comment]
Hi @K4LCIFER! When you subscribe to a community that is not on your instance, the button should change from the plus icon to three dots, which indicates that your subscription is pending.

![Screenshot_20240604-201007.png](https://github.com/thunder-app/thunder/assets/7417301/cf1c7e5d-2fe8-4c91-95c5-daeb8e8260fb)

In addition, if you long-press the button, it will tell you that pressing the button again will unsubscribe you, and that your subscription is currently pending.

Can you let us know if the three-dot icon is showing for you and/or if you have any other ideas for more clearly indicating what's going on?

**Comment by hjiangsu** [comment]
Maybe we can add in a snackbar message here when the action succeeds or fails?

**Comment by K4LCIFER** [comment]
> When you subscribe to a community that is not on your instance, the button should change from the plus icon to three dots, which indicates that your subscription is pending.

I do see the 3 dots, but there is a delay that is dependent on the responsiveness of the server. Sometimes, this delay can be quite substantial — substantial enough that the user thinks that their request didn't go through, so they tap the button again.

---

> Maybe we can add in a snackbar message here when the action succeeds or fails?

Perhaps also a message, on first tap, that says something like "subscription request sent"?
