### ISSUE TITLE
Profiles seem to show Subscriptions feed

### ISSUE THREAD

**Issue by orangeNgreen** [thunder-app/thunder#1454]
### Bug Description

Clicking on a user profile view their posts just seems to show the Subscribed feed, rather than that user’s posts. 

### Expected Behaviour

The profile should show a user’s posts as opposed to the Subscriptions feed. 

### Steps to Reproduce

1. Click a user. 
2. Try to view their posts. 

### Additional Context

Here are some pictures with various random users all showing the same posts on their profile, which are also the same as my Subscribed feed.

![IMG_4865](https://github.com/thunder-app/thunder/assets/140240648/bfa54cf5-c343-42ff-8e93-b155ff034b34)

![IMG_4864](https://github.com/thunder-app/thunder/assets/140240648/5fd118d6-5d7b-42b7-b6f0-6a88d571b8e7)

![IMG_4863](https://github.com/thunder-app/thunder/assets/140240648/fefe0692-f702-424f-91ca-a05b01d1057e)

### App Version

0.5.0-1

### Device

iPhone 15 Pro

### OS

17.5.1

**Comment by hjiangsu** [comment]
Thanks for the report! This was caused with the recent switch to use the Lemmy account's feed settings rather than the in-app settings for determining the default feed type/sort!
