### ISSUE TITLE
Spoiler tagging within a codeblock breaks the codeblock

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#1459]
### Bug Description

Tried to show someone how to use spoiler tagging, and noticed that Thunder seems to try and render spoiler tagging that is within a codeblock.

Example: https://sopuli.xyz/comment/10163376

![Screenshot_20240619-132126833_1](https://github.com/thunder-app/thunder/assets/4365015/3199032c-cf42-4aa9-963e-26f7d6d17647)
![Screenshot_20240619-132143257_1](https://github.com/thunder-app/thunder/assets/4365015/ac78469d-355e-416e-8659-3e7e51040e6b)

### Expected Behaviour

Markdown within a codeblock should be ignored

### Steps to Reproduce

1. Open this comment: https://sopuli.xyz/comment/10163376

### App Version

0.5.0-1

### Device

Zenfone 6

### OS

Android 13

**Comment by micahmo** [comment]
@CTalvio It looks like Thunder is rendering this exactly like the web UI. Do you agree?

| ![image](https://github.com/thunder-app/thunder/assets/7417301/de8a057b-6801-4b24-899a-e09c2827381f) |
| - |

| ![image](https://github.com/thunder-app/thunder/assets/7417301/ab6b596b-ec40-4242-9b11-a14cee0ba248) |
| - |

**Comment by CTalvio** [comment]
Interesting. It's still wrong.

The codeblock doesn't render, a line within it goes missing, and the codeblock ending shows up in plaintext.
