### ISSUE TITLE
Comment text area stops accepting taps after formatting

### ISSUE THREAD

**Issue by sukhmel** [thunder-app/thunder#1464]
### Bug Description

Sometimes, when writing a markdown text, input area blinks grey and stops accepting taps, making it impossible to open a keyboard after previewing and complicating navigation.

### Expected Behaviour

Text input area should always allow to tap for moving the caret position

### Steps to Reproduce

1. Start writing a comment
2. Let it's length exceed one line
3. Input `**` for creating a bold text

### Additional Context

It seems to never happen when formatted text is on the first line of the input 

IIRC, it sometimes requires to also input the paired `**`, but it may be not necessary 

It was happening before 0.4.0 but I was too lazy to report, sorry 😅

### App Version

0.5.0-1

### Device

Pixel 8 Pro

### OS

Android 14, build AP2A.240605.024

**Comment by sukhmel** [comment]
Completely forgot to add the reproduction video:

https://github.com/thunder-app/thunder/assets/5804169/69ccbd10-9d5c-4d98-91c5-94597ac0dc47

**Comment by hjiangsu** [comment]
Thanks for the report!

I looked into this, and it seems like Flutter's spell checking is causing exceptions when you input ** characters. I'm not sure if there's any way to fix this except for waiting the fix upstream. For now, I can disable spell checking on the inputs.

**Comment by hjiangsu** [comment]
Seems like this issue was already noted down upstream and there is a fix, but we have not yet upgraded to the Flutter version that contains that fix. See https://github.com/thunder-app/thunder/pull/1465#issuecomment-2185282875 for reference.

**Comment by micahmo** [comment]
By the way, I just wanted to chime in here and mention that you can use the markdown toolbar to make a word bold, rather than explicitly typing the `**`. That might help to mitigate this issue!

**Comment by sukhmel** [comment]
Yes, I also noticed after reporting that using format buttons helps, it's just that a habit of inputting text manually is too strong 😅

Thank you, will look forward to an update
