### ISSUE TITLE
Remove usage of `USE_EXACT_ALARM` permission

### ISSUE THREAD

**Issue by hjiangsu** [thunder-app/thunder#1532]
### Bug Description

Google Play no longer allows the usage of `USE_EXACT_ALARM` permission unless the app is declared to be a calendar or alarm app.

Because of this, we are unable to publish new versions of Thunder to the Google Play store.

![image](https://github.com/user-attachments/assets/d97994ab-b9fd-4125-9aec-b04eca5d4f08)

### Expected Behaviour

N/A

### Steps to Reproduce

N/A

### Additional Context

This permission was added in this PR: https://github.com/thunder-app/thunder/pull/1343

More context: https://developer.android.com/about/versions/14/changes/schedule-exact-alarms#calendar-alarm-clock

### Device

All

### OS

Android

**Comment by hjiangsu** [comment]
@micahmo

**Comment by micahmo** [comment]
Want me to take care of this? It just means our debugging page won't be able to send local notifications within a minute, which is fine.

**Comment by hjiangsu** [comment]
If possible, that would be great!
