### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by x4740N** [thunder-app/thunder#1548]
### Bug Description

Occurs when I try to reply to my own post using the reply button on the bottom of the post next to the scroll buttons

Cannot post comment as it says "Null check operator used on a null value" when I try to post comment

I am aware of this issue which seems to be the same but had gone away for the user

https://github.com/thunder-app/thunder/issues/1474

Have tried clearing cache both within the app and in android settings

### Expected Behaviour

Should be able to post comment without issue

### Steps to Reproduce

Steps to reproduce shown in screen recording

https://github.com/user-attachments/assets/16a0a15b-c345-452c-803d-f939c7d2fe7f

### App Version

v0.5.0

### Device

Samsung Galaxy a70

### OS

Android 11

**Comment by x4740N** [comment]
.

**Comment by hjiangsu** [comment]
Hey @x4740N!

Just checking, but were you able to resolve this issue? I saw that you marked it as complete but mentioned that v0.5.1 did not resolve the issue.
