### ISSUE TITLE
Setting to auto-hide read posts

### ISSUE THREAD

**Issue by blakeashleyjr** [thunder-app/thunder#1551]
### Is Your Feature Request Related to a Problem?

As my sessions gets longer (after a few minutes), I find myself constantly dismissing read posts and then dismissing the read posts that come in from the refresh.

### Feature Description

I would like a setting that automatically hides read posts and does not even display them when refreshing for new content.

Essentially a simple if statement, if the setting is enabled and the post has already been read, act as if it doesn't exist (and potentially refresh again until a certain number of posts are collected).

**Comment by ggichure** [comment]
In your account settings you can toggle it on or off. 

Also trust you have mark as read on scroll .


![Screenshot_20240905-190437_Thunder](https://github.com/user-attachments/assets/3993eafd-24ed-4007-9a90-95a330309e1d)

**Comment by blakeashleyjr** [comment]
I am running the latest release and don't have that option:

![Screenshot_20240905-121027.png](https://github.com/user-attachments/assets/42a5b000-98f4-46ea-b23c-e714f2cde116)

![Screenshot_20240905-121154.png](https://github.com/user-attachments/assets/f81aa4f7-f214-418b-80a5-8092434f7694)

But that does seem to be exactly what I am looking for.

**Comment by ggichure** [comment]
In your account settings you can toggle it on or off. 

Also trust you have mark as read on scroll .


![Screenshot_20240905-190437_Thunder](https://github.com/user-attachments/assets/3993eafd-24ed-4007-9a90-95a330309e1d)

**Comment by ggichure** [comment]
Its under Settings> Account

**Comment by blakeashleyjr** [comment]
Thanks, just found it. See my edit from above:

> There are "Feed Settings" under General and Account. I found it.
Of note, when searching "read" in the settings search, it does not return for me.

**Comment by micahmo** [comment]
@blakeashleyjr Thanks for raising this issue, and @ggichure thanks for jumping in to solve it! Yes, this feature is already implemented by the Lemmy backend, and the account setting that @ggichure pointed to should sync between Thunder and your Lemmy account (so if you ever happen to use the web UI, read posts will be hidden there as well).

> when searching "read" in the settings search, it does not return for me.

Setting search was improved to include account settings in PR #1541, which should be included in the next release.

https://github.com/user-attachments/assets/0688cc52-370c-4428-9574-cabedc842bd1

**Comment by blakeashleyjr** [comment]
I think it's good to close if the search will be fixed. I was going to recommend a possible settings reorg, because it doesn't feel like an "account" setting to me. The search fix should take care of it though.

**Comment by micahmo** [comment]
> I was going to recommend a possible settings reorg, because it doesn't feel like an "account" setting to me.

I totally hear what you're saying, and I think we're open to reorganizing things to make Thunder as easy as possible to use. The reason it's under Account settings is because... it literally is a setting of your Lemmy account. 😆 If you log into the web UI, you'll see the same setting. If it were anywhere else in Thunder, it might seem like a Thunder-specific setting.

| ![image](https://github.com/user-attachments/assets/a67f4f93-efc6-486e-a46e-3a485c54b2d5) |
| - |

We did add this little link in the general settings page to help you find the additional account settings. I'm not sure if it's in a released version or not yet.

https://github.com/user-attachments/assets/35add106-914c-4b60-8a58-edb891f012ea

**Comment by blakeashleyjr** [comment]
That makes sense and I think that is a perfect solution! Thanks for your time and attention on this. That isn't in my app (v0.5.1), so it must be in an upcoming version.
