### ISSUE TITLE
Upvotes/downvotes counts and time of comments ugly display 

### ISSUE THREAD

**Issue by cabillaud** [thunder-app/thunder#1586]
### Bug Description

Counts and time of comments in the post view are messed up
![Screenshot_20241028_103350](https://github.com/user-attachments/assets/dbde84a6-fb3d-4c49-9f6f-8ec18359f755)

### Expected Behaviour

Fields should be disctinctly readable

### Steps to Reproduce

Happens often in the comments view

### App Version

0.5.1

### Device

Honor Magic 5 lite (RMO-NX1) 

### OS

Android 13

**Comment by micahmo** [comment]
Is this a dup of #976?

**Comment by cabillaud** [comment]
Yes


Eric Engelmann
06 22 57 04 38

**Comment by micahmo** [comment]
Thanks for confirming, I'll close this one as a dup. If you have any other problems, please feel free to open a new issue. And please feel free to comment on #976 if you have any more info to add. Thanks!
