### ISSUE TITLE
For the overscroll function, please follow the system and don't override

### ISSUE THREAD

**Issue by Coffee-Viking** [thunder-app/thunder#163]
**Is your feature request related to a problem? Please describe.**

Pulling down when reaching the top of the screen makes the text and all menus stretch, this is a function Android refers to as "overscroll".

People with vision impairment however can get dizzy, so it can be disabled:

https://support.google.com/pixelphone/thread/132936922/how-to-turn-of-android-12-overscroll?hl=en

Thunder however overrides the system settings (regardless whether it's disabled via developer options or accessibility settings) and overscrolls regardless.

**Describe the solution you'd like**

Please follow the system default, or implement a manual switch to disable it.

**Describe alternatives you've considered**

None possible.

**Comment by hjiangsu** [comment]
I'll have to see what is causing this to happen - I'm not too sure how Flutter handles that setting, so this might take a bit more time to implement and fix

**Comment by Coffee-Viking** [comment]
Got it, appreciate the quick response!

**Comment by hjiangsu** [comment]
Sorry that this has taken so long to get to, but this is now in-progress! The solution that I'm working towards is to have a setting to reduce the animations used by Thunder.

Thunder itself (as far as I'm concerned), is not able to read the system settings, so this is my plan: introduce a new setting which reduces animations. When enabled, certain animations will be reduced/removed:
- Overscrolling effects from lists (feed, posts, etc)
- Potentially completely removing page transition animation when switching between tabs (in-discussion on Matrix)

Please let me know if there are any other potential animations that you would like to see removed or reduced when this option is on!

cc: @micahmo, @ajsosa, @CTalvio

**Comment by micahmo** [comment]
I like that plan! Here are a few more potential animations to eliminate in that mode. Not sure these are all equally important, they just came to mind.

* Navigation change (e.g., loading post)
* Comment expand/collapse
* Bottom modal

**Comment by hjiangsu** [comment]
Do you think we should completely remove the navigation change animation, or just drastically reduce the time it takes? I did a quick test and reducing it to zero makes it feel a bit jittery.

**Comment by micahmo** [comment]
Hard to say (even whether we should touch that one at all). Android has an animation speed setting which I know many people like to lower to make the phone feel more snappy. On the other hand, iOS has a reduce motion setting which turns many animations into dissolves. If this is about accessibility, then maybe the latter makes more sense. Then again, I don't know if we can turn SwipeablePageRoute into a dissolve.

**Comment by hjiangsu** [comment]
Just linking this as its relevant to the original issue: https://github.com/flutter/flutter/issues/10101#issuecomment-398940831
