### ISSUE TITLE
App doesn't start after update 

### ISSUE THREAD

**Issue by Offerel** [thunder-app/thunder#1633]
### Bug Description

After updating the app from 6.0.1 to 6.0.2, the app is stuck in the loading screen. Deleting the cache did not resolve the issue. Deleting data does. However with that, the settings are lost and you have to relogin.

BTW: can you please update the link for weblate, to point directly to the project in readme.md in github?

### Expected Behaviour

After update, the app should start normal 

### Steps to Reproduce

1. Download Apk from Github
2. Install as update 
3. When update is finished, start the app 
4. App starts
5. Is stuck in loading screen for several minutes 

### App Version

6.0.2

### Device

Sa.sung S23

### OS

Android 14

**Comment by hjiangsu** [comment]
Thanks for the report! Are you able to share your app settings prior to the update?

You can export them by going to Settings -> General -> Import/Export Settings -> Save Settings

@micahmo could you try to reproduce this as well and let me know if you are experiencing the same issue? Thanks!

**Comment by micahmo** [comment]
I have not noticed this issue yet, but I've been updating incrementally (i.e., I didn't jump straight from 0.6.0-1 to 0.6.0-2).

**Comment by hjiangsu** [comment]
@Offerel I just released v0.6.0-3 which should _hopefully_ fix the issue with Thunder hanging on the splash screen. Please let me know if this fixes the issue!

I'll keep this open until it's confirmed that the issue has been resolved.

**Comment by Offerel** [comment]
I'm not sure, if this was the correct settings, directly before the update, but i think, i havent changed anything after making this settings backup:
`{"setting_enable_change_sort_fab":false,"setting_theme_metadata_font_size_scale":"small","setting_enable_dismiss_read_fab":false,"setting_general_show_full_height_images":false,"current_version":"0.5.0","setting_general_show_save_action":false,"setting_general_scrape_missing_previews":true,"setting_use_profile_picture_for_drawer":true,"active_profile_id":"1","setting_compact_tappable_author_community":true,"settings_comment_show_user_instance":false,"setting_general_mark_post_read_on_media_view":true,"setting_theme_use_material_you":true,"setting_post_default_comment_sort_type":"new_","setting_browser_mode":"customTabs","setting_general_default_listing_type":"all","thunder_last_notifications_poll_time":"2024-08-15 22:30:27.715442","setting_notifications_show_inapp_update":true,"setting_post_fab_enable_change_sort":false,"setting_feed_card_divider_color":0,"setting_general_default_sort_type":"new_","user_full_name_user_name_color":"theme_primary","setting_general_show_post_author":true,"setting_general_show_vote_actions":false,"setting_general_show_title_first":true,"setting_general_hide_topbar_on_scroll":true,"setting_general_show_community_icons":false,"setting_general_use_compact_view":false,"setting_use_display_names_for_users":true,"setting_general_post_body_view_type":"expanded","setting_feed_card_divider_thickness":"comfortable","setting_enable_back_to_top_fab":false,"setting_general_show_text_content":true,"setting_app_language_code":"de","setting_enable_subscribed_fab":false,"setting_general_combine_comment_scores":true,"setting_theme_title_font_size_scale":"large","setting_general_mark_post_read_on_scroll":true,"setting_post_fab_enable_refresh":false,"setting_general_show_edge_to_edge_images":false,"video_auto_play":"always","setting_general_show_comment_button_actions":true,"setting_inbox_notification_type":"local","setting_enable_refresh_fab":false,"setting_general_hide_nsfw_previews":false,"setting_post_fab_enable_back_to_top":false}`

Anyway, after removing all data (which should be the same as reinstalling), i could import exactly this settings file without any issue The app starts with this settings without any issues.

**Comment by hjiangsu** [comment]
I'll be closing this as I believe it should now be working as of v0.6.0-3. Let me know if any additional issues pop up regarding updating to the latest nightly build!
