### ISSUE TITLE
Disable swipe action only does for posts

### ISSUE THREAD

**Issue by Coffee-Viking** [thunder-app/thunder#164]
**Description**  

Disabling swipe actions in the settings disables them for posts only, they still persist for comments.

**Expected Behavior**  

Disabling swipe should do so app-wide, and in case of the comments, should then add a function bar below for reply, star, share, up & downvote.

Alternatively, allow disabling swipe for posts and comments separately.

If current implementation is as intended (least favorite, I hate swiping), rename setting to "disable swipe actions for posts".

**Comment by hjiangsu** [comment]
Hey! For now, that was intentional - I want to add in an alternative way of voting and performing actions within comments before I add in an option to disable the swipe gestures on them

**Comment by Coffee-Viking** [comment]
Understood, then I'll wait patiently. To me the swiping is annoying since sometimes swiping out of the comments back into the frontpage causes me to vote or save a comment by accident.

**Comment by hjiangsu** [comment]
Definitely, I do want to make alternative actions for comments a higher priority for the next release (v0.2.1+10)

**Comment by hjiangsu** [comment]
Just an update - this will be added as part of the next general release!

Quick preview:

![simulator_screenshot_4533EF3C-83EC-4F8E-9B13-AD6204958335](https://github.com/thunder-app/thunder/assets/30667958/0afbff2b-0126-4c91-acb6-e7a62297cb5b)
