### ISSUE TITLE
Mark post as read when they are scrolled past

### ISSUE THREAD

**Issue by tunglith** [thunder-app/thunder#169]
**Describe the solution you'd like**
A post that is opened, upvoted or scrolled by should be considered read. This would allow for future enhancements such as "Discard read posts button" or "unread only" feed.

**Comment by hjiangsu** [comment]
I think it makes sense for post that are opened or voted on the be marked as read. For marking posts on read when scrolling through them, maybe this can be a toggle in the settings?

**Comment by tunglith** [comment]
In Relay's case it was a setting, so you've got the right idea !

**Comment by Offerel** [comment]
Any news about this feature?

**Comment by hjiangsu** [comment]
@Offerel This is being worked on and should be coming soon! This is the PR associated with this issue: https://github.com/thunder-app/thunder/pull/1139

**Comment by Offerel** [comment]
Thanks for the info. I've been watching the PR for some time now. I can really look forward to testing the first trial version as an APK

**Comment by hjiangsu** [comment]
This should now be released to 0.3.0. Please open up a new issue if you find any issues with the feature!
