### ISSUE TITLE
Button to discard read posts from the feed or an "unread only" feed

### ISSUE THREAD

**Issue by tunglith** [thunder-app/thunder#170]
**Is your feature request related to a problem? Please describe.**
When going back to the app after a few hours, the top posts are often the same and require a lot of scrolling to get new stuff. This is not an issue in itself as it's good to see posts rising and to be able to go back to them to see new comments, sometimes we want to get to the new stuff.

**Describe the solution you'd like**
The initial request is inspired by Relay for Reddit which main central button is used to discard the read posts from the feed. This way when you open the app, even though the feed is still r/all in hot or whatever, the read post (which have a darker background) are discarded and unread posts are brought to the top.

**Describe alternatives you've considered**
Although I love this feature because it prevents me from scrolling through the same posts every time I open the app, it's not perfect. If you have read a lot of posts, discarding the read posts will force to fetch new posts which can include read posts and the button would have to be clicked again.

An alternative could be a second feed or a toggle (maybe next to the sort options button in the top right) to hide read posts entirely and only get the new stuff ?

**Additional context**
You'll find a screen record bellow of how the discard button works in relay (speedran to fit into Github's 10Mb limit).

https://github.com/hjiangsu/thunder/assets/40027008/108d79af-a78c-48d9-bb24-eadd6a276776

**Comment by Poolitzer** [comment]
> An alternative could be a second feed 

The issue with adding another feed that feeds right now act as filters (subscribed, local, all), and you might want to have any of these combined with unread. So you would need three more filters which is too much for the left sidebar.

> or a toggle (maybe next to the sort options button in the top right) to hide read posts entirely and only get the new stuff ?

I dont like mixing sort by and filter by options in one interface.


In my opinion, we need a new menu, a filter menu. There is still space in the upper menu bar to add one more icon, and then lets filter away.

**Comment by hjiangsu** [comment]
> An alternative could be a second feed or a toggle (maybe next to the sort options button in the top right) to hide read posts entirely and only get the new stuff ?

Just adding in that this could be tied in with #174 for a filtering button to allow you to quickly toggle different settings in the feed

**Comment by Poolitzer** [comment]
Basically happened in #273 now.

**Comment by tunglith** [comment]
Not sure I get what you mean, we're talking about the main feed not search results ?

**Comment by Poolitzer** [comment]
Your issue does, but the last few comments didn't, which I wanted to follow up/close with this.

**Comment by Lippiece** [comment]
Ability to filter read posts would be a major victory of this app over the others, imho.

**Comment by hjiangsu** [comment]
The ability to hide read posts has been added in this PR: https://github.com/thunder-app/thunder/pull/921

> The initial request is inspired by Relay for Reddit which main central button is used to discard the read posts from the feed.

Similarly, this has already been implemented so I'll mark this issue as fixed for next release!
