### ISSUE TITLE
Close image when swiping from anywhere

### ISSUE THREAD

**Issue by ContraMuffin** [thunder-app/thunder#173]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, per se, but as of right now, you can only close an image by swiping from the image. Any swipes that do not start on the image do not count. This makes it somewhat unintuitive to close images, especially if images are different sizes or if they are small. My thumb needs to reach at an awkward angle in order to reach the image. It's especially noticeable because the only other way to close an image is by pressing the back button on my phone's row of menu buttons (Android).

**Describe the solution you'd like**
It would be really sweet if swipes from any area of the screen (not just the area covered by the image) will count toward closing the image. For instance, if I swipe upward from the bottom corner of the screen, that would close the image

**Describe alternatives you've considered**
Another possible alternative will be to add an explicit back button in an easily reachable place. As I mentioned above, the only other way to close an image is by pressing the back button on the row of menu buttons. This seems pretty limited, so adding other options to close images would be welcome.

**Additional context**

**Comment by CTalvio** [comment]
Addressed by #317
