### ISSUE TITLE
Use browser provided Custom Tabs on Android

### ISSUE THREAD

**Issue by vfosnar** [thunder-app/thunder#176]
**Is your feature request related to a problem? Please describe.**
the webview does not respect user selected browser (no addons support, etc.)

**Describe the solution you'd like**
Use Android Custom Tabs: https://android.stackexchange.com/a/219950

**Describe alternatives you've considered**
Webview - no addons
Open in external browser automatically - creates a new tab for every link I click

**Additional context**
None

**Comment by hjiangsu** [comment]
Interesting - I'll have to take a closer look at that when I have the time. Thanks for sharing it!

**Comment by jordan1776** [comment]
If I can add a feature to this is to include support for chrome private custom tabs as well. Jerboa has this feature.

**Comment by micahmo** [comment]
A potentially related issue is the fact that, if you navigate several levels deep in the embedded browser, pressing back will go back to the post. Android Custom Tabs might handle this better.
