### ISSUE TITLE
[Feature Request] Confirmation dialog box on exit

### ISSUE THREAD

**Issue by avasts** [thunder-app/thunder#179]
As of v0.2.1+10 on Android, I am now accidentally exiting the app instead of going back because of not paying attention to where I am in the app. Can a (ideally optional checkbox in settings) dialog box be added to confirm app exit? Maybe even make it an option where the back button doesn't exit the app, but a dialog box would definitely be helpful.

**Comment by hjiangsu** [comment]
I think maybe a good solution for this is to have double tap back to exit the app? This might be easier to implement than a whole dialog

This can then also be a setting (although I'm not sure how useful it would be) to toggle this functionality on/off

**Comment by micahmo** [comment]
@avasts Are you happy with the fix in #245? I am going to mark this fixed unless you disagree.

**Comment by avasts** [comment]
Yeah, I think this is a great implementation. Thank you!
