### ISSUE TITLE
Pinch zoom only works once

### ISSUE THREAD

**Issue by subhashay** [thunder-app/thunder#193]
**Description**  
After clicking on the image post and trying to zoom on the picture works as long as I don't lift my finger. When I lift my fingers and try to zoom again, it doesn't work.

**How to Reproduce**  
1. Open any image post
2. Click on the image
3. Pinch to zoom in or zoom out
4. Lift your fingers off the screen and then try pinch to zoom again. Fails here.

**Expected Behavior**  
Ideally I should be able to zoom in and out every time.

**Screenshots**  
NA

**Device & App Version:**  
 - Device: Pixel 6
 - OS: Android 13
 - Version 0.2.1

**Additional Context**  
NA

**Comment by subhashay** [comment]
Hmm, I just tried a few combinations and you're it's kinda flaky. 

What I further observed is after pinching in to zoom, if you try to zoom out (by pinching out) from the exact spot where you pinched in, it works. But trying from different places fails.

**Comment by everdred** [comment]
>if you try to zoom out (by pinching out) from the exact spot where you pinched in, it works. But trying from different places fails.

Yep, confirming it's the same for me! I hadn't noticed that specifically.

**Comment by CTalvio** [comment]
This is because the actual image "area" is only the size that the image starts off at.

Trying to do any gestures outside that area, even after expanding the image, does not work.

I've fixed this in #317
