### ISSUE TITLE
Show username in posts and instance name in comments

### ISSUE THREAD

**Issue by micahmo** [thunder-app/thunder#197]
**Is your feature request related to a problem? Please describe.**
When scrolling posts, I can see the the community and instance name. When I click on a post to view the comments, I can see the username and the community.

**Describe the solution you'd like**
It would be nice to see all three things in both places. However, I realize that screen real estate is tight in the list of posts. At the very least, I think it would be very nice to see the full community and instance name in the comment view.

**Describe alternatives you've considered**
I just wanted to say it's nice that we can click the community and go to its page. That's very nice!

**Additional context**
N/A

**Comment by micahmo** [comment]
The first half of this (show username in posts) was completed in #381.

**Comment by hjiangsu** [comment]
@micahmo Do you think this is still relevant? Or has it been fixed be a previous PR?

**Comment by micahmo** [comment]
I am not exactly sure what I meant in the initial issue. 😆 But I would eventually like to optionally see the instance name for the user and community in the post body. Should that be a new issue?

**Comment by micahmo** [comment]
I think this issue has been resolved by various changes over time. 😊
