### ISSUE TITLE
Swipe goes back when actions are disabled

### ISSUE THREAD

**Issue by micahmo** [thunder-app/thunder#198]
**Is your feature request related to a problem? Please describe.**
When swiping on posts/comments are disabled, swiping does nothing. We can take advantage of this additional operation.

**Describe the solution you'd like**
It would be nice if swiping from left-to-right in the comments view would go back to the main posts view. It would be nice if swiping from left-to-right in the main posts view would open the hamburger menu. Both of these things are implemented by Relay for Reddit and Jerboa, if you want examples.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jordan1776** [comment]
>It would be nice if swiping from left-to-right in the main posts view would open the hamburger menu. 

This is already implemented as a partial swipe on the left edge.

**Comment by micahmo** [comment]
> This is already implemented as a partial swipe on the left edge.

I can't get this to work, can you demonstrate? On Android, if I swipe from the very left, it goes back. I would prefer a swipe somewhere in the middle.

**Comment by jordan1776** [comment]
That is what I mean, the swipe on the very left edge. Maybe it should be more forgiving by extending it a few pixels right so it should be possible to swipe it with your right thumb, but I actually prefer the something like the current behavior over going half screen or Fullscreen with gestures on.

**Comment by micahmo** [comment]
This has been working much more consistently as of #1413. Any objections to closing?

**Comment by hjiangsu** [comment]
No objections!
