### ISSUE TITLE
Indicate originating instance of comments

### ISSUE THREAD

**Issue by micahmo** [thunder-app/thunder#200]
**Is your feature request related to a problem? Please describe.**
Since comments can be posted cross-instance, it's not always clear where a comment came from (whether it's my current instance, the instance of the post, or another one).

**Describe the solution you'd like**
Show the originating instance in the comment view. I'm not sure whether this should always be shown (which might clutter things) or be available from a menu.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CTalvio** [comment]
I'd prefer the usernames become tappable to open the user profile, same as poster usernames right now.

Eventually comment should also be long tappable, like posts, to view additional info and a menu with actions outside the configured gestures.

It doesn't really matter what instance someone is on, so in the name of minimalism, I would not display it.

**Comment by CTalvio** [comment]
#281 will make comment usernames tappable

**Comment by micahmo** [comment]
I'm happy having these details available via tooltip (#319), although I believe @hjiangsu said he might consider showing this on the main UI (optionally), so I will leave this open for now.
