### ISSUE TITLE
Remember the collapsed state of comments when collapsing/expanding parents

### ISSUE THREAD

**Issue by micahmo** [thunder-app/thunder#204]
**Is your feature request related to a problem? Please describe.**
The collapsed state of comments is not remembered.

**Describe the solution you'd like**
The collapsed state of comment should be remembered within a thread. For example...
Collapse a second-level comment. Collapse a top-level comment. Expand the top-level comment. The second-level comment is now expanded again.

Another possible enhancement would be to remember even when leaving the comment feed and coming back, but that may be a separate issue and/or undesirable.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hjiangsu** [comment]
> Another possible enhancement would be to remember even when leaving the comment feed and coming back, but that may be a separate issue and/or undesirable.

Did we still want to implement this feature here? I kept this open previously because we don't currently have this! Although I'm not sure if this should be the default behaviour or not

**Comment by micahmo** [comment]
Ahh, the title of this issue, "Remember the collapsed state of comments when collapsing/expanding parents" is implemented, but as I re-read my request, the second part, "remember even when leaving the comment feed and coming back" is not. Should I open a separate issue for that?

**Comment by hjiangsu** [comment]
Yeah, we can open up a new issue for this!

**Comment by micahmo** [comment]
Done in #742.
