### ISSUE TITLE
Optionally mark post as read when media is viewed

### ISSUE THREAD

**Issue by micahmo** [thunder-app/thunder#205]
**Is your feature request related to a problem? Please describe.**
Sometimes I only view the picture associated with a post and never open the comments. Then I see it later as unread and am confused.

**Describe the solution you'd like**
I understand that not everyone will desire this, so it could be optional. But I would like to mark a post as read as soon as I view the media associated with it, even if I have not navigated to the comments. This is a feature of Relay for Reddit, for example.

**Describe alternatives you've considered**
Maybe there could be a Mark as Read quick action so that it's still intentional but quicker than opening the comments.

**Additional context**
N/A

**Comment by ajsosa** [comment]
@hjiangsu I implemented this behavior for myself in my custom build but not sure how you would like this to work for everyone. Would you prefer a toggle-able option for this behavior? If so, what should be the default?

**Comment by hjiangsu** [comment]
I think this should be a toggle-able action! I would prefer the default for it to be off (post stays unread until you open it) simply so that it matches the current behaviour

If we do end up getting a lot more feedback about having this enabled by default, then we can switch it then!

**Comment by micahmo** [comment]
Thanks for the consideration @hjiangsu! I don't mind turning this on manually, as long as the option is there. 😊 I also think a new swipe action could be an alternative way to accomplish this. Why not both! 😉 Of course, this is not a super high priority.

**Comment by micahmo** [comment]
@hjiangsu Can we mark this as fixed in next release?
