### ISSUE TITLE
Navigate directly from media to comments

### ISSUE THREAD

**Issue by micahmo** [thunder-app/thunder#206]
**Is your feature request related to a problem? Please describe.**
When I am viewing media, it takes two actions to view the comments (back to the main posts view, then click on the post).

**Describe the solution you'd like**
It would be nice to have a comments button on the media. That way the workflow could be very simple:
Open media -> Open comments
Rather than the extra step of going back to the main posts view before opening the comments.
Relay for Reddit has this feature, for example.

**Describe alternatives you've considered**

**Additional context**

**Comment by CTalvio** [comment]
In addition, I would like for image view to have three buttons along the bottom, open post( ie go to comments ), save, and share. The only current button, save, being in the top corner is a reachability mistake, when the bottom right is perfectly unused.

The share option should provide the option to either share a link to the post on lemmy, or to share the image file directly.

**Comment by micahmo** [comment]
> share the image file directly

Yes, +1 to this idea too (maybe a separate enhancement).
