### ISSUE TITLE
Add refresh option other than scroll up

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#207]
The only way to trigger a feed refresh is currently to scroll all the way up.

My vote is for a refresh button next to the sort button in the top right, same as in inbox. it should also appear on community pages and for comments.

Also add pull down to refresh to inbox.

**Comment by bactaholic** [comment]
Been working on this issue, I successfully added a manual refresh button to the home screen, just working on getting a pull to refresh for the inbox, but I'm running into a lot of problems getting the refresh to activate. Tried using `RefreshIndicator()` when I tell it to `onRefresh: context.read<InboxBloc>().add(const GetInboxEvent());` it throws an error.

Removing my work for the inbox until I can get something working, but I'll commit my other changes so hopefully we can get the refresh button on the home screen in the next release.

**Comment by bactaholic** [comment]
pull request relating to this issue, #213

**Comment by hjiangsu** [comment]
@bactaholic I'll assign this to you for now if thats okay!

**Comment by bactaholic** [comment]
@hjiangsu sure thing!

**Comment by CTalvio** [comment]
I spotted the refresh button in some new places. Nice.

I also noticed, that it is not possible to refresh on the comments and saved tabs in the profile view.

**Comment by bactaholic** [comment]
@CTalvio howdy, yeah I noticed it's missing from a few places as well. I'll be going through all the pages and adding refresh options where needed, just finished implementing pull-to-refresh in the inbox, but I gotta clean up my code and add a quick fix for an error when refreshing within communities, then I'll be moving onto adding refresh to all pages.

**Comment by krestenlaust** [comment]
Shouldn't this have an "fixed-in-upcoming-release"-tag?

**Comment by CTalvio** [comment]
@bactaholic Bug report for you, when in "All" I noticed the button goes back to "Local posts" when used, while pull down to refresh does not.

**Comment by bactaholic** [comment]
> @bactaholic Bug report for you, when in "All" I noticed the button goes back to "Local posts" when used, while pull down to refresh does not.

@CTalvio Does the behavior match that of #216 by chance? Sounds similar, if so, I have that fixed in a pull request that was successfully merged a few days ago, I imagine it will be in the release version soon.

**Comment by CTalvio** [comment]
I'm on the latest alpha. That particular issue is already fixed.

Essentially, refreshing does not just refresh the current feed, it also resets to your default, be that local/subbed/all.

**Comment by bactaholic** [comment]
> I'm on the latest alpha. That particular issue is already fixed.
> 
> Essentially, refreshing does not just refresh the current feed, it also resets to your default, be that local/subbed/all.

Oh whoops, edited, fast reply lol. Yeah I will get it fixed in my current pull request, unless it gets merged into the develop branch before I can do so haha.

**Comment by bactaholic** [comment]
@CTalvio fixed in PR  #245 , though I need to resolve the conflicts before it can be merged into the develop branch
