### ISSUE TITLE
Refresh button in communities refreshes the home feed while still in the community

### ISSUE THREAD

**Issue by tunglith** [thunder-app/thunder#216]
**How to Reproduce**  
1. Go to a community
2. Tap the new refresh button next to the sorting option
3. Header of the community remains but posts are from other communities

**Expected Behavior**  
Refresh the community posts while respecting sorting option

**Screenshots**  
![Screenshot_2023-07-04-13-55-40-942_com hjiangsu thunder](https://github.com/hjiangsu/thunder/assets/40027008/8d60f92a-8859-4881-83f8-19c70e4e4761)

**Comment by hjiangsu** [comment]
I'm gonna pull in @bactaholic for this one - maybe you could take a look into it? :D

**Comment by bactaholic** [comment]
> I'm gonna pull in @bactaholic for this one - maybe you could take a look into it? :D

Ahhh...yeah. That was an oversight lol, I'll look into it.

**Comment by bactaholic** [comment]
this should be fixed by #227
