### ISSUE TITLE
Option to disable a swiping/gesture action

### ISSUE THREAD

**Issue by krestenlaust** [thunder-app/thunder#217]
**Is your feature request related to a problem? Please describe.**
Gesture customization was recently added, it's awesome. But it would be even better to have to option to disable a dragging option. 

**Describe the solution you'd like**
- Configuring both "<" and "<<" to nothing at the same time will recent in no drag being triggered towards that side.
- Configuring only "<" will remove the extended drag option.
- It probably shouldn't be possible to only configure "<<"

**Describe alternatives you've considered**
Unsure.

**Additional context**
Based on this [comment](https://github.com/hjiangsu/thunder/issues/195#issuecomment-1619581449).

**Comment by Tealk** [comment]
> * It probably shouldn't be possible to only configure "<<"

Why?
I would have liked to use this as a replay and turn off the short wipe, less mistake

**Comment by krestenlaust** [comment]
> Why? I would have liked to use this as a replay and turn off the short wipe, less mistake

Oh right, I didn't think of that, that's pretty useful. Though if hijangsu plans on adding customized thresholds anyway, then it might be best to not over complicate it 🤷‍♀️

**Comment by CTalvio** [comment]
Swipe gestures can now be set to none.
