### ISSUE TITLE
Comments L4 and below are collapsed by default

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#221]
**Description**  
Comments levels 1, 2, and 3 are expanded while comments below this level are not

**How to Reproduce**  
1. Go to any post with many deep comments such as [this one](https://lemmy.world/post/1013126)
2. See error

**Expected Behavior**  
All levels should be expanded by default

**Screenshots**  
![Screenshot_20230704-111246_Thunder](https://github.com/hjiangsu/thunder/assets/116814522/ad718665-61d6-4cc6-ba4e-7f8240d74717)

**Device & App Version:**  
 - Device: [e.g. iPhone6] Motorola One 5G Ace
 - OS: [e.g. iOS8.1] Android 11
 - Version [e.g. 22] multiple

**Additional Context**

**Comment by CTalvio** [comment]
I'm fairly certain this is intentional. The WebUI also collapses large comment chains.

A good feature, would be a clear indications for when there are additional comments, but they are collapsed, as requested in #190

**Comment by hjiangsu** [comment]
Yup this is intentional to prevent long comment chains from becoming the main view.

It could be possible to have some level of customization here with how many levels are down by default but that would be lower priority unless the community feels otherwise!

**Comment by shortwavesurfer2009** [comment]
I like the way redreader did it. They went to L10 and then had a "load more" button that opened another screen with what was the l10 at the top and then any other replies under it. That may be an option here too. Have L1, L2, L3, Load More. And that Load more would open a new screen with that L4 at the top and continue on down the comment chain. When done you hit the back button and you are back in the main comments for the OP.

**Comment by guigs4** [comment]
Apollo did the same 👆🏼

**Comment by hjiangsu** [comment]
I would like to say that this issue is more or less resolved. While comments are collapsed beyond a given level, the comments within the collapsed comment will stay expanded.

This should ideally help fix a bit of issues around having to expand every single comment.

I'll close this issue, but do let me know if this is still not resolved!
