### ISSUE TITLE
Can't vote on comments in quick succession

### ISSUE THREAD

**Issue by krestenlaust** [thunder-app/thunder#230]
**Description**  
When updating a row of comments quickly after one another, it's often only the first one gets a reaction. The same effect happens if it's the same comment you are trying to toggle quickly.

It makes the app feel unresponsive.

**How to Reproduce**  
1. Go to a post
2. Vote on some comments in quick succession

**Expected Behavior**  
No matter how fast the instance/server is, the UI should update immediately. You could consider to adding a short debounce delay to not stress the instance (if changing a vote is stressing)

**Screenshots**  
https://streamable.com/ef1oen (expires in 2 days apparently)

**Device & App Version:**  
 - Device: OnePlus 6T
 - OS: Android 11
 - Version: v0.2.1+10

**Additional Context**  
~~It doesn't seem to happen when voting on posts on the timeline.~~

Edit: It's the same on posts, but it feels like it's faster when it's two different instances.

**Comment by krestenlaust** [comment]
Weird how there's no label on this post

**Comment by Poolitzer** [comment]
Did you open it with GitHub mobile?

**Comment by krestenlaust** [comment]
yeah, it's probably related

**Comment by CTalvio** [comment]
WebUI seems to handle voting on a bunch of comments very quickly, would be nice if thunder did too.

**Comment by hjiangsu** [comment]
This has been added in. It'll be a part of the next pre-release version. I've set it so that voting and saving comments are no longer throttled

**Comment by krestenlaust** [comment]
Awesome! Just wanted to say you're all doing a fantastic job developing this app, remember to take the time off you need @CTalvio @hjiangsu @micahmo 

(p.s. no need to reply, just showing some appreciation!)
