### ISSUE TITLE
Add unread count to inbox icon

### ISSUE THREAD

**Issue by Fmstrat** [thunder-app/thunder#233]
**Is your feature request related to a problem? Please describe.**
I had 19 unread messages, but had no idea because there was no indicator.

**Describe the solution you'd like**
A number placed over the inbox icon displaying the unread count. This wouldn't need to be live, probably just updated on app load and when marking items in the inbox read.

**Comment by krestenlaust** [comment]
It would be awesome if it was live though, but I'm not sure if that's even possible with new lemmy backend. The client would probably have to query every once in awhile.

**Comment by kaibagley** [comment]
Hey, 

New to flutter, trying my best. 
https://github.com/kaibagley/thunder/commit/e5b16972359c78dba552e624894b679ed86e8314

Here is an attempt from me to do this. I'm sure it's not done super well, as I'm new to this, but it seems to work.
A problem with it though is that it adds quite a bit of lag to page switching. Anyone got any ideas on how I can improve this?

**Comment by krestenlaust** [comment]
I recommend you make a draft pull request (just like a normal one, but select draft), it's easier to look into implementation with the tools there :)

**Comment by hjiangsu** [comment]
I second that! It'll make it easier for me to see the changes and provide any feedback!

**Comment by hjiangsu** [comment]
One idea for this is to do polling for new notifications every so often (e.g. every couple minutes) and update the inbox icon to show new replies. This polling would run in the background while you're using the app

There might be a possibility (if web sockets are enabled in the future) to just open up a connection and get live notifications that way

**Comment by kaibagley** [comment]
So sorry guys, please feel free to just smash this out if anyone is able to do it. I've been very busy and haven't had much time to look at this recently

**Comment by krestenlaust** [comment]
> So sorry guys, please feel free to just smash this out if anyone is able to do it. I've been very busy and haven't had much time to look at this recently

We're all only into open-source for the fun of it. You shouldn't pressure yourself!

**Comment by hjiangsu** [comment]
This is being worked on and an initial implementation is slated to be released in the next upcoming version
