### ISSUE TITLE
Colorized usernames

### ISSUE THREAD

**Issue by lazerleif** [thunder-app/thunder#240]
**Is your feature request related to a problem? Please describe.**
Coming from Reddit client infinty i really miss that usernames isn't in color. Would be nice if it could follow a theme or something. It would be easier to see if usernames isn't same color as the comments.

**Comment by hjiangsu** [comment]
Could you provide a bit more detail on where you'd like to see coloured usernames? Having some screenshots for ideas would also be good!

Currently, coloured usernames are reserved for distinguishing users (the original poster, yourself, and admins)

**Comment by lazerleif** [comment]
Oh of course. I was talking about in the comments.

Just a diffrent color from the comment text. I took an example from infinty.

You can still have colored usernames for OP myself and admins. But just change the "others" to another color than white 

![Screenshot_20230708-234853_Infinity](https://github.com/hjiangsu/thunder/assets/37516628/a53d2199-c840-4083-ad01-74eaa9d2047a)

**Comment by CTalvio** [comment]
I really like them just being white.
