### ISSUE TITLE
All screens should go back to home feed before exiting app

### ISSUE THREAD

**Issue by jordan1776** [thunder-app/thunder#243]
**Is your feature request related to a problem? Please describe.**
This enhancement expands on #180. When pressing back on the main screens of search, profile, inbox, and settings the app is exited.

**Describe the solution you'd like**
When on those screens, the back button should go to the home feed. Then pressing back again should exit the app.

**Describe alternatives you've considered**
A double tap to exit or popup would be welcome on the home feed.

**Comment by tunglith** [comment]
Strongly agree with that one. Many times I go back from the settings or profile and am thrown out of the app.

**Comment by bactaholic** [comment]
If accepted this should be partially fixed by #245, app now asks to confirm before exit and if a back button press/swipe is made again it dismisses the exit warning. Still working on getting it to navigate back to home if using the back button/swipe from any navbar page but the first.
