### ISSUE TITLE
Make API errors not take up the whole screen

### ISSUE THREAD

**Issue by Maritsu** [thunder-app/thunder#248]
**Is your feature request related to a problem? Please describe.**
With slow internet causing timeouts, your instance of choice being overloaded, or the target instance having downvotes disabled, API errors can occur, which, as of 0.2.1, display an error taking up the whole screen and forcing you to reload all content.

**Describe the solution you'd like**
Maybe do something similar to what Connect does and display a pop-up somewhere that describes the error

**Describe alternatives you've considered**
- Pop-ups at the bottom of the screen
- Any other non-fullscreen way of notifying the user about an error

**Additional context**
A "downvotes are disabled" error as of 0.2.1
![API error taking up the whole screen](https://github.com/hjiangsu/thunder/assets/66056347/a9895266-7a1c-4135-9c27-7f4c863b9fca)
An example of what the Github app does in case of an error (Connect does the same thing)
![Example of what Github does on mobile](https://github.com/hjiangsu/thunder/assets/66056347/c9e5a236-0aad-47d7-a697-0f4623dcb9d2)

**Comment by krestenlaust** [comment]
That last screenshot is pretty meta😄

Is this the error you are referring to? #19

**Comment by Maritsu** [comment]
Not really; what I mean is API errors (e.g. timeout) taking up the whole screen and forcing you to reload all content

**Comment by krestenlaust** [comment]
I meant the one in additional context. You wrote "downvotes are disabled" or something along those lines :)

**Comment by Maritsu** [comment]
Oh yea, that too. Feels like disabling the downvote button could also be a good enhancement.  
I chose to use a screenshot of "downvotes disabled" because that's the error that I could reproduce the easiest

**Comment by Maritsu** [comment]
Apparently this is already done in the comments view, from what I have just noticed

**Comment by hjiangsu** [comment]
This is partially in progress (as you've mentioned)

The next big focus for this would be to remove the fullscreen error messages from the feed page (whenever its suitable) and migrate to using toast notifications for them!

**Comment by hjiangsu** [comment]
I'll mark this as fixed as it should be addressed in the next release
