### ISSUE TITLE
Upvote and downvote button color customization.

### ISSUE THREAD

**Issue by jordan1776** [thunder-app/thunder#25]
**Is your feature request related to a problem? Please describe.**
[This is related to this discussion](https://github.com/hjiangsu/thunder/discussions/1#discussioncomment-6211638)

**Describe the solution you'd like**
Colors for up/downvote should by default match Lemmy's (blue #007bff for up and dark orange #873208). There should a setting in customization to use colors for reddit (orangered/periwinkle) and kbin (green/red)

**Additional context**
Directly or indirectly asking the user in a first install OOBE what vote colors to user along with post view/gestures/etc could be a nice feature for the future.

**Comment by ShambhavII-Singh** [comment]
hi can you assign this to me?

**Comment by jordan1776** [comment]
> hi can you assign this to me?

You could check with the Matrix chat if anyone else is working on it. Looking back maybe asking for preset color combos might not have been the best choice and probably using the color picker dialog from "Accent colors" would be better (but I don't think that was a thing back then). One for upvotes and one for downvotes.

**Comment by micahmo** [comment]
Hey @ShambhavII-Singh, I've assigned this issue to you for now. As @jordan1776 said, you're welcome to join the devs in Matrix at https://matrix.to/#/#thunderapp:matrix.org. There you'll have a better idea of who's doing what. But of course, you're welcome to contribute without joining or even being assigned an issue. PRs are welcome!

To @jordan1776's point about colors, we have been leaning heavily into coloring elements based on the current theme using `alphaBlend` ([example](https://github.com/thunder-app/thunder/blob/53ff594fac6baff31f22e06d960ef3c0ea0dfc36/lib/shared/comment_header.dart#L293)). But I also get the desire to set specific colors for upvote/downvote. Feel free to put together a proposal and we'll let the community weigh in!
