### ISSUE TITLE
Anonymous account

### ISSUE THREAD

**Issue by trymeouteh** [thunder-app/thunder#269]
The Infinity app for Reddit is a multi reddit account Android client. You can sign to multiple reddit accounts and you can also use the apps anonymous account feature. The anonymous account is browsing reddit without being in any of your accounts and essentially just like browsing reddit in a inconigo tab and not being logged in.

**Comment by CTalvio** [comment]
How would this work? You'd still have to use some instance or other?

**Comment by trymeouteh** [comment]
> How would this work? You'd still have to use some instance or other?

Not only will you be able to add accounts, you can add an instance.

When browsing an instance, you are not using any account

**Comment by CTalvio** [comment]
Ah. So you'd want to be able to add a entry to the "account" list, with no login? Just an instance. That could work well.

**Comment by SergeantPanda** [comment]
I believe that is how Connect works. You are able to use a 'Guest' account for some instances that you do not want to log in to. It seems to work well.

**Comment by trymeouteh** [comment]
Essentially there would be two kind of accounts. Instances and actual accounts. When you browsing an instance, your not logged into any account. When your browsing under an account, your logged into an account on a specific instance.
