### ISSUE TITLE
New comments indicator

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#272]
Looking into adding some kind of indicator for when a post you've already read has new comments.

The Lemmy web UI tells you when a post you've already read has new comments, and also highlights new comments in the comment view.

I'd like to implement both of these. @hjiangsu feel free to assign this one to me as well.

En example of what this could look like:

![image](https://github.com/hjiangsu/thunder/assets/4365015/acf532d4-f39d-4f85-aa76-7ce4f2b07325)

**Comment by CTalvio** [comment]
I have settled on something like this:

![image](https://github.com/hjiangsu/thunder/assets/4365015/919b19bd-55a6-4bb6-945b-b1cc92b43de7)

**Comment by hjiangsu** [comment]
I like the new look, it makes it more minimalistic. I wonder if we should still display the number of new comments? e.g., it could be in brackets 112 (4) would indicate 4 new comments

**Comment by CTalvio** [comment]
I changed it so the number is replaced by a +number to indicate the amount of new comments. The total is not shown, but can be viewed when opening the post.

This is in the screenshot in the PR.

I figure if there are additional comments, and you are seeing the post, having the total number visible at a glance is not necessary to show that it is a post with a lot of activity.
