### ISSUE TITLE
More search options

### ISSUE THREAD

**Issue by trymeouteh** [thunder-app/thunder#273]
Please add more search options

### Type
 - [ ] All
 - [x] Comment
 - [x] Post
 - [x] Communities
 - [x] Users
 - [x] URL

### Filter
 - [x] Subscribed
 - [x] Local
 - [x] All

### Sort
 - [x] New
 - [x] Old
 - [x] Top Hour
 - [x] Top Day
 - [x] Top Week
 - [x] Top Month
 - [x] Top Year
 - [x] Top All Time

And add a search bar within each community to fold posts and comments within that specific community.

**Comment by micahmo** [comment]
Just an FYI, I edited the original post to have checkmarks for each item we need to implement. I'm checking them when the related code gets merged into this repo (not necessarily when the feature is release).

**Comment by trymeouteh** [comment]
Your unable to filter a user search to local instance and global. And instead of the filter being called All Posts and Local Posts it should be called All Users and Local Users

**Comment by micahmo** [comment]
> Your unable to filter a user search to local instance and global.

I agree. However, the web UI still shows those options, although they don't seem to have any affect, so I was just following that pattern. Do you think we should hide that filter in Thunder when `Users` is selected?

| ![image](https://github.com/thunder-app/thunder/assets/7417301/9285510a-7fb9-4740-90c6-9b4a5cfa6ee3) |

> instead of the filter being called All Posts and Local Posts it should be called All Users and Local Users

How about just "Subscribed", "Local", "All", like the web?

**Comment by micahmo** [comment]
Hey @trymeouteh (and anyone else that's interested), do you think this issue is fully resolved as of [0.2.7-1](https://github.com/thunder-app/thunder/releases/tag/0.2.7-1)? I guess the only thing we don't technically have is the "All" search type, but every searchable type is available (we just don't have a UI to combine results like that). What do we think?

**Comment by hjiangsu** [comment]
I would consider this to be fully resolved! I'll mark it as such and if there are any further requests, a new issue can be made
