### ISSUE TITLE
Webp previews don't display with full-height images

### ISSUE THREAD

**Issue by Fmstrat** [thunder-app/thunder#276]
**Description**  
Most images posted display just fine, but webp always convert into a link. This only happens in the comfort card when full-height images are used. I'm guessing because the calculation for size isn't working for webp.

**How to Reproduce**  
1. Go to a meme community
2. Be in normal mode, with full height images on
3. Scroll until you hit a webp

**Expected Behavior**  
An image.

**Comment by Poolitzer** [comment]
Potentially related to #247

**Comment by Fmstrat** [comment]
> Potentially related to #247

Replied there but it's not, I covered that in another PR. (Can't close the issue though). Thanks!
