### ISSUE TITLE
Add additonal profile info to user header

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#280]
As we will be using display names by default, some users may have a different handle. Therefore I'd like to display the full handle of a user below their display name, on their profile.

I also co-opted the icons commented out into post and comment counts.

![image](https://github.com/hjiangsu/thunder/assets/4365015/976b040c-55a0-4c1c-b14a-0e7e3459ec03)

I'll roll this into the same PR as for display names, but thought I'd give anyone who wants to a chance to comment.

**Comment by CTalvio** [comment]
Same goes for communities. The display names are not always the same as the handles, and as such:

![image](https://github.com/hjiangsu/thunder/assets/4365015/79d0b993-0598-4098-8f70-cc14d180de5b)

**Comment by Poolitzer** [comment]
Great change!

**Comment by hjiangsu** [comment]
I think those are good changes overall - I would maybe like to see if there are better icons for the post/comment points (unless those are actually the number of posts/comments that you've made) as they might be slightly confusing

**Comment by CTalvio** [comment]
That is the **actual** number of posts and comments I've made. 😅

**Comment by hjiangsu** [comment]
In that case, I think that works!

**Comment by CTalvio** [comment]
I have also changed the online count, which doesn't seem to work anymore, with monthly active.
