### ISSUE TITLE
Community title + info is cut off in Blocked popup message

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#285]
Screenshot attached - for some/all of the communities which use additional descriptive text beyond their community name, it looks like that info is being pulled when you use the block functionality:
![Screenshot_20230708-140548](https://github.com/hjiangsu/thunder/assets/3624023/24c2393d-3222-4c0a-8221-91c3772f8c31)

Currently the popup does not account for text this long, which continues to draw off the screen instead of wrapping. I propose that (since we presumably know what we're blocking already) the popup would only show the community name, and not the community name + description text.

This feeeeeeeeeeels like it might be something I could try and make a PR for, but (as I've stated once or twice) I'm not a coder and I've never done a PR. That said, if someone wanted to point me in the right direction as to where I could look in the code, I could try and implement?

**Comment by machinaeZER0** [comment]
After thinking this over more I realized I'm referencing two different things here - the popup for the community in the screenshot actually probably is (just) the full community title, as opposed to the more truncated name shown on the post itself (for example, Thunder - A Cross Platform Lemmy App vs thunder_app). To revise my proposed change, I think there are several options here:

- have the popup use the same name shown on posts (full title is probably not necessary, since we already know to some degree what we're blocking)
- have the popup text wrap instead of continuing off the screen (probably not ideal as it could make the popup very tall in some situations)
- truncate the popup text with an ellipses [...]
- some combination of the above

**Comment by hjiangsu** [comment]
Oops, this was missed by me 😅

I'm thinking truncating the name with ellipses is the easiest way to go with this!
