### ISSUE TITLE
Login with email breaks profile and subscribed views

### ISSUE THREAD

**Issue by RealStickman** [thunder-app/thunder#290]
**Description**  
Using the email instead of the username results in infinite loading of subscribed communities in the sidebar and does not show the profile view under profile.

**How to Reproduce**  
1. Add a new account
2. Login with email instead of username
3. Sidebar can't load subscribed communities
4. Can't view posts, comments and saved of account

**Expected Behavior**  
Login with email should be allowed, or explicitly rejected by the app.  

**Screenshots**  
Logging in with email (broken)
Sidebar view  
![Screenshot_20230709-151258_Thunder](https://github.com/hjiangsu/thunder/assets/61015582/8afb54f5-86d4-4d5d-9d7c-13c80a0c066e)
Profile view  
![Screenshot_20230709-151305_Thunder](https://github.com/hjiangsu/thunder/assets/61015582/e8b49195-803a-4e53-8d0f-35b4cb15f322)

Login with username to the same account (working)  
Sidebar view
![Screenshot_20230709-151340_Thunder](https://github.com/hjiangsu/thunder/assets/61015582/11abf179-7940-4736-99c2-544674537888)
Profile view  
![Screenshot_20230709-151348_Thunder](https://github.com/hjiangsu/thunder/assets/61015582/29056a60-6ea4-443b-8084-e3e0b85bfda7)

**Device & App Version:**  
 - Device: Xiaomi Mi 9 Lite (LineageOS 20 / Android 13)
 - OS: LineageOS 20 / Android 13
 - Version: 0.2.1+10

**Comment by hjiangsu** [comment]
This should be fixed now, but let me know if you're still encountering this issue!
