### ISSUE TITLE
Post/comment/reply pane: remove/arrange fields to maximize relevant content

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#299]
#295 is making this more of an issue, but even without a mysterious grey block I've found that it's easy to push relevant content offscreen in the post/comment/reply windows/popups once the keyboard is on screen. This is most noticeable when replying to a longer comment, as (minimum) either the send button will be cut off:
![Screenshot_20230709-120206](https://github.com/hjiangsu/thunder/assets/3624023/812b4d03-de68-41de-bea3-eaa1b96c50a3)

or the text box you're typing in (and the options below):
![Screenshot_20230709-120153](https://github.com/hjiangsu/thunder/assets/3624023/0e24e10d-2c33-4ecb-9651-43b1343d6ad9)

=====

Attaching a mockup of a proposed restructuring for this type of pane:
![reply mockup](https://github.com/hjiangsu/thunder/assets/3624023/ce6fdcec-c033-496e-96c1-f25986095068)

Changes include:
- Removal of the large pane title (a title feels unecessary IMO given all the other clarifying text on screen, and it frees up a lot of space)
- Shifting the send button to beneath the text box (this feels like a natural place for this to tap once you're done typing, and also is much easier to reach)
- Removing the Clear button (personal preference as it could still live next to "show preview", but it's fairly trivial to delete your entered text or swipe away to start fresh)
- (Optional) also remove the "replying to ____" dialog? For replies this feels like it would be okay to gain back some screen real estate since you can already see the parent text to know you're replying to the right person, but I could see keeping it in case you wanted to type the person's name in your reply and wanted it there for easy reference

Further, I'm not sure if it's possible to immediately show the keyboard in these situations, but if it is that feels like it would create a more seamless experience (fewer taps to accomplish your goal)

Would love to know what others think, but I think this would be a great change if possible at some point down the line!

**Comment by CTalvio** [comment]
Another cool feature feature, the ability to save drafts.

If you exit without clearing the text field, save its content.

Then if a user cones back to reply to that same comment, load in the same content they already typed in earlier.

**Comment by machinaeZER0** [comment]
It does still feel like in the latest release there could still be improvements on the comment/reply side of things - is there a plan at this point to update those to more closely match the updated Create Post pane? Apologies, I may be behind in following PRs at the moment!

**Comment by micahmo** [comment]
I believe the comment page should match the post page nearly identically now due to #643.

| ![260781147-8302d68f-4973-4afc-b501-809b9113b91c](https://github.com/thunder-app/thunder/assets/7417301/722fed72-3b26-4111-aabc-12c92622143d) |
| - |

Maybe this isn't in a nightly yet?

**Comment by machinaeZER0** [comment]
I think it might not be, it's not on +16 which is what I'm running. If your screenshot is how it looks in dev currently then this should be closed in the upcoming release for sure!
