### ISSUE TITLE
[backlog] OS-specific font scaling

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#301]
Not high priority, but per the discussion and resolution of issue #59 I'm creating this ticket as a backlog item. It seems iOS and Android handle font scaling differently, so currently (to my understanding) the unified code in Thunder is setting font size in a way to achieve a sort of "happy medium" across devices. In practice, this is currently set up in a way where the base font size on Android is slightly smaller than it was in earlier releases, so that iOS fonts aren't displayed as oddly large.

At some point in the future I believe the goal is to implement dedicated, OS-specific font handling "stuff", which would address this small issue :)

**Comment by hjiangsu** [comment]
Finally working on this!

**Comment by machinaeZER0** [comment]
Oh dang! At this point I'm used to it, hahah. A big win for consistency though!

**Comment by micahmo** [comment]
Yeah that was my concern as well. The font size looks great on Android currently, so I was hoping it wouldn't change much. Looks like most of the changes are for iOS.

**Comment by machinaeZER0** [comment]
Yeah, @hjiangsu's initial workaround set the scaling to .95 I believe (to make iOS look more normal), so if that's changing back to whatever 1 is on Android it shouldn't be too jarring a change! I guess the good news is that if it looks off we'll be able to tweak without worrying about affecting both OS views anymore :)
