### ISSUE TITLE
Back swipe sometimes triggers comment swipe animation

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#302]
I'm not able to consistently reproduce this, but I've noticed sometimes when I swipe to leave a post it can trigger the animation for swipe actions on a comment - never enough to actually trigger a vote or other action, but I think if it's possible to avoid it will make the general browsing experience that much smoother. (Also noting this is on Android, if it's relevant)

Proposed fix - since the OS gesture is triggered from swiping the edge of the screen, I already subconsciously swipe posts and comments further from the edge. Would it be possible to add in a small amount of dead zone for triggering app gestures in Thunder? If so, I believe this edge case (pun intended) would be resolved without any unintended consequences :)

**Comment by hjiangsu** [comment]
I'm living for the puns 😄

This is something I was considering as well. However, theres a few caveats with the logic at the moment which prevents this from being easily achievable

Currently, the whole comment itself is a "widget", and is linked together with the gesture action. This means that adding padding to the content of the comment wont work as the gesture is the whole comment itself (notice the orange background - that is still part of the widget and the gesture action)

![image](https://github.com/hjiangsu/thunder/assets/30667958/7b6cf2d3-6113-4d5f-a577-384146e8de8f)

![image](https://github.com/hjiangsu/thunder/assets/30667958/7c56597c-b94e-49b1-a940-ad11eac804c9)

An easy fix for this is to add some margin to the left of the comment (outside of that orange background that you see), but then it would push the comment contents (the stuff to the right of the coloured bar) to the right and would look a bit weird

We could maybe add in another gesture detection which detects if theres a gesture that's occurring at the edges, and potentially use that to cancel the effects of the swipe, but I would have to look to see if this is a possibility

**Comment by machinaeZER0** [comment]
Ahh, got it. That makes sense!

This is probably crazy, but (thinking back to the discussion about keeping the sidebar from triggering when swiping at the bottom of the screen to switch apps) would it be possible to create some sort of "dead zone widget" which would be a thin transparent border around the screen that couldn't be seen, but would prevent app gestures while allowing OS gestures? If that were possible then that could draw over other app elements without them needing to shift around to visually accommodate for it.

Probably not possible - just brainstorming!

**Comment by hjiangsu** [comment]
Hopefully with the introduction of the draft PR, this will be reduced slightly! There seems to also be a setting to adjust the detection point of the swipe to go back, so we can mess around with that until we find a happy medium

**Comment by machinaeZER0** [comment]
Looks like you guys are cookin! Excited to see how things develop :)

**Comment by hjiangsu** [comment]
@machinaeZER0 If you can, try out the latest pre-release and see if this issue is still present! It should be somewhat reduced hopefully, but do let me know!

**Comment by machinaeZER0** [comment]
Oh snap, I think it's fixed! Thank you!!!
