### ISSUE TITLE
[Request] hide community name on posts when viewing community?

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#303]
Right now when you view posts in a community, the posts themselves still show the community handle:
![Screenshot_20230709-140157](https://github.com/hjiangsu/thunder/assets/3624023/a69e7925-dd53-4746-a2b2-138017404b76)

In this example, every post says mst3k, which feels somewhat redundant. While it's not causing any harm, removing this line from this specific view will save vertical space (in compact mode, at least) when a post's title contains a few lines of text already (making it taller than the thumbnail, I mean)

Would be interested to know other people's thoughts, as I may not be thinking of an edge case where this would be helpful. I'm also not sure whether Thunder differentiates between a post in a feed versus in a community, which would be the other blocker (but I feel like it must, since the community posts don't show the instance?)

If this does sound like a good thing to implement, I could try and attempt it? Feels like it might be semi-straightforward, unless we wanted it to be toggleable. Let me know!

**Comment by hjiangsu** [comment]
What I was thinking was to display the user when looking at a particular community

**Comment by tunglith** [comment]
I think the user should always be displayed, maybe we could inspiration from what Jerboa and liftoff for this one, they display OP's name alongside the community icon and name.
