### ISSUE TITLE
Ability to see the destination of any link before visiting

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#309]
**Is your feature request related to a problem? Please describe.**
As it is, the only way to view links in a comment is by blindly tapping them, with no way to first see the destination URL. (Unless it's a plain URL link). When following an external link from the main posts feed, it's possible to use the "Share" feature to preview the URL, but it's a convoluted extra step.

**Describe the solution you'd like**
It would be great if the destination URL could be made visible to the user after tapping a link but before loading the URL. While I can't seem to find a screenshot, the Reddit app RiF had an excellent solution, a pop-up displaying the following:

1. The full destination URL itself.
2. A "Go" button to load the link directly in the in-app browser.
3. A "Share" button to share the link using the native OS sharing system.
4. A "Copy" button to quickly copy the URL to the system clipboard.

**Describe alternatives you've considered**
I'm sure there are other ways to implement such a feature, but I believe the functionality described above covers everything one may want to do with a link, short of viewing it directly.

**Comment by everdred** [comment]
@jordan1776 That's also an interesting approach, but ideally there would be a way to not show previews until the user chooses to interact with a link.  As it is, I have to say I'm not loving the automatic inline display of images within comments.

**Comment by jordan1776** [comment]
Also

**Comment by micahmo** [comment]
Related to #709.

**Comment by ggichure** [comment]
> It would great if we could visit lemmy links inside Thunder itself, link are being opened inside built-in webview browser

This has been done at #832 . 
comments, posts, users.
