### ISSUE TITLE
Add option for full screen swipe-to-go-back

### ISSUE THREAD

**Issue by sageDieu** [thunder-app/thunder#312]
**Is your feature request related to a problem? Please describe.**
I tend to prefer swipe actions for navigation, and in Apollo and other similar apps I'm usually able to turn on an option to swipe anywhere on the page to go back to the previous. 

**Describe the solution you'd like**
For a quick example check out the HackerNews app HACK: https://apps.apple.com/us/app/hack-for-hacker-news-reader/id1464477788

Enable the setting for "full screen swipe to go back" and then go load a post and swipe anywhere on the screen to go back to the list of posts.

**Comment by micahmo** [comment]
Related to #198.

**Comment by jordan1776** [comment]
Personally I would rather have partial screen swipe to go back rather than full screen so you could both have comment gestures and swipe back at the same time. This  type of action is already used for the side menu on the feed view.

**Comment by micahmo** [comment]
> you could both have comment gestures and swipe back at the same time

One idea: Relay uses right-to-left for back and left-to-right for post/comment gestures.

**Comment by thepaperpilot** [comment]
As another relay user, I'd also like to be able to swipe right to go back. Now that the swipe gestures are customizable, I'd love to have something that just entirely disabled swiping right on comments to allow going back instead

**Comment by jordan1776** [comment]
>, I'd love to have something that just entirely disabled swiping right on comments to allow going back instead

Maybe the swipe settings should have up to 4 on the right side for emulating Relay and 2 on the left for Apollo, with the option to set the 2nd, 3rd, and 4th actions to none. And if both left side actions are set to none, use the full screen swipe.

**Comment by Fmstrat** [comment]
This needs to be considered for iOS vs Android. Newer versions of Android have a default swipe back action. iOS will probably steal this in the future, but for now, if this is implemented it may need to be platform specific.

**Comment by hjiangsu** [comment]
For swiping right to go back, iOS already has that natively (I can swipe right from any screen to go to the previous screen) I didn't fully realize that this was not the case for Android (I'm guessing it depends on the OS version or variant)

The one thing I'm wondering about with the full screen swipe is how it interferes with swipe gestures. Would swipe gestures on comments/posts need to be turned off for this to work or is there a way that both of them can work together?

**Comment by micahmo** [comment]
> is there a way that both of them can work together?

Not saying this is the best answer, but one thing we discussed in this thread is having left-to-right go back and right-to-left for gestures. We might want up to four gestures per side in that case though.

**Comment by hjiangsu** [comment]
This has been implemented (without the toggle) in the latest pre-release. Let me know your thoughts!

If there is a left-to-right action, then full page swipe is disabled and you can only go back when swiping from the left. Otherwise, it should be enabled

**Comment by thepaperpilot** [comment]
It's great to see it coming along! I've personally found it really hard to swipe precisely enough to get it to work, though. Could it be more forgiving about the exact angle? For example, give 45 degree leeway either direction.

**Comment by hjiangsu** [comment]
Do you have any left-to-right gestures enabled? If you do, then swiping back will only get triggered from the edge of the screen

You can try these settings and let me know if you're still having trouble!

![image](https://github.com/thunder-app/thunder/assets/30667958/a4915294-4762-404d-a953-6538a9bba534)

**Comment by micahmo** [comment]
If I get a chance alter I'll try to do a screen recording with touches on so you can see what's happening.

**Comment by micahmo** [comment]
@hjiangsu GitHub is having trouble playing the recording from my physical device (probably a format issue), so I DM'd you in Matrix.

**Comment by micahmo** [comment]
This has been added to the latest general release. However, the functionality seems to be a bit hit-or-miss on Android. While this is still being investigated I'll leave this issue open.

**Comment by micahmo** [comment]
Just circling back on this issue... I happened to notice that swiping back on the center FAB is very consistent! This leads me to believe our original conclusion was correct that there is still some conflict of gestures with the comments (`Dismissible`).

**Comment by micahmo** [comment]
Hey @hjiangsu, two questions!

Do you think this is a dup of #198?

Do think it can be closed as a result of #1363? As I commented on #1413, this has been working much more consistently for me now!

**Comment by hjiangsu** [comment]
I think we can close this then, if you're noticing better consistency in the new post page! I haven't had too many issues personally on this, so it's hard for me to comment whether or not this is fixed or not 😅
