### ISSUE TITLE
Clicking Comments from profile gives an error

### ISSUE THREAD

**Issue by jimmyhiggs337** [thunder-app/thunder#327]
**Description**  
When I click on a comment from my profile I get a page that says "oops something went wrong!" And then it goes to the post, but not the context of my comment 

**How to Reproduce**  
1. Go to your user profile
2. Go to comments
3. Click on any comment
4. You will see an "oops something went wrong no error message available" screen
5. The page will shortly refresh, which will bring you to the right post, but not to your comment

**Expected Behavior**  
I will be brought to the correct post and be shown my comment in context

**Screenshots**  
![Screenshot_20230711-111125](https://github.com/hjiangsu/thunder/assets/45857725/8d1a5380-aefe-4eb8-9893-d76187a21f32)

**Device & App Version:**  
 - Device: Asus Zenfone 9 
 - OS: Android 13
 - Version: v0.2.1-alpha.3+11

**Additional Context**

**Comment by hjiangsu** [comment]
This should be fixed with the latest nightly version!
