### ISSUE TITLE
Selecting comment in inbox shows full comment section

### ISSUE THREAD

**Issue by TheSaneWriter** [thunder-app/thunder#329]
**Description**  
When I select a comment in my inbox, it takes me to the full comment section, forcing me to search for the original comment.

**How to Reproduce**  
1. Go to your user inbox
2. Select a comment reply
3. Full comment section of that post opens.

**Expected Behavior**  
When I select a comment in my inbox, typically in other apps it will open a focused view of the post, the selected comment, and the replies to that comment, without the other post comments.

**Device & App Version:**  
 - Device: OnePlus 9 5G
 - OS: Android 13
 - Version: v0.2.1+11

**Comment by CTalvio** [comment]
There's been some discussion on implementing jump to comment and context view. It's still in the phase of figuring out how to do it in a good way.

Definitely something that is planned to be addressed.
