### ISSUE TITLE
Share button for pictures

### ISSUE THREAD

**Issue by Tealk** [thunder-app/thunder#330]
**Is your feature request related to a problem? Please describe.**
If I want to share an image I have to download it first.

**Describe the solution you'd like**
Add a share button next to the download button that opens the os share menu.

**Comment by micahmo** [comment]
This already exists if you tap-and-hold on the post. I think @CTalvio is working on adding the same share functionality within the image viewer in #317.

**Comment by Tealk** [comment]
Oh your right, sorry

**Comment by CTalvio** [comment]
This could still be left open to track the feature. I have it working, but its still waiting to merge and eventually get released.

**Comment by CTalvio** [comment]
Added in #317
