### ISSUE TITLE
Error trying to vote in community you're banned from

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#332]
Soooo, apparently at some point my account was blocked from a community because they thought I was a bot (lol). I was able to get this sorted out, but the other good news is that it helped me catch a bug/missing feature!

I was trying to upvote posts in the community, but when I did, Thunder would show this screen:

![Screenshot_20230710-204530](https://github.com/hjiangsu/thunder/assets/3624023/86086695-4d2b-4459-99db-ffcaee2117b3)

And when I reloaded the app, my vote would not have been counted.

**Expected behavior:**
Perhaps in the event this happens, maybe just a toast popup that lets you know your account has been banned from [community name]?

**Comment by krestenlaust** [comment]
Maybe there's already an issue for changing the full-screen error message into something more digestible. Can't seem to find it though. I believe the solution they decided on was having toast notifications for most issues.

A related feature that could be interesting would be some kind of icon on communities (and posts from that community) which have you blocked.

**Comment by hjiangsu** [comment]
I've made changes so that the feed view should no longer show the full screen messages, but rather a toast notification!

I can't do a test on this particular issue since I don't have any banned accounts, but the toast message would be the same as the message that you see in the image for now. In the future, we can customize the message more for each case. The toast message would read `LemmyApiException: community_ban`

**Comment by micahmo** [comment]
> I can't do a test on this particular issue since I don't have any banned accounts

Could you create a test account and ban yourself from [!thunder_app@lemmy.world](https://lemmy.world/c/thunder_app)?

**Comment by hjiangsu** [comment]
That's true - I'll try that out and see

Also, just linking #248 here since they're both relevant

**Comment by hjiangsu** [comment]
![simulator_screenshot_01B0ADE6-829B-4320-A82C-D90A15D4D700](https://github.com/thunder-app/thunder/assets/30667958/b7a95e39-3b31-4ffa-bdc3-c4e7b4e08dcb)

**Comment by machinaeZER0** [comment]
A toast to toasts!
