### ISSUE TITLE
Logged in, but not?

### ISSUE THREAD

**Issue by pabloscloud** [thunder-app/thunder#336]
**Description**  
I find my profile in the profiles tab and it's also active, but whenever I want to vote or comment I get a message saying I'm not logged in.

**How to Reproduce**  
1. Login with username/password/no totp
2. Vote, comment, check notifications

**Expected Behavior**  
I can vote, comment, see my notifications

**Screenshots**  
![signal-2023-07-12-07-31-36-254-2.png](https://github.com/hjiangsu/thunder/assets/93644977/56e4ddee-1ea7-47e1-bc34-b1374f547ec0)

![signal-2023-07-12-07-31-36-254-3.png](https://github.com/hjiangsu/thunder/assets/93644977/3575aa9b-5b43-4ac6-97e6-3c5601952cdc)

![signal-2023-07-12-07-31-36-254.png](https://github.com/hjiangsu/thunder/assets/93644977/4a38ae6a-c7a5-4cf7-8c8e-9eef676d7370)

![signal-2023-07-12-07-31-36-254-1.png](https://github.com/hjiangsu/thunder/assets/93644977/df4d9cb9-c482-4993-af31-e74a1cdc1bb1)

**Device & App Version:**  
 - Device: Google Pixel 4a 5g
 - OS: 13
 - Version: 20-20230611-NIGHTLY-bramble

**Additional Context**  
Using LineageOS

**Comment by hjiangsu** [comment]
I've noticed that too. It's weird, because your subscriptions load which should not happen if you're not logged in. It's also intermittent. Sometimes it works and other times it doesn't.

I'm not sure exactly what is causing this, but if you have a secondary account elsewhere, could you try logging in that and see if you're encountering this issue? It could be instance related

**Comment by hjiangsu** [comment]
Further confirmation it could be instance related

<img width="1001" alt="image" src="https://github.com/hjiangsu/thunder/assets/30667958/8cde7cc4-a37b-46fd-9aca-0c701339a0e3">

https://lemmy.world/comment/1145286

**Comment by pabloscloud** [comment]
Ok, I'll wait a few days and if this won't get resolved I'll try to check on another instance or app.

**Comment by OldWorldOrdr** [comment]
Same issue, pixel 5

**Comment by jkhsjdhjs** [comment]
I also have this issue with https://iusearchlinux.fyi/

**Comment by pabloscloud** [comment]
> Same issue, pixel 5

Same instance?

**Comment by OldWorldOrdr** [comment]
> > Same issue, pixel 5
> 
> Same instance?

lemmy.world

**Comment by hjiangsu** [comment]
This should hopefully be fixed with the lemmy.world upgrade: https://lemmy.world/post/1375042

For those encountering these issues, please log out and log back in for it to take effect!

**Comment by pabloscloud** [comment]
Seems to work for me now
