### ISSUE TITLE
Incorrectly assuming all links with /c/ are Lemmy links

### ISSUE THREAD

**Issue by ajsosa** [thunder-app/thunder#343]
#### Issue
Clicking on links with paths that start with `/c/rest-of-path` get incorrectly treated as a Lemmy link. 

#### Example
https://catbox.moe/c/rk6abk

So when clicked within app, Thunder tries to open it as if it were a community.

#### Reference
https://lemmy.world/post/1369784

**Comment by hjiangsu** [comment]
I believe I need some stronger regex rules for figuring out lemmy links - linking this since it seems like we can follow lemmy-ui's regex: https://github.com/LemmyNet/lemmy-ui/blob/61255bf01a8d2acdbb77229838002bf8067ada70/src/shared/config.ts#L38

**Comment by micahmo** [comment]
> it seems like we can follow lemmy-ui's regex: https://github.com/LemmyNet/lemmy-ui/blob/021677316d290062a8c3bafdbec668dd8ebb3b85/src/shared/config.ts#L31-L39

Unfortunately that regex is pretty limited in what it matches. It requires the full `community@instance` name.

![image](https://github.com/thunder-app/thunder/assets/7417301/5f067e03-451f-4d7e-83ea-924c484ca9eb)

**Comment by ajsosa** [comment]
Yeah that's probably the simplest solution. Do a ping to check if the community exists and have that decide how to open link.

**Comment by micahmo** [comment]
This fix should be in the latest general release.
