### ISSUE TITLE
[Development] Standardize linting and auto-formatting of project files

### ISSUE THREAD

**Issue by hjiangsu** [thunder-app/thunder#345]
**Is your feature request related to a problem? Please describe.**
This is for development practices and workflow enhancements. It would be best if we are able to standardize the auto-formatting and linting processes for the Thunder. This aims to help with a few things:
- Easier time to look over the actual changes when reviewing PRs as we can focus on the logical changes, rather than changes that occur due to auto-formatting that VSCode provides
- Linting will allow us to keep the codebase a bit cleaner, and helps remove unnecessary imports and changes

**Describe the solution you'd like**
- To standardize linting, we could have a pre-commit hook which runs `dart fix` to automatically apply fixes to any dart files
- Standardizing auto-formatting will need a more robust solution. For those using VSCode, we could create a workspace settings file which would apply to everyone using VSCode. These workspace settings should be agreed upon together.
  - Other solutions may be required for those who are using another IDE to develop in

The main workspace settings that I feel like are applicable are the following rules (these are my own relevant settings):
```json
"dart.lineLength": 200,
"[dart]": {
    "editor.formatOnSave": true,
    "editor.rulers": [ 200 ],
},
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hjiangsu** [comment]
Pulling in @micahmo @ajsosa @bactaholic @CTalvio for suggestions and discussion - Feel free to pull in others which might benefit from this discussion as well

**Comment by micahmo** [comment]
I am definitely in favor of this, and the starting settings you supplied seem to work great (by default, the `lineLength` is far too short, in my opinion). Do any of the other recommended settings here look useful?

https://dartcode.org/docs/recommended-settings/

The only other thing that comes to mind for standardized formatting is `.editorconfig`. The benefit is that a lot of IDEs support it, so we wouldn't be tied to VS Code. However, I'm not sure if Dart supports it.

**Comment by hjiangsu** [comment]
I actually have all of those settings that you linked! But I think for this particular purpose, the settings I mentioned above is the minimum needed and the rest are based on your personal preference

> The only other thing that comes to mind for standardized formatting is .editorconfig. The benefit is that a lot of IDEs support it, so we wouldn't be tied to VS Code. However, I'm not sure if Dart supports it.

I think formatting on save is something that happens on a per IDE basis, so I'm not sure if `.editorconfig` will work in this case (although it might help with setting the indentation spacing)

**Comment by micahmo** [comment]
Would you add `.vscode/settings.json` to source control? If so, wouldn't other changes try to be committed? Or maybe you could force bypass `.gitignore` for the first commit.

**Comment by ajsosa** [comment]
Dart also provides a formatter via `dart format`. Most editors/IDEs have a file watcher type feature where you can have it run a formatter on a file upon saving.

**Comment by hjiangsu** [comment]
> Would you add .vscode/settings.json to source control? If so, wouldn't other changes try to be committed? Or maybe you could force bypass .gitignore for the first commit.

We could still keep `.vscode/settings.json` in source, and any other custom settings could be placed in your user settings rather than the `.vscode/settings.json` file to keep things separated?

**Comment by hjiangsu** [comment]
> Dart also provides a formatter via dart format. Most editors/IDEs have a file watcher type feature where you can have it run a formatter on a file upon saving.

That's actually pretty good to know! I wonder if that is what happens when formatOnSave is `true`. We could potentially use `dart format` as a pre-commit hook then if thats possible. Then it would apply to all IDEs regardless of their settings

**Comment by bactaholic** [comment]
I use Android Studio for flutter, but I have VS Code installed cause it use it for my other software that doesn't have any sort of hot reload feature.

It also just came to my attention a few days ago that VS Code also has a plugin for hot reloading so I'll likely switch anyway, I've just been busy the last few days, and over the weekend my dumbass broke my PC so I was fixing that and don't have everything set up again yet. I'll use this opportunity to switch to VS Code along with everyone else which should make it easier to format.

As far as linting, I've just been using the dart analysis tool that runs automatically in Android Studio, it seems to work pretty well. Not sure what options VS Code has but from the comments above it seems possible.

Overall I think this a great idea, anything to improve the process of reviewing and accepting/rejecting new code sounds like a good idea to me.

**Comment by hjiangsu** [comment]
I have added in the vscode workspace settings, and have added in some formatting/ci into the general workflow which should improve things a little bit. I'll close this since the original issue has been resolved
