### ISSUE TITLE
[Suggestion] Confirmation popup for logging out account

### ISSUE THREAD

**Issue by tj9fu5bu** [thunder-app/thunder#351]
As the title suggests, a popup confirmation for logging out would be nice to prevent it from happening by accident.

**Comment by realeatham** [comment]
It should also mention what account you are logging out of

**Comment by CTalvio** [comment]
> It should also mention what account you are logging out of

As the logout button is on the profile page, you'll see the account you're logging out of both before and while the logout dialogue is displayed.
