### ISSUE TITLE
somewhat confusing settings

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#356]
Some settings are setup so you have to enable a switch to disable a feature. Some examples are

- Disable Post Swipe Actions
- Enable Swipe Gestures
- Enable Double-Tap Gestures

This may be better as 

- "Post Swipe Actions" with the switch button on by default
- "Navbar Swipe Gesture" (its little explaination is fine) and default it to whatever it is by default now
- "Navbar Double-Tap Gesture" (the explaination is fine)

I hope this makes sense as i have changed these settings and am not sure what they default to.

**Comment by micahmo** [comment]
I agree. I think all settings should be in the "positive" form. Flipping a toggle on to disable something is confusing 😆 We can still set the defaults however we want.

Also, with regards to the nav bar gesture, I actually think the explanations could be expanded. It just says "Swipe/tap gestures on bottom nav bar", but I didn't know what the gestures actually did for a while!

How about "Swiping on the bottom bar will open the side menu" and "Double-tapping on the bottom bar will open the side menu"?

**Comment by machinaeZER0** [comment]
Or perhaps some wording for "side bar shortcut" with options like swipe nav bar/double-tap nav bar/disable? If we don't think people would use both at once then that could become a drop-down/popup selection instead of separate toggles

**Comment by shortwavesurfer2009** [comment]
> 

Ah, so the setting would become "Sidebar Shortcut" and be a popup dialog with "disabled" (default), Double-Tap Navigation Bar", and "Swipe Navigation Bar"

**Comment by micahmo** [comment]
I think we should keep the options separate so they can both be selected. However, I like having a new category.

**Comment by hjiangsu** [comment]
I can work on this - I'm adjusting the gestures page to allow enabling/disabling comment gestures

**Comment by hjiangsu** [comment]
Thoughts?

![simulator_screenshot_F97A1FEE-9F42-48EC-B031-04E1695644CB](https://github.com/thunder-app/thunder/assets/30667958/6a845652-a0f4-4bbd-92d3-c3c573c52678)

**Comment by shortwavesurfer2009** [comment]
Take the word "enable" out of "Post Swipe Actions" and "comment Swipe Actions" and this looks fine to me

**Comment by machinaeZER0** [comment]
@hjiangsu can we hyphenate double-tap in the description to match the formatting of the setting itself?

**Comment by hjiangsu** [comment]
Done and done
![simulator_screenshot_905E6ED1-1AFA-4F25-9E03-73E0F854CAE9](https://github.com/thunder-app/thunder/assets/30667958/8a2d6dd1-5152-44f4-8709-4b24b5d20411)

**Comment by shortwavesurfer2009** [comment]
Perfect!
