### ISSUE TITLE
Have Floating Action Buttons follow material guidelines (Back to Top FAB)

### ISSUE THREAD

**Issue by jordan1776** [thunder-app/thunder#359]
**Is your feature request related to a problem? Please describe.**
The way the back to top FAB works does not follow Material guidelines in the following ways: 
1. When going to the comments of a post, the back to top FAB flies across the screen and transforms into the reply button. [The FAB should disappear then the new one appear.](https://m3.material.io/components/floating-action-button/guidelines#4dd3a071-5250-4b4b-97b8-78c7ca9e808f)
2. When scrolled down the comments, there are 2 large FAB buttons. [There should only be 1 large FAB onscreen.](https://m3.material.io/components/floating-action-button/guidelines#1eacb352-bd1c-48e1-8e84-853ceb79ec94)

**Describe the solution you'd like**
1. Blink out the FAB per guideline.
2. Use a small FAB for the back to top action which appears above the reply button [like this](https://m3.material.io/components/floating-action-button/specs#04ef3d0d-557e-4416-81fc-0d8978137970) in comments. In the feed view since there is no other large FAB action, either 
  a. The large back to top FAB should be simply moved to the right side or
  b. Implement #71 Hide read posts, so that the interactions visually look the same between the feed view and comments (large FAB with a small one above)

**Describe alternatives you've considered**
Moving the back to top action to a double tap on nav bar or tap on the top header would make the feature less obvious to new users.

**Additional context**
Having a snackbar appear to return to previous position would be useful for accidental presses.

**Comment by coslu** [comment]
To be honest I'd rather remove the reply FAB in comments altogether since there is a reply button under the post that does exactly that. Can be an easier solution until FAB action customization is added.

**Comment by hjiangsu** [comment]
I think the general consensus is to lean away from using FABs unless needed

Check out #365 which will most likely replace the scroll to top functionality with a secondary press of the home button. As @coslu mentioned, it might also be good to start thinking of custom FAB actions, and enabling/disabling FAB within the settings!

**Comment by micahmo** [comment]
> Check out https://github.com/thunder-app/thunder/pull/365 which will most likely replace the scroll to top functionality

Just keep in mind that this doesn't work in the community view because the nav bar is hidden.

**Comment by jordan1776** [comment]
> Just keep in mind that this doesn't work in the community view because the nav bar is hidden.

And if a feature for hiding the top and nav bar on scroll is added (which I think should be done by default), then you'd have to move the screen around so it would appear. I personally like FABs in general since it makes the major action of a screen obvious.

My suggestions are if hjiangsu is moving away from FABs then interactions should still be quick and easy.

**Comment by machinaeZER0** [comment]
I'd imagine the bars would show back up almost immediately on scrolling up in that situation though, so I personally wouldn't feel inconvenienced having to do that to expose the home button and scroll to top by pressing it. I might just be used to that behavior from previous apps, though!

**Comment by CTalvio** [comment]
#497

**Comment by hjiangsu** [comment]
This issue might not be relevant anymore with the FAB rework that @CTalvio has done. @jordan1776 If you could try out the latest pre-release version and let us know your thoughts, that would be great!

**Comment by hjiangsu** [comment]
I will mark this as completed as the original description is no longer relevant with the changes made to the FAB. If there are any other issues, feel free to open a new issue!
