### ISSUE TITLE
Tapping comment from profile should show comment in limited context

### ISSUE THREAD

**Issue by SquawkWoof** [thunder-app/thunder#361]
**Is your feature request related to a problem? Please describe.**

Currently, tapping a comment from your profile (comment history) loads the entire comment thread for the associated post.  This makes it cumbersome to locate the comment and view replies.

**Describe the solution you'd like**

Tapping a comment from your profile (comment history) should display the comment thread for the associated post in limited context: the comment itself, all replies (children and grandchildren), and the immediate parent comment (if applicable).

**Describe alternatives you've considered**

Automatically scrolling to the comment within the full thread could be a reasonable alternative.

**Additional context**

n/a

**Comment by micahmo** [comment]
Related to #329.

**Comment by KarkanAlzwayed** [comment]
@hjiangsu this also applies to clicking on a reply to my comment in the inbox. Clicking the reply doesn't bring it up, it just loads the whole thread, and I'd have to sift through the whole thread to find it. Didn't want to open a new issue since I think the two issues are similar

**Comment by hjiangsu** [comment]
Hey! A fix for this has already been applied, but has not yet been released as a pre-release version!

**Comment by KarkanAlzwayed** [comment]
> Hey! A fix for this has already been applied, but has not yet been released as a pre-release version!

Is the fix supposed to be in the alpha 1+13? If so, it still not bringing up the comment. It doesn't bring up the thread that comment is in, but not the comment itself. I still have to go find the comment, but it's easier to find now.

**Comment by hjiangsu** [comment]
If I recall correctly, it will load the specific comment thread where your comment resides in, but it does not yet scroll your comment into view!

The fix for the inbox not showing the comment is not in alpha 1+13. It'll most likely come with the next pre-release version alpha 2+13

**Comment by KarkanAlzwayed** [comment]
> If I recall correctly, it will load the specific comment thread where your comment resides in, but it does not yet scroll your comment into view!
> 
> The fix for the inbox not showing the comment is not in alpha 1+13. It'll most likely come with the next pre-release version alpha 2+13

My man, thank you so much for the hard work and the quick replies. Brining the comment itself automatically would be legendary. Let me know if you need any testing done. Again, thank you.
