### ISSUE TITLE
[Android] Android navigation bar obscuring content and buttons

### ISSUE THREAD

**Issue by willbennett-kaltura** [thunder-app/thunder#377]
![Screenshot_20230715-215313.png](https://github.com/thunder-app/thunder/assets/77282969/d98d13b4-4ad0-489e-aef8-3395ca2e3584)

At the bottom, I can't access share or download because of my navigation buttons.

**Comment by hjiangsu** [comment]
Working on a fix - will apply it on the next pre-release!

**Comment by hjiangsu** [comment]
This should be fixed in the latest nightly: https://github.com/thunder-app/thunder/releases/tag/v0.2.1-alpha.6%2B12

**Comment by willbennett-kaltura** [comment]
Looks like that fixed it, but I'm getting the same problem now with the top bar. Example

![Screenshot_20230716-063242.png](https://github.com/thunder-app/thunder/assets/77282969/4174934b-a268-4bc3-9cca-60736a5f0c08)

**Comment by CTalvio** [comment]
#376 Should fix the top bar, as it restores the top bar with a back button that I removed.

I was trying to give the image more screen real-estate, it did not look good in the end.
