### ISSUE TITLE
Add video player

### ISSUE THREAD

**Issue by kovalensky** [thunder-app/thunder#383]
Currently embedded videos are not being shown and indicate error
Please add ability to view videos in the posts

![photo_2023-07-16_22-19-57](https://github.com/thunder-app/thunder/assets/45331093/5762ee92-5da6-4669-b966-5e7b05c88f69)

**Comment by CTalvio** [comment]
This _would_ be **very** cool.

**Comment by CTalvio** [comment]
https://pub.dev/packages/video_player

**Comment by K4LCIFER** [comment]
This feature is sorely needed for Peertube content. Currently, peertube content displayed as a link to the video rather than the video itself. An example of this would be [this Peertube channel federated to Lemmy](https://sh.itjust.works/post/11657970).

**Comment by Nutomic** [comment]
FYI the embed url is automatically put into `post.embed_video_url` for Peertube/Youtube links.

**Comment by micahmo** [comment]
@ggichure I've assigned this issue to you since you were experimenting with video support in #1081. Of course you're not obligated to continue for any reason, so let me know if you'd prefer that I remove the assignment. Thanks!

**Comment by micahmo** [comment]
@ggichure I've assigned marked this issue as in progress since you were experimenting with video support in #1081. Of course you're not obligated to continue for any reason, so let us know if there are any updates or if we should remove the status.

**Comment by ggichure** [comment]
@micahmo Leave the status. I'll have sometime coming week to complete it.

**Comment by hjiangsu** [comment]
Marking this as completed!

**Comment by K4LCIFER** [comment]
Peertube content appears to still not have a video player. For example, the channel that I mentioned in this comment, https://github.com/thunder-app/thunder/issues/383#issuecomment-1869753224, doesn't have a video player.

**Comment by K4LCIFER** [comment]
Ha, my bad! I forgot that I had created that issue.

**Comment by kovalensky** [comment]
> Marking this as completed!

Brilliant, I tried invidious videos with direct play in post, but no luck, probly the same problem with PeerTube functionality

**Comment by micahmo** [comment]
Feel free to provide links to any examples you tried so we can track them for testing!
