### ISSUE TITLE
expand the create post body area

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#393]
**Is your feature request related to a problem? Please describe.**
The post body area only accepts 5 lines of input before needing to scroll. This can make editing a post difficult when needing to select many lines

**Describe the solution you'd like**
Expand the body text area to be larger and have the bold, italic, etc buttons at the bottom

**Describe alternatives you've considered**
Keep the 5 lines by default until more are needed and expand the box line by line until there is no more vertical area left at the bottom of the screen to expand into before scrolling

**Additional context**
This should also be done for the comment editor

**Comment by CTalvio** [comment]
I plan on eventually improving the posting dialogue layout in several ways. The nsfw switch wasn't even something I noticed was in the app at first...
