### ISSUE TITLE
Dynamically connect to best instance on startup

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#394]
As discussed in the matrix chat, it would be good if Thunder connected to the currently fastest-responding instance among the top five or so when not logged in. This would make it more instance agnostic for new users, and also mitigate cases where one or more of the top instances is having some sort of server trouble.

Good candidates for a top five:

- lemmy.world
- lemmy.ml
- lemm.ee
- sh.itjust.works
- lemmy.fmhy.ml

**Comment by micahmo** [comment]
Should we make this initial selection sticky? Once I've launcher Thunder once and started browsing on the given instance, I might not want it hopping around.

**Comment by CTalvio** [comment]
> Should we make this initial selection sticky? Once I've launched Thunder once and started browsing on the given instance, I might not want it hopping around.

Might be a good idea. I'd still want it to switch to another if the one it picked first is down.

**Comment by micahmo** [comment]
Hey @CTalvio, I'm just going through old issues and I'm wondering if this is still something you'd be interested in or you think other people would like?

**Comment by CTalvio** [comment]
We haven't seen any of the big instances run into performance issues since the exodus, so the original reason for something like this isn't as prevalent.

I would perhaps ditch this in favour of a sign-up wizard for new users, which would do something like the join lemmy site, which suggests an instance based on your language and interests. That still suffers from the way it will give you several suggests, then open new sites in new tabs with their own sign-up pages. That almost certainly confuses some users.

On-boarding new users is one of the pain-points of the fediverse, so creating a sign-up process that eases users into things would be cool.

Probably not a priority though.

**Comment by hjiangsu** [comment]
I think we can close this issue for now just to clean up the backlog - if we do encounter issues where a lot of instances are failing to connect, we can reconsider adding this feature back in!

Let me know if you think otherwise, and I'll re-open this issue 😅
