### ISSUE TITLE
Integrate lemmy-search as an alternative search option 

### ISSUE THREAD

**Issue by marsara9** [thunder-app/thunder#403]
The built-in search for Lemmy is rather slow, compute intensive and requires exact matches to find content.

As an alternative I've built lemmy-search (https://www.github.com/marsara9/lemmy-search) / https://www.search-lemmy.com that takes the load off the existing servers, supports complex queries and filters, and is relatively fast.

I've also had a handful of users reaching out if it can be added to the third party apps...

But API documentation can be found on the site itself.

**Comment by hjiangsu** [comment]
Hmm, this sounds interesting! I'm not sure if it'll be planned for the near future, but it's definitely something to keep in mind!
