### ISSUE TITLE
Option to hide floating action buttons

### ISSUE THREAD

**Issue by njshockey** [thunder-app/thunder#405]
**Is your feature request related to a problem? Please describe.**
There's these floating action buttons to go back to the top of a post when viewing comments or back to the top of the feed and another one for replying to a post. I know I'll never use them so being able to hide them would be nice.

**Describe the solution you'd like**
An option in the settings to hide the floating action buttons.

**Describe alternatives you've considered**
Idk any other alternatives. Removing them completely is obviously a bad idea.

**Additional context**
I know how to use dart and flutter so I could probably add this myself if someone pointed me in the right direction.

**Comment by CTalvio** [comment]
Picking this up now.

**Comment by ajsosa** [comment]
The plan is to re-work the FABs. But in the mean time we've added the option to hide them.

https://github.com/thunder-app/thunder/pull/425
