### ISSUE TITLE
disabling material you doesn't work properly 

### ISSUE THREAD

**Issue by realeatham** [thunder-app/thunder#406]
**Description**  

**How to Reproduce**  
1. Settings > theme enable material you
2. not sure if you would need to restart the app or not
3. disable material you

**Expected Behavior**  
The color to go back to purple

**Device & App Version:**  
 - Device: Samsung S21
 - OS: OneUI 5.1 / Android 13
 - Version v0.2.1+12

**Additional Context**

**Comment by hjiangsu** [comment]
I'm not able to reproduce this unfortunately. Is this still an issue with the latest pre-release?

**Comment by realeatham** [comment]
It is still an issue on +13 alpha 1

**Comment by hjiangsu** [comment]
I'm still unable to reproduce this issue - I'll pull in @micahmo and @ajsosa to see if they can hopefully reproduce this as they have access to an Android device!

**Comment by micahmo** [comment]
@realeatham I am not able to reproduce this with the latest alpha build on my Android device. Would you be able to take a screen recording of the issue so we can see the the exact steps in more detail?

**Comment by realeatham** [comment]
When accent color got added
