### ISSUE TITLE
Preview doesn't work

### ISSUE THREAD

**Issue by gon555551** [thunder-app/thunder#428]
**Description**  
The Post Preview doesn't work, it just greys out!

**How to Reproduce**  
1. Start a post.
2. Type some text.
3. Click the preview button on the bottom right.

**Expected Behavior**  
It should show the Markdown preview, but instead shows a grey screen.

**Screenshots**  
![Grey section on the post after clicking the preview](https://i.postimg.cc/HsNZxChR/Screenshot-2023-07-20-13-47-22-680.jpg)

**Device & App Version:**  
 - Device: TCL 20+
 - OS: Android 11
 - Version: v0.2.1+12

**Comment by shortwavesurfer2009** [comment]
Yep, same issue here on my OnePlus Nord N200 running Android 13 with Thunder v0.2.1+12
