### ISSUE TITLE
Latest Alpha Non-Functional

### ISSUE THREAD

**Issue by rjm831** [thunder-app/thunder#432]
Installed latest alpha:  v0.2.1-alpha.1+13 on a Samsung Tab A7 (stock, Android 12) and app simply attempts loading for a brief period before completely freezing.

**Comment by CTalvio** [comment]
Did you try clearing app data? Re-installing?

**Comment by rjm831** [comment]
Feel like a noob -- should have tried either.  Clearing app data & signing in again solved all the issues.  Apologies for the post.

**Comment by hjiangsu** [comment]
I'll close this since it seems like its been resolved!
