### ISSUE TITLE
Accessibility: unlabeled previews with talkback

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#446]
**Description**  
Text and link previews are read as "unlabeled"

**How to Reproduce**  
1. Go to System settings > Accessibility > Talkback and turn it on
2. Open Thunder
4. Tap a link preview or image preview
5. See error

**Expected Behavior**  
I suggest these elements be skipped entirely by talkback as they just add extra elements to navigate through. Either that or label them like "open article link" or "open image".

**Screenshots**  
![Screenshot_20230722-080759_Thunder_1](https://github.com/thunder-app/thunder/assets/116814522/d409bfdf-52dd-46b7-ab4b-a4c9a1f86553)

**Device & App Version:**  
 - Device: [e.g. iPhone6] OnePlus Nord N200
 - OS: [e.g. iOS8.1] Android 13
 - Version [e.g. 22] v0.2.1-alpha.1+13

**Additional Context**

**Comment by hjiangsu** [comment]
For the next nightly version, I'll see if I can just completely remove the previews from talkback/voiceover. I'm not entirely sure if it'll work so please let me know!

**Comment by shortwavesurfer2009** [comment]
That is fine. Removing them is fine in the long-term too as the less elements to navigate through the better. That is why i am glad the comment actions buttons are off by default since it would seriously increase the elements per page. It really is a balance between not having too many elements while still keeping the ones that are absolutely needed
