### ISSUE TITLE
Ability to export/import settings

### ISSUE THREAD

**Issue by SquawkWoof** [thunder-app/thunder#456]
**Is your feature request related to a problem? Please describe.**

Lightning requires uninstall/reinstall when upgrading to new version.  This causes loss of settings.

**Describe the solution you'd like**

Ability to export/import settings, including user accounts.  Any new setting options available in the newer version, but not in the  version that exported the settings, can be skipped for that particular import operation.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by shortwavesurfer2009** [comment]
I dont think user account import would work since you need to authorize it and wouldnt want your password in a backup. Otherwise i agree with this.

**Comment by SquawkWoof** [comment]
@shortwavesurfer2009 I have no problem storing my password in a local file.  It could an optional feature with user consent, or the file could be encrypted with a user-supplied key.

**Comment by micahmo** [comment]
We could use [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage), which utilizes each platform's native, encrypted storage.

**Comment by hjiangsu** [comment]
Currently, importing and exporting does not contain user account information. I think this can be split off into a new issue if needed! I'll close this one since the latest version introduced this feature
