### ISSUE TITLE
Proposed updates for Accent Color settings

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#457]
With Accent Color as it's currently implemented, it's not possible to see how the color will look without exiting the Theming page. I have some thoughts on how this could be updated:

- right now accent color is selected from a list of swatches, and picking a swatch immediately closes the picker. I suggest changing it from a tap-to-change list to a list with radial buttons and a Save button at the bottom. With this change you would be able to "window shop" colors as much as you'd like, with the radial buttons (and Save button) updating in real time to give you a sense of what the color will look like elsewhere in the app. Backing out of this menu would discard your changes, and hitting Save would (nach) save your selected color
- additional thought: instead of showing your selected color in the Theming page by its name (Red, Blue, etc), I think it would be great to instead show your selected swatch in this space. Again, since currently nothing on this particular page is themed, this gives people another indicator of what their chosen accent color actually looks like

**Comment by machinaeZER0** [comment]
Adding some mockups as to what I was envisioning!

![accent color thunder](https://github.com/thunder-app/thunder/assets/3624023/8625efa5-bdce-4e5b-b781-a78accaa5976)


![accent color 2 thunder](https://github.com/thunder-app/thunder/assets/3624023/ba366a8b-d929-40f9-9d13-b022b9bb6218)

![accent color 3 thunder](https://github.com/thunder-app/thunder/assets/3624023/ca316538-208f-4d01-a2b5-e2f4ef44d44d)

**Comment by CTalvio** [comment]
![image](https://github.com/thunder-app/thunder/assets/4365015/8c7db314-ca30-45ed-9b03-7d346f3fd1f9)

How about using the same style of swatches, as the "material you" selection screen? It displays the primary, secondary and tertiary colors is icons for you to quickly see the colors that come with each option.

**Comment by machinaeZER0** [comment]
That would be really cool!
