### ISSUE TITLE
Downloaded images are saved in wrong location

### ISSUE THREAD

**Issue by bikasv** [thunder-app/thunder#467]
**Description**  
The images are saved in incorrect folder

**How to Reproduce**  
1. Go to any post with image
2. Click on the image to enlarge
3. Click on the download button to download the image
4. See the location where image is saved, which is **sdcard > Pictures > Pictures > Thunder**

**Expected Behavior**  
The image should be saved in **sdcard > Pictures > Thunder** folder

**Device & App Version:**  
 - Device: Samsung S21 Ultra
 - OS: Android 13 (One UI 5.1)
 - Version v0.2.1-alpha.4+13

**Comment by hjiangsu** [comment]
Found the issue, it should hopefully be resolved in the next nightly!
