### ISSUE TITLE
Open link in external browser, opens original URL not current URL

### ISSUE THREAD

**Issue by krestenlaust** [thunder-app/thunder#472]
**Description**  
When using the integrated browser, after navigating a webpage, pressing the open-in-external opens the original URL, not the one that's browsed to currently as expected.

**How to Reproduce**  
1. Open URL
2. Navigate to different URL within browser
3. Press open-in-external browser button

**Expected Behavior**
Open currently navigated URL

**Device & App Version:**  
N/A (assuming it isn't a device-specific bug)
App version: v0.2.1-alpha.1+11

**Comment by hjiangsu** [comment]
It seems like you're still using an older version of Thunder - could you test out the latest nightly and check if this is still an issue? Thanks!

**Comment by micahmo** [comment]
@krestenlaust Based on your comment on another thread, you might not actually have the latest version? If you do, maybe you can send a screen recording of the issue. I haven't seen this issue with Custom Tabs.

**Comment by krestenlaust** [comment]
https://github.com/thunder-app/thunder/assets/17174333/833f3a51-701b-48a7-9e0b-f1091c7bb419

Video description:
1. Open link
2. Navigate to front page of news site
3. Open in external browser
4. I'm back to the article in the external browser.

**Comment by micahmo** [comment]
Hi @krestenlaust, thanks for posting that! That confirms you are using an old version of Thunder with the embedded browser. The latest version uses Custom Tabs, which will integrate your default browser's interface directly into the app. It should handle things like Open in Browser (and other functionality) better than our home-grown one. Thanks!

**Comment by hjiangsu** [comment]
Closing this issue as it seems to be fixed
