### ISSUE TITLE
Provide better hints for how to edit own comments

### ISSUE THREAD

**Issue by fqux1** [thunder-app/thunder#477]
#158 says 

> Closing as this should be fixed in v0.2.1+10!

However on v0.2.1+13 there still doesn't seem to be any way

**Comment by micahmo** [comment]
If you have the "Reply" gesture configured, it should turn into "Edit" when it's one of your own comments. This might not be the most intuitive, but it should be there.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/a1bd3924-6f29-4768-a414-ac7bdc152947) |
| - |

https://github.com/thunder-app/thunder/assets/7417301/2efce32b-6cae-473a-a666-ca7292afd015

**Comment by hjiangsu** [comment]
Maybe a change in the wording from "Reply" to "Reply/Edit" may make sense here

**Comment by micahmo** [comment]
> Maybe a change in the wording from "Reply" to "Reply/Edit" may make sense here

Good idea. I added this to #473.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/c46969d3-3ba9-472b-8a7a-13bd0be282ef) |
| - |

**Comment by CTalvio** [comment]
Could someone edit the title on this to reflect the change in this tracking better hints for how to access editing

**Comment by hjiangsu** [comment]
> Could someone edit the title on this to reflect the change in this tracking better hints for how to access editing

Done!
