### ISSUE TITLE
Missing posts compared to other clients, web

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#489]
**Description**  
I just discovered a new community, folkhorror@feddit.uk, and had a look at it. I understand that my instance may be missing posts compared to the community's "home" instance, and that's not a Thunder issue... but when viewed in Thunder my instance's version of the community is missing a post compared to both 1) my home instance's web interface _and_ 2) the Android client Jerboa. (Web and Jerboa show three posts, while Thunder only shows two.)

**Expected Behavior**  
Thunder should show the same posts as my instance's web UI.

**Screenshots**  
[Thunder](https://github.com/thunder-app/thunder/assets/5367819/c51d3b23-2273-4ef6-a242-a00c93d80512)
[Jerboa](https://github.com/thunder-app/thunder/assets/5367819/0cbcfd04-f563-4788-87b8-a4573d81a373)
[web on my instance](https://github.com/thunder-app/thunder/assets/5367819/65955044-9c30-42a3-bb20-eee3848c866b)
[web on the home instance, probably not relevant](https://github.com/thunder-app/thunder/assets/5367819/1d44ff5c-ef5a-442e-8468-b4ab3b274006)

**Device & App Version:**  
 - OS: Android 11
 - Version v0.2.1+13

**Comment by everdred** [comment]
Here is another example. Jerboa is displaying both posts that currently exist on web, while Thunder is missing one.

[in Thunder](https://github.com/thunder-app/thunder/assets/5367819/6a82ae09-ebf7-486b-af05-80cac9ee5b97)
[in Jerboa](https://github.com/thunder-app/thunder/assets/5367819/a44f5cec-ffaa-4594-aee7-7858d2dde383)

**Comment by hjiangsu** [comment]
It seems like this is indeed the issue that @ajsosa found and fixed!

**Comment by hjiangsu** [comment]
@everdred If you have the ability to get the nightly version, could you double check and confirm that this issue is fixed? (v0.2.1-alpha.1+14)

**Comment by everdred** [comment]
@hjiangsu I just upgraded and checked a handful of new communities, plus the example communities from the original report. The post lists all appear identical to my other client and to web, so I'd say it's fixed! 

(Aside: just noticed the inbox badge... very nice!)
