### ISSUE TITLE
Incognito mode

### ISSUE THREAD

**Issue by thisisartman** [thunder-app/thunder#491]
**Is your feature request related to a problem? Please describe.**
There's no way to browse privately. Sometimes, it's easier to not have the ability to upvote or comment, but having to log out for this every time is cumbersome.

**Describe the solution you'd like**
An additional option in the accounts list for anonymous/incognito mode.

**Describe alternatives you've considered**
The closest alternative to this is to log out of all accounts and then scroll. Obviously, this requires extra steps that a button would solve.

**Additional context**
![Screenshot_20230727-061202.png](https://github.com/thunder-app/thunder/assets/85949613/5b901c72-348f-4cad-a772-1a476353012c)

**Comment by micahmo** [comment]
Related to #269.
