### ISSUE TITLE
Make comment show up on the top of the thread

### ISSUE THREAD

**Issue by KarkanAlzwayed** [thunder-app/thunder#498]
Commenting on a post throws my comment to the very bottom of the post. Getting to it gets really cumbersome when the thread is long, in case I want to proofread or edit it. When I comment, it should be at the very top in my opinion.

**Comment by ajsosa** [comment]
So we currently don't have the code in place for inserting a comment into place. What is actually happening is after the new comment is created, the page is refreshed according to the comment sort setting you have selected. This also why you end up back at the top of the post.

I'm working on building out the comment insertion functionality. I don't think showing your comment at the top of the thread is the right way to go about this. The way I'm hoping to get this to work is to keep your place in the comment section so you can immediately see your comment in the correct context when replying. For top level comments I want to insert it into the correct place based on your selected sort setting and auto-scroll to it. That's my hope anyway.

**Comment by ajsosa** [comment]
Actually, after speaking with the team, we'll place top level comments at the top.
