### ISSUE TITLE
Add font scale options for more elements

### ISSUE THREAD

**Issue by sandpaperback** [thunder-app/thunder#510]
There are currently font scale options only for Title and Content. Allowing additional elements to be controlled independently will help provide users with finer control over their experience and also improve accessibility.

The biggest piece would be for metadata/interface to scale separately from content. Right now, if a user wants to minimize the space taken up in their timeline by user, community, etc, that scale setting also impacts the font scale for all comments and post detail. It can result in a less than comfortable experience.

Attached are some images to illustrate the idea.

![Screenshot_20230731_081605](https://github.com/thunder-app/thunder/assets/104503487/4c83f46d-e201-494a-8243-26d721534f01)
![Screenshot_20230731_082555](https://github.com/thunder-app/thunder/assets/104503487/d4a884bd-1e22-4ab8-b930-47518e63c421)
![Screenshot_20230731_081701](https://github.com/thunder-app/thunder/assets/104503487/5a65cac9-ff56-439a-ae6b-b70f33e8ee7c)
![Screenshot_20230731_081707](https://github.com/thunder-app/thunder/assets/104503487/1ae8f7e9-239c-4abd-b84c-8200f0ba9bb6)

**Comment by hjiangsu** [comment]
Thanks for creating the issue and the screenshots! That is really useful for us to be able to tackle this on.

I agree that we should have some more granularity in selecting the font sizes for different aspects of the UI. The reasoning for why there are only two options at the moment is to allow a bit more accessibility for those who require larger font sizes in order to use the app. Now that we have that foundation in place, we can start adding in more granularity to all the elements you've mentioned!

**Comment by hjiangsu** [comment]
One thought here: should "content font scale" and "detail content font scale" be the same thing?

I think these should be the options:
- **Title font scale**: handles the title of the post from the feed, and when you are viewing the post itself (same as what you have)
- Rename **Content font scale** -> **Post font scale** or **Post detail font scale**: this would handle the text preview in the feed, as well as the body of the post (this combines content font scale and detail content font scale from your image)
- **Comment font scale**: handles the text within comments (same as what you've described)
- **Metadata font scale**: handles any metadata text (same as what you've described)

@sandpaperback Let me know what you think!

**Comment by hjiangsu** [comment]
Added the options I mentioned in my previous comment, this should be available in the upcoming pre-release

**Comment by sandpaperback** [comment]
Sorry, started several replies and never followed through. Looks good and I'm looking forward to the next release!

**Comment by hjiangsu** [comment]
Awesome, thanks for checking it out!
