### ISSUE TITLE
Add domain to posts linking to external websites

### ISSUE THREAD

**Issue by mattrobineau** [thunder-app/thunder#511]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to know where a post will send you when looking at the card on the feed. You have to open the comments for the post to see the start of the URL which requires an extra click.

**Describe the solution you'd like**
I suggest adding the domain name under the post title for external links like the web interface does:
![image](https://github.com/thunder-app/thunder/assets/427379/8af16f62-5d33-41d4-a583-a3cc9ac71aa2)

**Comment by micahmo** [comment]
This was being worked on by @CTalvio. Not sure what the current status is. Here's a sneak preview from that time.

![image](https://github.com/thunder-app/thunder/assets/7417301/a4bfba29-8f49-4675-8065-ad31bb1fa800)

**Comment by CTalvio** [comment]
I have a draft up #468.

I've started on this but it was a side experiment during my work for the FAB rework.

Taking a break from that so there will likely be progress on this.

**Comment by mattrobineau** [comment]
Ah, and I even looked at that PR comments before opening this issue. (I missed the change that added the link)

Should this issue stay open until #468 is completed?

**Comment by CTalvio** [comment]
Yes
