### ISSUE TITLE
Keyword filter

### ISSUE THREAD

**Issue by Benjamin-R-Balzer** [thunder-app/thunder#513]
Please, correct me if I'm missing out somehow, but I've searched high & low for a simple keyword filter section in Settings, etc., and I'm comin' up empty.

All due respect, but I feel that this is a standard component of all aggregate reader apps (eg. Sync, Boost, RIF, etc.), and I'm genuinely surprised to see it missing in Thunder. I'm unaware of how simple it may be to implement, so please take this as a polite request, not a judgement. 

The app itself is fantastic, otherwise, and I'm pretty impressed at the feature additions with each update. Keep up the great work!

**Comment by hjiangsu** [comment]
I also agree that this should be a feature, but we just have not gotten around to it!

Could you maybe provide some more details in how you would like to see this be implemented? Would this be for posts, comments, or something else entirely? I think showing screenshots of other apps and how they do it, or providing some context into how you would like to access/edit these keywords would be really beneficial

**Comment by Benjamin-R-Balzer** [comment]
Certainly, and thanks for the feedback! In similar readers (Sync, Boost,
Connect, Jerboa, et al.), the Filter integration is a Setting and functions
at the feed level. I'm not sure if it also affects comments, though that
seems doubtful. Personally, I'd like to be able to filter out, at the very
least, things like: death, murder, rape, torture, and others, as well as
assclown news like Trump, DeSantis, QAnon, Westboro, etc. To put it simply:
if I want to hear about them, I'll actively look it up. Other than that,
life's too short. :)

**Comment by hjiangsu** [comment]
Thanks for the reply! Another question: for other apps, does this filter only apply to the title of the post? or does it also apply to the body/text of the post?

It also sounds like to me that there's a way to bypass the filtered keywords as well. Would this be a setting to toggle on/off filters, or is there another way to trigger this bypass?

**Comment by Benjamin-R-Balzer** [comment]
I don't have other readers installed currently, so I can't screenshot, but:
the Settings field is generally just a line for text, with the keywords
separated by a comma. No bypass, etc. Also, I believe it screens the
entirety of the initial post (title, body, image alt text, etc) just not
the comments, if any.

**Comment by zchilds** [comment]
Hey there, chiming in to how Memmy currently handles filters. At the moment there are two options.

1. Filtering posts based on words in the title of the post
2. Filtering out posts based on the instance they were posted from

Works really well and I'd love to see something like that implemented in Thunder. Thanks!

**Comment by hjiangsu** [comment]
> Lemmy natively does provide the option to block communities, but it does not currently allow people to filter posts based on title. I actually submitted an issue on the Lemmy side as well.

Yeah, we have functionality to block communities and users since that's offered by lemmy natively. It would be great if they could also add in filtering for keywords on posts/instances since that would just make everything more efficient in terms of reducing fetching unnecessary data

**Comment by Benjamin-R-Balzer** [comment]
Agreed, and blocking instances is only going to become more essential as
the platform gains traction. Incorporating a Report option to blocking such
(and users) would be efficient, too.

Personally, I prefer passively filtering posts, but actively blocking
instances/users. The difference is in the action of pruning one's feed vs.
declaring a source unfit/unnecessary.

**Comment by donnielrt** [comment]
Just as an FYI, seems like instance blocking will land in lemmy soon: https://github.com/LemmyNet/lemmy/pull/3869

**Comment by hjiangsu** [comment]
This is now in PR stage, let me know what you think about the implementation! (video is attached in the PR: #974)

**Comment by hjiangsu** [comment]
Keyword filters were added in a previous version and is generally available! I'll close this issue as completed. If there are any other requests, feel free to create a new issue!
