### ISSUE TITLE
Show community icons in the feed

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#516]
**Is your feature request related to a problem? Please describe.**
Currently the "Show Community Icons" option only shows them in search and the subscribed communities list. I would like to also be able to see the icons in the feed as well.

**Describe the solution you'd like**
An option to show community icons in the feed.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by hjiangsu** [comment]
This seems to be a bug - the option should allow you to see icons in the feed
