### ISSUE TITLE
Accessibility Regressions

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#517]
**Description**  
The following are not read or no longer read with talkback

**How to Reproduce**  
1. Go to System Settings > Accessibility > Talkback and turn it on
2. Open Thunder
3. Tap the items indicated

**Expected Behavior**  
should br read by talkback

**Screenshots**  
- [x] ![Screenshot_20230801-164726_Thunder_1_1](https://github.com/thunder-app/thunder/assets/116814522/c8c07dc3-876b-4c6a-b98b-b05023271d63)
- [x] ![Screenshot_20230801-170535_Thunder](https://github.com/thunder-app/thunder/assets/116814522/152aace4-f56a-47a5-b1e2-015a4875ab52)
- [x] ![Screenshot_20230801-170603_Thunder_1](https://github.com/thunder-app/thunder/assets/116814522/da63bfe5-8b46-45bd-a4a9-8ff918bad293)
- [x] ![Screenshot_20230801-172228_Thunder](https://github.com/thunder-app/thunder/assets/116814522/b8f734aa-d45c-45e2-9a13-d0b387f41b95)

**Device & App Version:**  
 - Device: [e.g. iPhone6] Oneplus Nord N200
 - OS: [e.g. iOS8.1] Android 13
 - Version [e.g. 22] 0.2.1-alpha.1+14

**Additional Context**

**Comment by hjiangsu** [comment]
I'll go ahead and close this!
