### ISSUE TITLE
Add a "Favorites" category in sidebar

### ISSUE THREAD

**Issue by Ginjutsu** [thunder-app/thunder#526]
**Is your feature request related to a problem? Please describe.**
One of the things that frustrates me with the current design is how when I want to go to a specific community, I have to scroll through a list of every community I'm subscribed to in order to find it. I'm personally subscribed to a _lot_ of communities, so this can be kind of an annoying process.

**Describe the solution you'd like**
Allow users to "favorite" communities that we frequent more often, which would move communities in the "Subscriptions" drop-down category to an additional "Favorites" category located above.

**Describe alternatives you've considered**
The search function can be a quicker way to find communities currently, but there are many situations where I'd rather just use the sidebar.

**Comment by Coehill** [comment]
This is the #1 feature I've been missing from when I used RedReader for Reddit. Except, RedReader calls it "pinned".

To take it one step further, there could be a feed option for only your "favourited" Lemmy communities!

**Comment by orangeNgreen** [comment]
Just wanted to add my support for this feature. Seems most of the communities I like to visit are located toward the bottom of my very long Subscriptions list (such as Thunder and Thunder Nightlies).

**Comment by hjiangsu** [comment]
This is now in WIP! The main functionality is complete, but its still a bit rough so more testing is needed before this is introduced in a nightly build

**Comment by hjiangsu** [comment]
Update: added a video to demonstrate the feature. Let me know what you think of it and if there are any changes that should be made before it's merged in. The video is attached to the PR: #971

**Comment by orangeNgreen** [comment]
For some reason I’m unable to view the video. Nothing happens when I click play.

**Comment by hjiangsu** [comment]
Interesting - are you on mobile? or on desktop? Sometimes, I have issues playing the video on mobile.

**Comment by orangeNgreen** [comment]
Ah. I was on mobile. Worked on desktop, and I love it! Thanks!

**Comment by Coehill** [comment]
Looks awesome! Thanks for implementing this feature.

**Comment by orangeNgreen** [comment]
I ask this only out of excitement: any thoughts when the feature will hit a Nightly?

**Comment by hjiangsu** [comment]
I'll try to get a nightly out within the next couple of days, just doing some final internal testing on things first!

**Comment by hjiangsu** [comment]
A new nightly build has been released which contains this feature: https://github.com/thunder-app/thunder/releases/tag/0.2.7-5

Let me know if you encounter any bugs or issues with it!
