### ISSUE TITLE
App cache grows large very quickly

### ISSUE THREAD

**Issue by jakebeinart** [thunder-app/thunder#529]
**Description**  
I regularly clear my cache after a few days using the app since it gains 500-600mb between every check of it. Not sure exactly how long the intervals were between me checking, but short enough for me to notice that it grows quite quickly. These are days of fairly heavy usage.

**How to Reproduce**  
1. Use the app normally and continuously for a few days to a week
2. Check the cache size

**Expected Behavior**  
I would expect cache sizes more in the range of 100-300mb after long periods of usage. Ex: Facebook, Instagram, other social media apps caches are not larger than 250mb and I've never consciously cleared them.

**Device & App Version:**  
 - Device: Galaxy S23 Ultra
 - OS: OneUI 5.1/Android 13
 - Version v0.2.1+13 is the last one I noticed on, but my cache was cleared when I updated to the latest nightly release

**Comment by micahmo** [comment]
It's hard to tell whether `ExtendedImage` and/or `LinkPreviewGenerator` just use memory cache or actual storage cache (which actually consumes disk space, despite being called cache). I was hoping the former, but it sounds like maybe some of the latter too. Either way, I believe both of these have a cache timeout that we could experiment with.

**Comment by hjiangsu** [comment]
Linking PR to this issue: https://github.com/thunder-app/thunder/pull/1062

Hopefully this solution helps with keeping the cache size down. We'll have to monitor this in the longer term to see if its effective (and potentially adjust the frequency for removing cached data)

**Comment by hjiangsu** [comment]
I'll mark this as completed since this has been added in. However, feel free to make a new issue if you have any feedback with the implementation!
