### ISSUE TITLE
Further posts don't load if the initial set fits on screen

### ISSUE THREAD

**Issue by chenxiaolong** [thunder-app/thunder#534]
**Description**

When opening Thunder, if the initial list of posts fits on screen, further posts don't load. It almost seems like further loading is triggered by scrolling, but on larger screens, there's nothing to scroll.

**How to Reproduce**

1. On a larger device (eg. tablet), open Thunder
2. Set to the compact list view in the settings
3. Navigate back to the posts

**Expected Behavior**

The first 10 posts show up. The loading spinner shows up after the 10th post, but never loads anything. It's not possible to scroll down because everything already fits on screen. Also, it does not respond to the swipe-to-refresh gesture while in this state.

**Screenshots**

* [Portrait with 1-column layout](https://github.com/thunder-app/thunder/assets/646253/834f5327-ec5b-49c5-b999-de5f20e34067)
* [Landscape with 2-column layout](https://github.com/thunder-app/thunder/assets/646253/c286fe5a-e7ae-44d8-bceb-70d6ca317f94)

**Device & App Version:**

- Device: Samsung Galaxy Tab S8 Ultra
- OS: Android 13
- Version: `v0.2.1-alpha.1+14`

**Comment by hjiangsu** [comment]
This should hopefully be fixed in the upcoming pre-release version!

**Comment by chenxiaolong** [comment]
Thanks for the quick fix!

**Comment by chenxiaolong** [comment]
Confirmed working in `v0.2.1-alpha.2+14`. Thanks again!

**Comment by hjiangsu** [comment]
Awesome, thanks for confirming
