### ISSUE TITLE
Allow the user to see votes on their own comments in the profile comment history

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#537]
**Is your feature request related to a problem? Please describe.**
When looking at the profile comment history, you currently only are able to see the comment itself, and not the vote count.

**Describe the solution you'd like**
I think it would be a good idea to also show the vote count for comments in your comment history.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by hjiangsu** [comment]
This should be added in the latest nightly - [v0.2.1-alpha.1+14](https://github.com/thunder-app/thunder/releases/tag/v0.2.1-alpha.1%2B14)

![image](https://github.com/thunder-app/thunder/assets/30667958/f7c18052-4c68-4133-b21b-8e7e427d1667)

Let me know if you are describing a different issue!
