### ISSUE TITLE
Highlight featured / pinned / sticky posts

### ISSUE THREAD

**Issue by krestenlaust** [thunder-app/thunder#541]
**Is your feature request related to a problem?**
I can't tell if a post is sticky (not sure about comments)

**Describe the solution you'd like**
Some kind of icon next to the post, or maybe a slightly tinted outline to either green or orange (whatever the official UI uses). Maybe even both.

**Describe alternatives you've considered**
🤷 

**Additional context**
The top post is sticky.
![Screenshot of sticky post taken from feed](https://github.com/thunder-app/thunder/assets/17174333/37f65e4a-05b9-401f-a92c-ca3b0001ad4e)

**Comment by micahmo** [comment]
Hi @krestenlaust,

I see a sticky indicator on my end.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/a8cf3767-9c62-4d5e-84ac-e5fb5f9377eb) |
| - |

What build are you using?

**Comment by CTalvio** [comment]
Thunder has had this feature for a long while. Pinned posts appear at the top with a green megaphone. In some cases pinned posts fail to appear at the top, due to federation issues, but this is not a bug Thunder can solve. It's a problem with how Lemmy federates posts.

![image](https://github.com/thunder-app/thunder/assets/4365015/029c0458-776f-497f-903d-7f9a036656f6)

**Comment by micahmo** [comment]
I thought maybe there was an issue with the Subscriptions page, since that's what @krestenlaust, but I see the sticky indicators there too.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/3574279f-85f8-49bf-a022-148708b00942) |
| - |

**Comment by CTalvio** [comment]
We need more details. Feel free to provide anything that seems relevant @krestenlaust, if this turns out to be a bug, I will reopen, rename and relabel.

**Comment by krestenlaust** [comment]
I'm using this build
![Screenshot_20230803-140039.jpg](https://github.com/thunder-app/thunder/assets/17174333/86a904f8-8e8b-43eb-bb31-b60b7dc13944)
