### ISSUE TITLE
Comments do not show up if sorted by Old

### ISSUE THREAD

**Issue by Lichtgestalt060** [thunder-app/thunder#550]
**Description**  

**How to Reproduce**  
1. In the settings / General / Posts, Default comment sort type= 'Old'
2. Open a post that already has some comments
3. ->Post is shown
4. ->Comments are NOT shown, but an exception and an endless circling cursor

**Expected Behavior**  
Comments should be displayed

**Screenshots**  
 yes but I don't know how to post it here

**Device & App Version:**  
 - Device: xiaomi 11
 - OS: android
 - Version 13

**Additional Context**  
If the setting is 'New', then it works OK

**Comment by hjiangsu** [comment]
This seems to have been fixed in an upcoming pre-release build
