### ISSUE TITLE
Accessibility, downvote counts in comments are wrong with talkback

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#555]
**Description**  
When using talkback to read comments with both upvotes and downvotes the downvote number is not correct

**How to Reproduce**  
1. Go to System Settings > Accessibility > Talkback and turn it on
2. Open thunder
3. Find a comment with both upvotes and downvotes and tap it.

**Expected Behavior**  
Talkback should read downvote counts correctly

**Screenshots**  
![Screenshot_20230804-155936_Thunder](https://github.com/thunder-app/thunder/assets/116814522/9295929b-efe2-4150-8224-5e42cf9e4813)

**Device & App Version:**  
 - Device: [e.g. iPhone6] OnePlus Nord N200
 - OS: [e.g. iOS8.1] Android 14
 - Version [e.g. 22] v0.2.1-alpha.1+14

**Additional Context**  
In the screenshot above talkback reads
"17 upvotes 17 downvotes 16h"

**Comment by shortwavesurfer2009** [comment]
I just noticed it still does this when viewing my comments from the profile page. Should i open another issue for that?

**Comment by hjiangsu** [comment]
I can fix that quickly

**Comment by hjiangsu** [comment]
And done - will come with the next pre-release version!
