### ISSUE TITLE
monochrome theming

### ISSUE THREAD

**Issue by RustoMCSpit** [thunder-app/thunder#558]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by micahmo** [comment]
Hi @RustoMCSpit, I believe adaptive icons for Android were implemented in #73.

It seems to work fine for me.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/44661d55-b411-4edc-a155-1fa43701bfe7) |
| - |

Are we missing something?

**Comment by RustoMCSpit** [comment]
> Hi @RustoMCSpit, I believe adaptive icons for Android were implemented in #73.
> 
> It seems to work fine for me.
> 
> ![image](https://user-images.githubusercontent.com/7417301/258617503-44661d55-b411-4edc-a155-1fa43701bfe7.png)
> Are we missing something?

doent work for me uhhh, not sure if you are missing something ngl

**Comment by micahmo** [comment]
> doent work for me uhhh, not sure if you are missing something ngl

What version are you running? Can you send a screenshot of the Settings page?

**Comment by RustoMCSpit** [comment]
> > doent work for me uhhh, not sure if you are missing something ngl
> 
> What version are you running? Can you send a screenshot of the Settings page?

lawnchair launcher is bugged surprisingly, made an issue report. sorry for wasting your time

**Comment by micahmo** [comment]
> lawnchair launcher is bugged surprisingly, made an issue report. sorry for wasting your time

No problem at all! Feel free to link the Lawnchair launcher issue if you want. Hopefully it gets resolved!

**Comment by RustoMCSpit** [comment]
> > lawnchair launcher is bugged surprisingly, made an issue report. sorry for wasting your time
> 
> No problem at all! Feel free to link the Lawnchair launcher issue if you want. Hopefully it gets resolved!
https://github.com/LawnchairLauncher/lawnchair/issues/3568

**Comment by RustoMCSpit** [comment]
> > lawnchair launcher is bugged surprisingly, made an issue report. sorry for wasting your time
> 
> No problem at all! Feel free to link the Lawnchair launcher issue if you want. Hopefully it gets resolved!

thanks micah

**Comment by hjiangsu** [comment]
I'll close this since this issue does not come from Thunder
