### ISSUE TITLE
Make votes visible on comments on user profiles

### ISSUE THREAD

**Issue by 1Phase1** [thunder-app/thunder#578]
**Is your feature request related to a problem? Please describe.**
On user profiles, upvotes and downvotes are not shown for comments. They are only shown for posts. 

**Describe the solution you'd like**
Add an option to make upvotes and downvotes on the comments of user profiles visible at a glance.

**Describe alternatives you've considered**
The only alternative is to press each comment one by one so the app will take you directly to the post it was posted under, or switch to Jerboa or another Lemmy app and view the user profile's comments there.

**Additional context**
If this option is added, the ability to sort comments and posts on user profiles would also be very useful.

**Comment by hjiangsu** [comment]
This should be added in the latest nightly release. Could you double check that and see if that's what you meant?

![simulator_screenshot_EE01822C-9EEE-4547-B93E-21C83C51EFB8](https://github.com/thunder-app/thunder/assets/30667958/1da3bdc7-a92b-4fbb-939f-ca4c83150663)

**Comment by 1Phase1** [comment]
@hjiangsu Ah, I was using the latest stable release. That's why I didn't see this feature. Thanks a lot.

**Comment by hjiangsu** [comment]
No worries! This will most likely arrive in the general release sometime later this week (hopefully)
