### ISSUE TITLE
Counter-intuitive animation when opening a post

### ISSUE THREAD

**Issue by noodlejetski** [thunder-app/thunder#583]
**Description**  
Version v0.2.1-alpha.2+14 has introduced new animations when opening a new post. The post itself slides in from the right side which is fine, but the list of posts seems to enlarge in the background, which makes it look like it's getting closer to the screen. It would feel more logical to have the list "shrink" instead, so that it looks like it's moving further into the background and making space for the post view.

**How to Reproduce**  
1. Open any post
2. Notice the opening animation

**Expected Behavior**  
The list of posts moves visually further into the background.

**Device & App Version:**  
 - Device: Fairphone 4
 - OS: Android 13
 - Version v0.2.1-alpha.2+14

**Comment by micahmo** [comment]
Wow, that's very subtle, but a great catch! Liftoff and the demo on the [swipeable_page_route package page](https://pub.dev/packages/swipeable_page_route) do not have this issue, so hopefully it's easily configurable! Liftoff doesn't have any animation for the current page (aside from parallax), which I think would be fine, but I also like the idea of the background moving back (Telegram does this).

**Comment by hjiangsu** [comment]
Could you supply a screen recording of this? I'm unable to reproduce it on my end!

**Comment by micahmo** [comment]
On an unrelated note, I notice the instance tagline uses markdown, which we should support. 😕 @noodlejetski Do you mind if I ask what instance you're using so I can test it?

**Comment by noodlejetski** [comment]
it's geddit.social. now that you mention it, I could've sworn it used to display markdown properly in the notice in the past... although it's possible that I've seen that on Jerboa, not Thunder.

**Comment by hjiangsu** [comment]
https://github.com/thunder-app/thunder/assets/30667958/49c9a2e8-083c-4e08-a828-11ad0e08fc09

**Comment by micahmo** [comment]
I can try to take a look at this later!
