### ISSUE TITLE
Unable to dismiss deleted reply from inbox

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#584]
In the latest build I'm experiencing an odd edge issue - I have a notification for a reply that was deleted, and I can't seem to dismiss it from my inbox:
 
![Screenshot_20230808-083125.png](https://github.com/thunder-app/thunder/assets/3624023/2d045fb6-256c-48d6-930e-471632b5a646)

Is there any way to detect that a comment has been deleted and automatically remove it from the inbox? And/or a way to mark something as read even if it technically no longer exists?

Using the latest pre-release on Android, if that's relevant!

**Comment by machinaeZER0** [comment]
That makes sense to me! If possible that would be super :)

**Comment by micahmo** [comment]
I believe this is a dup of #683.
