### ISSUE TITLE
Username shouldn't be tappable when a comment is collapsed

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#591]
**Is your feature request related to a problem? Please describe.**
Okay, so maybe it's a matter of opinion but the user loses a fair bit of "safe" space to tap and re-expand a comment that they've collapsed, and just how much space is lost depends on the character count of the username. The effect can be even more pronounced if scrolling with one's left thumb.

**Describe the solution you'd like**
The entire collapsed comment should be tappable for the purpose of re-expanding the comment. Usernames would only link to the commenter's profile when the comment has been expanded.

**Describe alternatives you've considered**
I can't really think of another, though I guess it creates a slightly inconsistent situation where a UI element (the username) would be visually identical but function differently in different contexts. Perhaps the username could be slightly grayed out when collapsed, though that may conflict with the highlighting that is done for admins, original poster, etc.

**Comment by micahmo** [comment]
@everdred Just to clarify you're talking about when "Hide Parent Comment on Collapse" setting is turned on, right? In that case, this makes sense. Otherwise there is very little tap area.

**Comment by everdred** [comment]
@micahmo Thank you for calling that out! Yes, I'm talking about when that setting is enabled.

**Comment by K4LCIFER** [comment]
Is it possible to simply adjust the tap area instead of removing functionality?

**Comment by micahmo** [comment]
@K4LCIFER Can you expand on what you had in mind? The tap area was already just the username (plus a tiny bit of padding I guess). Not sure if it could realistically be much smaller.
