### ISSUE TITLE
Use more distinctive colours for image/link icons

### ISSUE THREAD

**Issue by tom-james-watson** [thunder-app/thunder#596]
I find it difficult to distinguish between the "image" and "link" icons on posts, i.e. the little icon in the bottom right of the thumbnails on posts.

For example, in the below screenshot, it's not obvious that post 2 and 3 are of a different type to post 1, 4 and 5, because they are both two shades of brown.

<img src="https://github.com/thunder-app/thunder/assets/3852719/be6e870d-ee1d-4144-8edc-0ecf1e83359c" width=300 />

This seems to happen whether I use material you or not.

It would be better if these used more distinctive colours, i.e. if images used a secondary colour from the theme instead of a slightly different shade of the primary colour.

**Comment by tom-james-watson** [comment]
I think they should be derived from the theme, that way they always fit with the rest of the app theme.

I believe that at the moment they are both using derivatives of the primary colour of the theme, but IMO maybe one should use a secondary colour, or maybe one secondary and one tertiary.

**Comment by tom-james-watson** [comment]
If I can get past https://github.com/thunder-app/thunder/issues/598 I'd be more than happy to try and implement this myself.

**Comment by hjiangsu** [comment]
From the Matrix discussions, it seems like it'll be difficult to use `secondary` and `tertiary` colours since some Material You colour themes have very similar secondary/tertiary colours (which would then cause the same issue mentioned originally)

We might have to think of an alternative method which keeps all the colours somewhat distinct while matching the theme

**Comment by tom-james-watson** [comment]
I've made a PR (https://github.com/thunder-app/thunder/pull/603) with what I think is a reasonable way of addressing this. Let me know your thoughts on the PR - thanks!
