### ISSUE TITLE
"Your app is using an unsupported Gradle project."

### ISSUE THREAD

**Issue by tom-james-watson** [thunder-app/thunder#598]
I am trying to run the app in development and when I run main.dart, the app fails to load with:

```
Launching lib/main.dart on Pixel 4a in debug mode...
main.dart:1
Exception: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.
Exited
```

I am on macOS 13.5 and flutter 3.10.6 installed from homebrew.

I've not done loads of flutter dev so maybe this is a common general issue and is not to do with this project specifically, but I cannot find much when googling it and I can run other projects I've created fine.

**Comment by hjiangsu** [comment]
I think you might have to switch to a different Flutter channel. Could you try running `flutter channel beta` and `flutter upgrade` and try again?

**Comment by tom-james-watson** [comment]
That worked, thanks!
