### ISSUE TITLE
Open lemmy links in this app

### ISSUE THREAD

**Issue by BardiaB8** [thunder-app/thunder#60]
**Is your feature request related to a problem? Please describe.**
It currently isn't possible to open a post from a link in this app.

**Describe the solution you'd like**
Thunder to appear as an option to open Lemmy links.

**Describe alternatives you've considered**
Thunder could appear as an app that you can share links to, and open them if they are Lemmy links.

**Comment by hjiangsu** [comment]
For this, did you mean that a lemmy link outside of Thunder (e.g., on the browser) should be redirected to Thunder?

**Comment by BardiaB8** [comment]
Yes, that's exactly what I mean.

**Comment by hjiangsu** [comment]
Ahh, okay - for that, it might take a bit more time to integrate that feature as I'm not too familiar with it. If there is anyone that might know how this could be implemented, feel free to discuss about it here

However, I agree that it would be a nice addition! I'll keep it in mind but it might be lower priority as compared to some other features (unless the community votes otherwise)

**Comment by suoko** [comment]
I would Also like to share to thunder the links I visit with my browser

**Comment by everdred** [comment]
> If there is anyone that might know how this could be implemented, feel free to discuss about it here 

@hjiangsu On the Android side, here's how a couple of other open source Android clients implement it:

https://github.com/dessalines/jerboa/blob/main/app/src/main/AndroidManifest.xml
https://codeberg.org/Bazsalanszky/Eternity/src/branch/master/app/src/main/AndroidManifest.xml

**Comment by micahmo** [comment]
Looks like Jerboa queries api.fediverse.observer to auto-generate that list. Not a bad idea!

https://github.com/dessalines/jerboa/blob/d3c61ac712b171d2411f017142c5e82435f29886/app/update_instances.gradle.kts#L17-L21

As a fallback, we could also allow any link to be shared with Thunder, and if we detect that it's a Lemmy link, we can do smart navigation.

**Comment by hjiangsu** [comment]
This should now be done for Android with the nightly versions (0.2.5-x). Still working on iOS support in https://github.com/thunder-app/thunder/pull/868 so I'll keep this as in-progress
