### ISSUE TITLE
Option to display User Avatar

### ISSUE THREAD

**Issue by MetalZealot** [thunder-app/thunder#600]
**Is your feature request related to a problem? Please describe.**
Sometimes it's easier to discern a user by their Avatar, especially when scanning for small text and without any colour differentiation. Displaying their Avatar to the left of their user name would help with this

**Describe the solution you'd like**
implement a togglable option to Display User Avatar

**Comment by Toldry** [comment]
Bump.

@MetalZealot perhaps add the "enhancement" tag to this issue?
