### ISSUE TITLE
not all subscriptions showing

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#61]
**Description**  
In the sidebar not all my subscriptions are showing. See screenshots below

**Expected Behavior**  
All subscribed communities should be shown

**Screenshots**  
![Screenshot_20230624-172832_Jerboa_for_Lemmy](https://github.com/hjiangsu/thunder/assets/116814522/f9539e77-f1df-45df-be6c-0059c4844748)
![Screenshot_20230624-172715_thunder](https://github.com/hjiangsu/thunder/assets/116814522/22302600-418f-48ac-bfcf-adc428a92ef6)

**Device & App Version:**  
 - Device: [e.g. iPhone6] Motorola One 5G Ace
 - OS: [e.g. iOS8.1] Android 11
 - Version [e.g. 22] https://github.com/hjiangsu/thunder/releases/tag/v0.2.1-prerelease%2B5

**Additional Context**

**Comment by hjiangsu** [comment]
Do you have names of some of the missing communities if you dont mind sharing them for testing?

**Comment by shortwavesurfer2009** [comment]
> Do you have names of some of the missing communities if you dont mind sharing them for testing?

Thats the odd part. Its different ones at different times. Its acting like it can only display 10 at a time and picks random ones out of the list to show when the app loads

**Comment by hjiangsu** [comment]
>  it can only display 10 at a time and picks random ones out of the list to show when the app loads

That comment just helped me actually - I think its something to do with pagination if its only retrieving 10 of them. I don't think I've implemented pagination/infinite loading to the subscriptions list. I'll take a look at it when I have the time!

**Comment by hjiangsu** [comment]
Also linking this https://github.com/hjiangsu/thunder/issues/15 since it might be relevant/linked

**Comment by hjiangsu** [comment]
I'll add in a stop-gap for now, to just load up more subscriptions (100). I'll keep this issue open so that a more proper solution can be implemented

**Comment by shortwavesurfer2009** [comment]
Hey, would you like this closed? The "stop-gap" measure you added is working just fine

**Comment by ManikandanUV** [comment]
> I'll add in a stop-gap for now, to just load up more subscriptions (100). I'll keep this issue open so that a more proper solution can be implemented

I'm also facing this bug. I don't know if you're pulling subscriptions in alphabetical order, but some of the subscriptions that are missing are 2000snostalgia and 30rock, which would be the top of the list.

**Comment by hjiangsu** [comment]
I have changed it so that it should now fetch all your subscriptions - this will be part of the next release (and nightly release)
