### ISSUE TITLE
Accessibility: unspoken element between post title and link

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#622]
**Description**  
Talkback highlights an element between a posts title and the link url as shown below

**How to Reproduce**  
1. Go to system settings > accessibility > talkback and turn it on
2. Find a post with a link preview in Thunder
3. Tap the post title and then flick from left to right to go to the next element

**Expected Behavior**  
If this element is the link preview image talkback should skip it in favor of the URL element directly below it

**Screenshots**  
![Screenshot_20230810-203439_Thunder](https://github.com/thunder-app/thunder/assets/116814522/6db68288-500b-411a-a97f-cf21fe0f73c8)

**Device & App Version:**  
 - Device: [e.g. iPhone6] OnePlus Nord N200
 - OS: [e.g. iOS8.1] Android 13
 - Version [e.g. 22] v0.2.1-alpha.3+14

**Additional Context**

**Comment by micahmo** [comment]
@shortwavesurfer2009

When I tap the post, it reads the title and the URL.

![image](https://github.com/thunder-app/thunder/assets/7417301/0ce4af88-dff7-4f32-88ba-d0d6f4b5bdc0)

When I navigate to the next element, it highlights just the link preview, but doesn't read anything.

![image](https://github.com/thunder-app/thunder/assets/7417301/ed719c38-86ac-4699-a1f3-f19f5ea9cc58)

The link preview is intentionally a separate element. Clicking it will go directly to the web page, as opposed to clicking on the post which will go to the comments.

I'm wondering if the fix here is to _not_ read the URL when the post is selected and _do_ read it when the link widget is selected. What do you think?

**Comment by shortwavesurfer2009** [comment]
I think you are in the wrong view. I had the post actually open

**Comment by micahmo** [comment]
Ahh you're right! Although I think the same issue sort of exists in the feed view.

**Comment by shortwavesurfer2009** [comment]
I looked over your screenshots again and think your right. Have the link preview itself read the URL. I didn't fully grasp your idea when i first looked at it because i was still half asleep when i saw it.

**Comment by micahmo** [comment]
> I didn't fully grasp your idea when i first looked at it because i was still half asleep when i saw it.

No worries, so was I. 😆
