### ISSUE TITLE
Instance status on Account Selection

### ISSUE THREAD

**Issue by hjiangsu** [thunder-app/thunder#628]
**Is your feature request related to a problem? Please describe.**

Idea to add in a general connectivity status for a given instance when selecting an account from the profile selection modal. This would quickly give users that ability to determine if there downtime associated with a given instance (e.g., lemmy.world)

We can use the existing logic which fetches the instance's image so that we don't make too many API calls. If an instance does not respond in time, we can visually add an indicator that the instance may be experiencing downtime.

This would help users hopefully differentiate between problems related to Thunder vs the instance itself, leading to less unrelated bug reports or issues

**Describe the solution you'd like**

We can potentially use a status indicator icon located somewhere in the instance's image to represent the status (red for downtime, green for normal status)

**Describe alternatives you've considered**
N/a

**Additional context**

**Comment by micahmo** [comment]
I love this idea! I've been going to the account selection page and checking the icon as a status indicator. Makes sense to have something more explicit.

**Comment by shortwavesurfer2009** [comment]
> I love this idea! I've been going to the account selection page and checking the icon as a status indicator. Makes sense to have something more explicit.

Ha, i never even noticed this icon before and when this issue mentioned it iwas like "what icon? Oh, that one." A status indicator is a great idea i think.
