### ISSUE TITLE
make account switcher shorter

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#630]
**Is your feature request related to a problem? Please describe.**
The account switcher accessed either via a long-press of the profile icon on the navbar or through the 2 people icon on the account page is to tall and mostly empty

**Describe the solution you'd like**
Make the switcher only take up what area it needs at the bottom of the screen

![Screenshot_20230813-081518_Thunder](https://github.com/thunder-app/thunder/assets/116814522/f1754479-220f-4cec-90b2-0d7aa5b64b1c)

**Additional context**
In the screenshot above i only have 2 accounts logged in and all that empty space below

**Comment by micahmo** [comment]
Is this a dup of #606?

**Comment by shortwavesurfer2009** [comment]
Yep, my bad. I looked for open issues but didnt find that one

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by micahmo** [comment]
No worries! I'll close this as dup.
