### ISSUE TITLE
Saved comments are not shown in the saved section of the user profile

### ISSUE THREAD

**Issue by 1Phase1** [thunder-app/thunder#635]
**Description**  
The saved section of the user profile does not display saved comments, only saved posts

**How to Reproduce**  
1. Save a comment and a post.
2. Go to your own user profile.
3. Press the button labeled "saved".
4. The post saved in step 1 will appear, but not the comment.

**Expected Behavior**  
Both saved posts and saved comments should appear in the saved section.

**Screenshots**  
N/A

**Device & App Version:**  
 - Device: Samsung Galaxy S10 Plus
 - OS: Android 12
 - Version 0.2.2

**Comment by micahmo** [comment]
This is being worked on in #519!

**Comment by 1Phase1** [comment]
@micahmo Glad to hear it, thank you.

**Comment by CTalvio** [comment]
Merged!
