### ISSUE TITLE
Hide all communities on a specific instance

### ISSUE THREAD

**Issue by RUzOfuz5m** [thunder-app/thunder#641]
This request is to hide all communities on a specific instance (IE LemmyNSFW) for an account while still showing user comments from the hidden instance within different communities. I'd rather not request my home instance to defederate because I know some people might want to see this stuff.

I currently block 4 to 5 times the amount of communities I subscribe to as I like to browse All Posts sorted by new. Every time a new community pops up on an instance I dont care about, I have to block that one also.

**Comment by micahmo** [comment]
Related to #701.

**Comment by machinaeZER0** [comment]
Unless I'm misunderstanding, it sounds like this will be getting natively baked into lemmy itself in the upcoming 0.19 release? If so that should make it much easier to implement in Thunder!

**Comment by micahmo** [comment]
Yes, we are waiting for Lemmy's native implementation of this feature. Actually, that was already mentioned in #701. I wonder if we should close this one as dup.

**Comment by hjiangsu** [comment]
I will close this as its a duplicate as @micahmo mentioned!
