### ISSUE TITLE
Use empty space on search page for discovery features

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#646]
It would be good for Thunder to have some discovery features. Using the blank space on the search page for this should make sense.

I would suggest displaying three sections of suggested communities, Trending, Most Subscribed, and Most active. The latter two could even have buttons to open full lists of the communities on the current instance.

Unfortunately the dart api library does not have the ability to get these lists from the instance, so we will have to add that. I looked into doing this but 'm not sure where to begin nor that I can muster the investment to take that on until it'd be done :/

@micahmo  @hjiangsu Might one of you be able to look into that?

**Comment by micahmo** [comment]
Makes sense to me! Would we want to do this after something like #273 is done?

**Comment by CTalvio** [comment]
> Makes sense to me! Would we want to do this after something like #273 is done?

Doesn't matter to me. We discussed "advanced search" earlier and how it should be accessed via cog icon or the like in the search field.

This would be entirely separate from that, just filling the empty space before entering a search term with links to some top communities.
