### ISSUE TITLE
Accessibility: sort by top

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#649]
**Description** 
When you open sort by options talkback reads "sort by top" which when activated is actually the "back" button. These need to be individual elements as "back" is a button while "sort by top" is a header

**How to Reproduce**  
1. Go to system settings > accessibility > talkback and turn it on
2. Open thunder > tap sort options (top right) > tap "top" > tap "Top in Past Hour" (but do not activate it)
3. Flick from right to left to go to previous element

**Expected Behavior**
The back button and "sort by top" should be individual elements

**Screenshots**  
![Screenshot_20230817-065040_Thunder](https://github.com/thunder-app/thunder/assets/116814522/cbc9daeb-c10e-44a7-afa9-b55de6c6dc5f)

**Device & App Version:**  
 - Device: [e.g. iPhone6] OnePlus Nord N200
 - OS: [e.g. iOS8.1] Android 13
 - Version [e.g. 22] v0.2.3+16

**Additional Context**

**Comment by micahmo** [comment]
Hey @shortwavesurfer2009, just so you know, it is intentional that the header also acts as the back button. That just gives us a greater tap zone for going back. But I understand since TalkBack is identifying each element, it's a bit strange that activating the header also goes back.

I'll see what I can do to fix this, just wanted to provide some background on why it's the way it is and why it'll be a bit tricky to fix. 😆

**Comment by shortwavesurfer2009** [comment]
> Hey @shortwavesurfer2009, just so you know, it is intentional that the header also acts as the back button. That just gives us a greater tap zone for going back. But I understand since TalkBack is identifying each element, it's a bit strange that activating the header also goes back.
> 
> I'll see what I can do to fix this, just wanted to provide some background on why it's the way it is and why it'll be a bit tricky to fix. 😆

I see what you mean as i can tap the "p" in "sort by top" and it goes back. Simple fix, make it visually say sort by top as itdoes now and change its symantic label to "sort by top, back button"

**Comment by micahmo** [comment]
> change its symantic label to "sort by top, back button"

Easy enough, thanks!
