### ISSUE TITLE
Reply to comments 

### ISSUE THREAD

**Issue by RoxasTheNobody** [thunder-app/thunder#658]
I might be dumb, but I can't seem to be able to reply to comments.

**Comment by micahmo** [comment]
Hi @RoxasTheNobody, there are a few ways to reply to comments!

First of all, make sure you're logged in. Then try swiping from right-to-left on a comment. Reply should be the first swipe action, but you can customize this in Settings > Gestures.

If you don't like swipe gestures, you can also turn on comment buttons in Settings > General > Show Comment Button Actions. This should put a Reply button directly on every comment.

Finally, we plan on have all of these actions in the long-press menu (but reply is not there yet).

Hope that helps!

**Comment by RoxasTheNobody** [comment]
You know what, I turned off the gestures on the initial release. Now that I go in there, it says I can turn on the comment buttons in the General settings. 

I apologize for my incompetence lol
