### ISSUE TITLE
Option to prevent posts from turning grey after you interract with them

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#663]
**Description**  
When you interract with posts in the feed in certain ways, i.e. upvoting, downvoting, and un-favoriting, the post will get a grey highlight. 

**How to Reproduce**  
1. Find a post in the feed
2. Upvote, downvot, or un-favorite
3. observe that the post gets highlighted grey

**Expected Behavior**  
I expect it to not highlight grey

**Screenshots**  
Post upvote:

https://github.com/thunder-app/thunder/assets/7829231/d579a3ab-427e-457b-9927-8fbb601f6eea

Post Downvote:

https://github.com/thunder-app/thunder/assets/7829231/0ecc2490-3e5b-432a-84ea-072cb0b07d51

Post Favorite + Un-Favorite

https://github.com/thunder-app/thunder/assets/7829231/42c16407-ad61-4e6f-af14-99ae247b3800

**Device & App Version:**  

**Additional Context**  
I'm not sure if it matters, but I have the "Mark read after viewing media" setting turned off
![Screenshot_20230820-131024](https://github.com/thunder-app/thunder/assets/7829231/1b95c8d3-aaca-4934-a66d-6fd21e4a3ed9)

**Comment by CTalvio** [comment]
This is intentional behaviour. Interacting with posts sets them as read. Read posts are greyed out so you can tell what you have and haven't seen before. The view media option enables posts to get set as read from opening the image, useful in compact view.

The FAB in the lower right, will then get rid of all posts set as read.

**Comment by K4LCIFER** [comment]
Is it possible to disable posts turning read when they are interacted with? I personally don't like that they turn grey.

**Comment by CTalvio** [comment]
No. But this is a feature request, not a bug.

**Comment by micahmo** [comment]
Hey all, it seems like there may be two different requests in this issue.

1. The ability to never distinguish read from unread posts.
2. The ability not to mark posts as read when interacting in some way other than opening (i.e., upvote/downvote/save).

Have I captured the discussion correctly and do we agree that these are separate issues? Thanks!

**Comment by K4LCIFER** [comment]
> Hey all, it seems like there may be two different requests in this issue.
> 
>     1. The ability to never distinguish read from unread posts.
> 
>     2. The ability not to mark posts as read when interacting in some way other than opening (i.e., upvote/downvote/save).
> 
> 
> Have I captured the discussion correctly and do we agree that these are separate issues? 

The feature request is essentially to allow the user the ability to prevent posts from going grey when marked read.

**Comment by micahmo** [comment]
> The feature request is essentially to allow the user the ability to prevent posts from going grey when marked read.

Alrighty, thanks for the clarification! I believe that would be number one of the two potential issues we identified. Shouldn't be too hard. 😊
