### ISSUE TITLE
Allow the sorting of a users posts and comments on their profile

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#664]
**Is your feature request related to a problem? Please describe.**
Currently a user's posts, and comments on their profile are locked in their order.

**Describe the solution you'd like**
It would be nice to be able to sort them with the usual options, i.e. top, new, hot, etc.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by micahmo** [comment]
Just FYI, we can now sort posts/comments on other profiles, but still not on our own.
