### ISSUE TITLE
message not removable if deleted by user

### ISSUE THREAD

**Issue by firefoxlover** [thunder-app/thunder#683]
I have a comment by a user that they then deleted. It is now impossible to put a checkmark on and this placeholder stays there, saying "delted by creator".

Recreate:
- get a comment reply
- have the replyer delete that comment before you read it

Solution
Automatically delete this placeholder? Or allow checking it manually

**Comment by Lichtgestalt060** [comment]
Same here, plus: the inbox counter for unread replies stays at "1" now and can never be reset to zero again.
![Screenshot_2023-08-25-08-09-33-199_com hjiangsu thunder](https://github.com/thunder-app/thunder/assets/141391397/38710a8a-5f9a-407c-b64b-62ab63e9999d)

**Comment by CTalvio** [comment]
A workaround for you to use, until this is fixed in a future version: You can dismiss the inbox item via the web UI.

**Comment by firefoxlover** [comment]
@CTalvio I tried it and feddit.de actually doesnt support this too ! Maybe this is a Lemmy bug?

**Comment by micahmo** [comment]
I believe this is a dup of #584!
