### ISSUE TITLE
Move the view down to the highlighted comment in a thread when you open a comment from your post history, or notifications

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#688]
**Is your feature request related to a problem? Please describe.**

Currently, If you open a comment from your post history, notifications, etc. your view will move to the thread that that comment belongs to, but your view will start at the top of the thread. You then will have to scroll down to where that comment is located, manually.

**Describe the solution you'd like**

I propose that the view will automatically move down to the highlighted comment.

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by micahmo** [comment]
I believe this is a dup of #678.

**Comment by K4LCIFER** [comment]
> I believe this is a dup of #678.

Ah, so it is! My bad!
