### ISSUE TITLE
Instance Filtering

### ISSUE THREAD

**Issue by 1Phase1** [thunder-app/thunder#701]
**Is your feature request related to a problem? Please describe.**
The ability to filter entire instances and all users and posts associated with those instances would be a very useful feature for dealing with certain problem instances. Like if I don't want to see LemmyNSFW posts on my c/All feed without needing to block every individual LemmyNSFW community or make every NSFW post invisible (since not all NSFW is automatically porn), I could just filter the entire instance.

**Describe the solution you'd like**
An instance filtering feature, like the ones featured in other Lemmy apps such as Sync and Connect, where you can open the actions menu on a post, then press the "filter instance" option to filter the instance, as well as the ability to go into the settings and view a list of filtered instances from there, and filter an instance directly from there by inputting the instance domain name.

**Describe alternatives you've considered**
As of now, there is no alternative for this feature, short of using a different Lemmy app (I'd prefer to stay on this one) or waiting for the feature to be implemented site-wide, and presently there's no indication of a time frame on when that will happen.

**Comment by micahmo** [comment]
Thanks for the request @1Phase1! We've been tracking the progress on this over at Lemmy (https://github.com/LemmyNet/lemmy/pull/3869) and it looks like they're on the way to implementing it in the backend. Therefore, I believe we'd wait to implement this in Thunder until it's officially part of the API, otherwise we'd have to do it all over again when it is.

**Comment by 1Phase1** [comment]
@micahmo Ah, perfect. I was unaware there was a dedicated pull request for this feature. In that case, I'm satisfied with waiting for site-wide implementation. Thanks a lot for the answer. Thanks also for linking the pull request. I can now directly follow the PR's progress.
