### ISSUE TITLE
Cannot mark notification as read for deleted comment 

### ISSUE THREAD

**Issue by guerda** [thunder-app/thunder#702]
**Description**  
Somebody replied to a comment and I got a notification in thunder about it. As the reply was deleted, I cannot mark the notification as read. In the browser I already marked it as read but it still appears in thunder.

**How to Reproduce**  
1. Get a reply on a comment
2. Let the author delete the reply
3. Refresh notifications in Thunder
4. The notification is missing the "mark as read" button

**Expected Behavior**  
The notification can be cleared.

**Screenshots**  
![Imagepipe_8.jpg](https://github.com/thunder-app/thunder/assets/230782/371511ed-92c3-4b44-98b9-d3c9c4af6331)

**Device & App Version:**  
 - Device: Pixel 7
 - OS: Android 13
 - Version v0.2.3+16

**Comment by micahmo** [comment]
Hi @guerda, I believe this is a dup of #683 and #584 (and was recently fixed by #693, but not released yet). Thanks!

**Comment by guerda** [comment]
That seems to be the case. Thanks!
