### ISSUE TITLE
Floating action button Must have hide/show read post settings

### ISSUE THREAD

**Issue by SocialSavvy** [thunder-app/thunder#71]
floating action button It is only used to send posts. This needs to support more functions. Floating action button must have hide/show read post settings
![Screenshot_20230623-075733_Sync Pro](https://github.com/dessalines/jerboa/assets/107673019/d5045740-91d5-4ce9-aadc-2d8ea8d160f7)
Images that appear in attachments are available in the sycn for redit application. With the fab button settings, you can use the button for different settings if you want. 
![Screenshot_20230623-075930_Sync Pro](https://github.com/dessalines/jerboa/assets/107673019/959dd9a0-3a37-4541-906e-10fac680cf81)
If you don't want to use the fab button for different features in this way the other option is to have the hide read feature there if you click on the 3 dots in the upper right corner. 
![Screenshot_20230623-075754_Sync Pro](https://github.com/dessalines/jerboa/assets/107673019/23b7afbb-f9ad-4869-84d5-0100abd4fe8d)
This feature provides easy access to hide read settings. Because you don't want to see the same things on your page. A cleaner homepage is nice. This feature provides easy access to hide read settings. 
But you'd like to see it in your posts to see new comments. Or this feature should be turned off to see the post you have sent. A setting that is used continuously should be more easily accessible. 
Also in the user settings section, this setting does not work. It is necessary to enter the website and change it.

**Comment by SocialSavvy** [comment]
> Twitter has a google translate plugin that translates foreign-language content into the native language. In the picture, it says translate tweet in the marked place. ![Screenshot_20230625-152352_Twitter](https://user-images.githubusercontent.com/107673019/248555374-1b413698-f596-4eb1-a81a-95294869a721.jpg) In the picture here, the content seems to have been translated. ![Screenshot_20230625-152402_Twitter](https://user-images.githubusercontent.com/107673019/248555549-6a6e4e07-b492-4c57-8a2a-6d62f4f2614e.jpg) It would be very nice if a feature like this was made. Thank you for your efforts.

**Comment by CTalvio** [comment]
Picking this up

**Comment by ajsosa** [comment]
FAB redesign which includes hide read posts function is in general release. Closing.
