### ISSUE TITLE
unable to reply to comments 

### ISSUE THREAD

**Issue by KarkanAlzwayed** [thunder-app/thunder#721]
**Description**  
Can't reply to comments. I get a grey box and clicking it doesn't do anything. My keyboard doesn't pop up. 
**How to Reproduce**  
Just reply to a comment 

**Expected Behavior**  
To be able to reply to comments.

**Screenshots**  
![Screenshot_20230907_202648](https://github.com/thunder-app/thunder/assets/49320606/084005bb-eee1-4d54-8cd7-16453a25b043)

**Device & App Version:**  
 - Device: Samsung Galaxy note 20 ultra 5G
 - OS: Android 13
 - Version 0.2.4-1 pre-relase

**Additional Context**  
This is a brand new install, btw.

**Comment by micahmo** [comment]
I believe this is a dup of #716 and should be fixed by #700.

**Comment by KarkanAlzwayed** [comment]
> I believe this is a dup of #716 and should be fixed by #700.

I've actually searched the issues and didn't find it, so I created a new one. Thanks for pointing that out.

**Comment by micahmo** [comment]
> I've actually searched the issues and didn't find it, so I created a new one. Thanks for pointing that out.

No worries, it happens! 😊
