### ISSUE TITLE
"Exception: Failed to retrieve image dimensions" blocks post loading

### ISSUE THREAD

**Issue by Fmstrat** [thunder-app/thunder#740]
**Description**  
When scrolling up, the above message keeps any new posts from loading, making you unable to browse the feed.  

**How to Reproduce**  
1. Load your feed
2. Swipe up until the error displays and no more posts load

**Device & App Version:**  
 - Devicee.Tab S9
 - OS: Android
 - Version 0.2.4-2

**Comment by hjiangsu** [comment]
Hmm, this error usually pops up when there is a slow network connection or if you are in a place of low connectivity (e.g., outside with low connectivity)

How often does this occur, and is this through wifi or cellular connections?

**Comment by Fmstrat** [comment]
Not often, but when it does, it stops the whole session. I have found the root cause I think. It seems to happen when Pictrs responds with JSON indicating an error with an image. For instance:

    {"msg":"Error interacting with filesystem"}

**Comment by hjiangsu** [comment]
Ahh thanks for narrowing down the issue! It is weird how it stops the whole session though. The image dimensions error generally shouldn't cause an issue outside of making the image not load on the feed

**Comment by Fmstrat** [comment]
@hjiangsu Did a test to figure out what the specific problem might be. If I use an `error_page` redirect in NGINX to a "missing placeholder" image, it still fails. If I do an alias to the path for the same "missing image", Thunder does not lock up and shows the placeholder image while continuing to load posts.

This leads me to believe that two things are happening:
1. Thunder's calls are not following redirects (this can be a problem on proxies)
2. Thunder is not fully catching the above error, and is stopping the feed pull

**Comment by Fmstrat** [comment]
MIGHT have found it:

The call to `getLinkInfo` is outside of the `try` block: https://github.com/thunder-app/thunder/blob/def12c1d717da49f0fdaa62a308f18708cbbc601/lib/utils/post.dart#L137

And in `getLinkInfo` sets `imageUrl` inside an `if` block of a 200 status code: https://github.com/thunder-app/thunder/blob/def12c1d717da49f0fdaa62a308f18708cbbc601/lib/utils/links.dart#L25

However, it returns using that `imageUrl` variable outside of the if statement, meaning it's undefined: https://github.com/thunder-app/thunder/blob/def12c1d717da49f0fdaa62a308f18708cbbc601/lib/utils/links.dart#L39

I don't have my env set up to test this out, though.

**Comment by Fmstrat** [comment]
Decided to try something at lunch, and it proved the above is likely true. Dart `http` follows redirects by default, so if I add:
```
error_page 403 =200 /missing.jpeg;
error_page 404 =200 ./missing.jpeg;
error_page 500 =200 /missing.jpeg;
error_page 502 =200 /missing.jpeg;
error_page 503 =200 /missing.jpeg;
error_page 504 =200 /missing.jpeg;
```
to the proxy config, everything works, and `missing.jpeg` is displayed if there is any error reported from Pictrs. So the `200` if block seems to be the culprit.

**Comment by Fmstrat** [comment]
After actually diving in it LOOKS to be a simple missing try/catch. PR above.

**Comment by hjiangsu** [comment]
Hey, thanks for all the investigation and PR! I haven't had too much time to go through my notifications here so I missed a few 😅

I'll go ahead and check the PR in a bit, and merge it in once I review it. Thanks again!
