### ISSUE TITLE
Up/Down arrows for navigating comment threads

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#75]
One feature I found very useful in Boost for reddit (that recently got added to Jerboa) is the presence of navigation buttons in a post's comment view - using the Up and Down arrows jumps you between parent threads, which makes comments very easy to navigate.

In Boost this feature is even more useful - long-pressing the Up arrow brings you immediately to the top of the post you're viewing, which I've always really appreciated!

Screenshot attached showing this feature as implemented in Boost, if that's helpful - in their last update they even added a handy search function in addition to the navigation arrows!
![Screenshot_20230625-112504](https://github.com/hjiangsu/thunder/assets/3624023/a33d3243-1943-49ae-9ce3-64fc038665dd)

**Comment by CTalvio** [comment]
Would also be cool if the volume buttons could be used for this.
