### ISSUE TITLE
Add ability to switch user while commenting or posting

### ISSUE THREAD

**Issue by Coehill** [thunder-app/thunder#755]
**Is your feature request related to a problem? Please describe.**
I have Lemmy accounts on different instances which have different themes.  If I want to comment or post with a different account, then I will lose the post/comment thread I was on while I navigate to the menu to switch accounts.

**Describe the solution you'd like**
a) When commenting, it would be useful to be able to tap your username and have the ability to switch your user account from a dropdown that appears.
b) When posting, it would be useful to have the same functionality as a)

**Describe alternatives you've considered**
I do not see any other methods for accomplishing this.

**Additional context**
This is similar to functionality already available on the open source Android app RedReader for Reddit.

**Comment by micahmo** [comment]
Thanks for the suggestion! Is this a dup of #341?

**Comment by Coehill** [comment]
> Thanks for the suggestion! Is this a dup of #341?

Thanks @micahmo, apologies that I missed it while searching.  This can be closed as a duplicate.

**Comment by Coehill** [comment]
Duplicate of #341

**Comment by micahmo** [comment]
> apologies that I missed it while searching

No problem at all! Actually I like your specific implementation idea of tapping the username to initiate the switch! 👍
