### ISSUE TITLE
Add an option/toggle to automatically open links in Reader View

### ISSUE THREAD

**Issue by throwawaytime** [thunder-app/thunder#760]
This would be helpful as dark mode easily gets destroyed by links to bright white backgrounded pages; reader view addresses that.  As a bonus it also eliminates ads and can circumvent paywalls.

**Comment by hjiangsu** [comment]
Hey @throwawaytime, thanks for the suggestion! After briefly looking at this, it seems like we may be able to get reader view on iOS devices. I'm not sure if Android has a similar implementation of this.

If you know of anything with regards to the Android side, that would be helpful! I'm not seeing this option with the package we use to handle custom tabs. Maybe @micahmo can chime in on this and see if theres a viable solution for Android

References:
- Safari allows for reader view via `enterReaderIfAvailable`: [API reference](https://pub.dev/documentation/flutter_custom_tabs/latest/flutter_custom_tabs/SafariViewControllerOption/entersReaderIfAvailable.html)

**Comment by micahmo** [comment]
I'm not familiar with this as a standard Android feature. Some browsers and apps have a reader view feature, but I don't think it's something we could easily invoke. That said, I'm fine with this being an iOS-only feature until/unless we have a solution for Android.

**Comment by throwawaytime** [comment]
> Hey @throwawaytime, thanks for the suggestion! After briefly looking at this, it seems like we may be able to get reader view on iOS devices. I'm not sure if Android has a similar implementation of this.
> 
> If you know of anything with regards to the Android side, that would be helpful! I'm not seeing this option with the package we use to handle custom tabs. Maybe @micahmo can chime in on this and see if theres a viable solution for Android
> 
> References:
> 
> * Safari allows for reader view via `enterReaderIfAvailable`: [API reference](https://pub.dev/documentation/flutter_custom_tabs/latest/flutter_custom_tabs/SafariViewControllerOption/entersReaderIfAvailable.html)

I am only familiar with it on iOS.  This would be a great enhancement even if it has to be iOS-only.

**Comment by throwawaytime** [comment]
> I'm not familiar with this as a standard Android feature. Some browsers and apps have a reader view feature, but I don't think it's something we could easily invoke. That said, I'm fine with this being an iOS-only feature until/unless we have a solution for Android.

I am only familiar with it on iOS.  This would be a great enhancement even if it has to be iOS-only.
