### ISSUE TITLE
Upvote/downvote buttons on inbox notifications don't work

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#767]
**Description**  
When you receive a reply, the upvote/downvote buttons on the inbox notification visually react to being tapped and make the device vibrate, but don't cause a vote to happen.

**How to Reproduce**  
1. Receive notification of reply
2. Try to upvote/downvote reply from Thunder, see no vote registered
3. Check web version of Lemmy instance, ensure reply wasn't deleted, and observe that reply still exists but no vote was registered
4. Try voting the reply on web version (either on notification or directly on the original thread itself) and see that the vote works and is even reflected on the Thunder notification, after reloading the inbox on Thunder
5. Try removing the now-existing vote on the reply from Thunder inbox (it also fails)
6. Just in case, try voting on the reply on the original thread itself in Thunder (it works)

**Device & App Version:**  
 - OS: Android 13
 - Version 0.2.4

**Comment by micahmo** [comment]
Thank you for tracking this.

For devs, [reference comment](https://github.com/thunder-app/thunder/pull/608#issuecomment-1689142901).

**Comment by K4LCIFER** [comment]
> For devs, https://github.com/thunder-app/thunder/pull/608#issuecomment-1689142901.

From what I can see, that was merged, however I still appear to be unable to vote from the inbox.

**Comment by hjiangsu** [comment]
Yup, this should be fixed with the new inbox page!
