### ISSUE TITLE
"Accessibility mode" toggle switch

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#778]
Now that Thunder has an "Accessibility" menu in settings i suggest adding an "Accessibility Mode" toggle that would change all the following settings

1. General > Compact List View > set to "on"
2. General > Tappable Authors & Communities > set to "off"
3. General > Show Comment Button Actions > set to "off"
4. General > Enable Comment Navigation Buttons > set to "off"
5. Gestures > Navbar Swipe Gestures > set to "off"
6. Gestures > Navbar Double-Tap Gesture > set to "off"
7. Gestures > Post Swipe Actions > set to "off"
8. Gestures > Comment Swipe Actions > set to "off"
9. ~~Accessibility > Reduce Animations > set to "on"~~

Below the accessibility mode switch would be a text block explaining what settings will be impacted. Very similar to the text in the Floating Action Button area.

**Comment by micahmo** [comment]
I definitely like the idea of making it easier for people to enable "accessibility" as a whole in the app. My concern is that some of these things are just personal preferences, and I'm curious whether we'd want to introduce a setting that makes the app perfect for only one person (as much as we love you @shortwavesurfer2009 😊). Remember that you can always import/export settings to make configuring your own perfect experience easier.

"Accessibility" is a broad term and covers a range of preferences, disabilities, etc., and I'm afraid there's not a one-size-fits-all. I am guessing that most of the things you've selected here make the app work better with a screen reader. But what if, for example, someone simply wanted motion effects to be reduced.

I wonder if we could arrive at a compromise. Maybe a few meta-settings would help (like one that that disables all swipe-related gestures (post/comment/navbar)). Or maybe there's some other way we can identify settings that could potentially be related to accessibility, so they're easier to find.

Anyway, this is just my ignorant 2₵. I would love to hear from @hjiangsu and others members of the community, especially those whom this would personally effect!

**Comment by shortwavesurfer2009** [comment]
@micahmo no, i absolutely agree. I change more than these 9 but attempted to boil them down to what were not personal preferences. I tried to select only the ones that would reduce elements, gestures, etc. But i did come at this from a screen reader user POV.

**Comment by micahmo** [comment]
Thanks for the thoughtful response, as always, and for categorizing the list and the motivation behind each option. Let's definitely keep moving forward together on this path to make accessibility easier for everyone!

**Comment by shortwavesurfer2009** [comment]
I wonder if instead of "Accessibility Mode" we made seperate toggles for each thing. For example, these would be "Optimize for Screen Readers". If we get people who are color blind we might have an "Optimize for Color Blindness" or "Optimize for High Contrast", etc.
