### ISSUE TITLE
Add haptic feedback when one uses the Floating Action Button

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#780]
**Is your feature request related to a problem? Please describe.**
The floating action button has no feedback when you use it.

**Describe the solution you'd like**
It would be great to add haptic feedback for when the floating action button activates, and you use one of the actions.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by micahmo** [comment]
Hey @K4LCIFER, which scenarios should have feedback, and should they all be the same intensity?

- Single-press
- Single-press to open
- Long-press
- Long-press to open
- Press close
- Swipe close
- Single-press extended action

Also this should probably wait until #752 is done. 😊

**Comment by K4LCIFER** [comment]
> Hey @K4LCIFER, which scenarios should have feedback, and should they all be the same intensity?
> 
>     * Single-press
> 
>     * Single-press to open
> 
>     * Long-press
> 
>     * Long-press to open
> 
>     * Press close
> 
>     * Swipe close
> 
>     * Press extended action
> 
>     * Press comment navigation buttons
> 
> 
> Also this should probably wait until #752 is done. 😊

I'm not sure about all of those, but the one that certainly should have it is a long press. When you trigger the start of a long press it should provide feedback, then when it activates, more feedback.
