### ISSUE TITLE
Add spell check

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#784]
**Is your feature request related to a problem? Please describe.**
Add the system spell checker functionality for those of us who cant words

**Describe the solution you'd like**
Enable the system spell check in post/comment title/body boxes so incorrect spellings get the red underline and tap to correct suggestions

**Comment by micahmo** [comment]
Is this related to #499?

**Comment by shortwavesurfer2009** [comment]
> Is this related to #499?

Ah, yeah. I did do a search for "spell" and "spell check" but that one did not come up

**Comment by micahmo** [comment]
No worries! It was in the back of my mind, but I had a hard time finding it too, for the same reason. Let me update the title there.
