### ISSUE TITLE
Prepare for Lemmy 0.19

### ISSUE THREAD

**Issue by machinaeZER0** [thunder-app/thunder#786]
According to this recent post, the next version of Lemmy will require client updates as new features and updates are implemented:

https://lemm.ee/post/9758985 (hopefully linked in a helpful way)

It looks like there is a release candidate running at https://voyager.lemmy.ml/ that can be used for testing purposes, and that (in theory) it should be possible for clients to support both 0.19 and 0.18 through the transition period.

Just wanted to put it on the radar since I saw it pop up in my daily browsing :)

**Comment by machinaeZER0** [comment]
Just realized this is a duplicate, whoopsie!

**Comment by micahmo** [comment]
No worries about the dup. Actually, thank you very much for the link to the beta instance. That's incredibly helpful!
