### ISSUE TITLE
If you quickly tap the  "Search" button when Thunder is first loading, it will glitch out and select "Search" without actually going to the search page

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#794]
**Description**  
If you quickly tap the "Search" button when Thunder is loading, it will glitch out and select the button without actually going to the search page. You can only then go to the search page if you deselect the search button, for example, by tapping the feed button then reselecting the search button. 

**How to Reproduce**  
1. Launch Thunder fresh
2. Quickly start tapping the search button
3. Observe that it will select without going to the search page
4. Observe that further tapping of the search button will not take you to the search page
5. tap the "Feed" button to deselect the search button
6. observe that the "Search" button now works as intended.

**Expected Behavior**  
I would expect the search button to work as soon as it pops up.

**Screenshots**  

https://github.com/thunder-app/thunder/assets/7829231/188546ce-784c-4efd-966f-6ba94fcb7245

**Device & App Version:**  
 - Device: Pixel 6
 - OS: Android 14
 - Thunder v0.2.4

**Additional Context**  
None.

**Comment by K4LCIFER** [comment]
I have found that this same behaviour occurs with all of the buttons on the bottom row, and not just the search button.

**Comment by michalsieron** [comment]
I think this is fixed in v0.3.0 (maybe earlier?).

However, I found another issue. When Thunder is first loading and one taps "Feed" button, the entire application will hang with no way to recover.

**Comment by K4LCIFER** [comment]
> I think this is fixed in v0.3.0 (maybe earlier?).

Indeed it appears to be! I will close this then.
