### ISSUE TITLE
Mark as read on scroll

### ISSUE THREAD

**Issue by Offerel** [thunder-app/thunder#805]
**Is your feature request related to a problem? Please describe.**
It would be nice, to know how far i have seen articles in a earlier session. That's why i would prefer some way to mark articles as read on scroll.

**Describe the solution you'd like**
I don't know if this is a history feature or one of It's own.

**Describe alternatives you've considered**

**Additional context**

**Comment by micahmo** [comment]
I believe this is a dup of #169.

**Comment by Offerel** [comment]
Yes, that's the same. Sorry, I have not seen this fr. I will close my own.

**Comment by micahmo** [comment]
No worries!
