### ISSUE TITLE
Add toggle to disable swipe to close comments

### ISSUE THREAD

**Issue by nimxaa** [thunder-app/thunder#815]
**Is your feature request related to a problem? Please describe.**

I sometimes trigger it by accident and then lose the comment that I was reading.

**Describe the solution you'd like**

Option to disable it.

**Describe alternatives you've considered**

\-

**Additional context**

I'm talking about this:

https://github.com/thunder-app/thunder/assets/145933422/694392f7-c484-409b-9e49-8014d1407f32

**Comment by Amunak** [comment]
Realistically it should be enough if the gesture was better tuned - expect that the user wants to scroll, and the back gesture would trigger only if you move in the X direction way more than currently.

**Comment by nimxaa** [comment]
> Maybe an option here then is to have an option in the settings which disables the full screen swipe to go back feature?

That would be nice, because you can still use the back button on your phone to go back.
