### ISSUE TITLE
Disabled FAB still impedes scroll swipe (again!)

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#819]
**Description**  
The circumstances of this bug are almost identical to #651, which was fixed. But in short: disable the floating action button and attempt to scroll using the spot where the button used to be, and the scroll gesture is caught by the invisible button.

The differences this time:
* Attempting to scroll from that spot results in the content area becoming dark, with only bottom bar visible. Tap elsewhere to dismiss. (On #651 there was no visual feedback.)
* Appears to only affect post feed, not when viewing an individual post where the button is also disabled.

**Screenshots**  
[Screencast of bug](https://github.com/thunder-app/thunder/assets/5367819/8147d557-6270-474e-b53f-41cc885d63d9)

**Device & App Version:**  
 - OS: Android 13
 - Version v.0.2.5-1

**Comment by hjiangsu** [comment]
Thanks for reporting this @everdred! This was most likely a result from the underlying changes that were made to the feed page. I'll link this with #811 since its somewhat related to that

**Comment by micahmo** [comment]
For reference, original fix in #653.

**Comment by hjiangsu** [comment]
As this was introduced in a nightly build but was fixed previously, I'll mark it as complete!
