### ISSUE TITLE
Grab the article title from link and use that as suggested post title

### ISSUE THREAD

**Issue by ggichure** [thunder-app/thunder#850]
**Is your feature request related to a problem? Please describe.**

Currently when we are creating new posts from share intents, one has to type the title.

**Describe the solution you'd like**

Grab the article title from link and use that as suggested post title.

**Describe alternatives you've considered**

**Additional context**

**Comment by micahmo** [comment]
This is done for URLs shared through intents. Still needs to be done for links typed/pasted into the new post screen.
