### ISSUE TITLE
Unable to open post link when viewed from replies or comments

### ISSUE THREAD

**Issue by tibert01** [thunder-app/thunder#856]
**Description**  
The embedded link shared on a post (in the post, the on out in the URL box), cannot be opened when the post is viewed from a comment on that post or a received reply.
It also happened with saved comments.

But opening the link does work when opening a post from saved. 

Links in the comments or in the post text can still be opened. 

**How to Reproduce**  
1. Reply to a post with an embedded link or comment on the post. 
2. Go to profile, comments, and open your comment (opening a received reply has the same effect) 
3. (optional) clic on view all comments
4. Try clicking on the link.
5. The link does not open. 

**Expected Behavior**  
The embedded link, viewed from a comment or reply should open when clicked. 

**Device & App Version:**  
 - Device: OnePlus 8 po
 - OS: Android, oxygen os 13.1
 - Version : 0.2.4 play store.

**Comment by hjiangsu** [comment]
Hey! I was not able to reproduce this on 0.2.5. Could you confirm whether or not this has been fixed?

**Comment by tibert01** [comment]
Seems to be fixed on 0.2.5, thanks.
