### ISSUE TITLE
Accessibility: select community to post to with talkback

### ISSUE THREAD

**Issue by shortwavesurfer2009** [thunder-app/thunder#872]
**Description**  
When using talkback to select a community to post to (from the main feed) the community takes up two swipes. The first one lets you select the community whilr the second one does not.

**How to Reproduce**  
1. Enable talkback from android settings > accessibility
2. Open thunder > from the fab on main feed create new post
3. Open the "select a community" box
4. Single tap a community and then swipe right to go to the next items.
5. See error

**Expected Behavior**  
The community should only have a single elemrnt

**Screenshots**  
Allows the community to be chosen
![Screenshot_20231103-135949_Thunder](https://github.com/thunder-app/thunder/assets/116814522/e32d1257-d36a-4e00-a7e3-d4b0802e226e)

Does not allow the community to be chosen
![Screenshot_20231103-135955_Thunder](https://github.com/thunder-app/thunder/assets/116814522/1b2b1e53-5d0e-462b-8965-e11d583886fe)

**Device & App Version:**  
 - Device: [e.g. iPhone6] OnePlus Nord N200
 - OS: [e.g. iOS8.1] Android 13
 - Version [e.g. 22] 0.2.5-3

**Additional Context**

**Comment by hjiangsu** [comment]
This should be fixed in [0.2.5-4](https://github.com/thunder-app/thunder/releases/tag/0.2.5-4) so I'll mark it as complete for now. Let me know if this issue is still present in the latest nightly build
