### ISSUE TITLE
General settings page appears blank

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#876]
**Description**  
When trying to view "General" settings category, page appears blank (light gray).

**How to Reproduce**  
1. Go to Settings
2. Tap on General, page is gray 
3. Go to Theming or any other category, page displays as expected

**Screenshots**  
[screencast](https://github.com/thunder-app/thunder/assets/5367819/2c232f32-96bf-4680-9c35-57e29fc1562c).

**Device & App Version:**  
 - OS: Android 13
 - Version 0.2.5-3

**Comment by hjiangsu** [comment]
Thanks for reporting the bug! It seems like your assumptions are correct about "New" being missing causing the gray screen to show up.

For a temporary workaround, you can try to reset your user preferences by going to Debug -> Delete Local Preferences. Do note that this **will remove any existing preferences.**

**Comment by everdred** [comment]
Thank you for suggesting the workaround! I'll probably just stick with the previous prerelease for the meantime.

**Comment by hjiangsu** [comment]
This should be fixed in [0.2.5-4](https://github.com/thunder-app/thunder/releases/tag/0.2.5-4) so I'll mark it as complete for now. Let me know if this issue is still present in the latest nightly build

**Comment by everdred** [comment]
Yep, I can view the General settings again while in New sort. Thank you!
