### ISSUE TITLE
Sort by "New" option missing for posts (but not comments)

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#877]
**Description**  
Option to sort posts by New does not appear among sorts. Since "New" is my default sort setting, I can use it until I change to another sort style. New sort does appear for comments.

Unsure if this is related to #876, but due to that issue I'm unable to try switching to another default sort.

**Screenshots**  
[Screenshot](https://github.com/thunder-app/thunder/assets/5367819/85e6fca4-d91e-4e0a-b3bc-a2b773919a22)

**Device & App Version:**  
- Instance: 0.18.5
 - OS: Android 13
 - Version 0.2.5-3

**Additional Context**  
Worth noting that when sorted by my default New, the usual "New" label does not appear up top under "Subscriptions" or "All posts," but labels appear if I switch to another sort (e.g. Hot).

**Comment by hjiangsu** [comment]
This should be fixed in [0.2.5-4](https://github.com/thunder-app/thunder/releases/tag/0.2.5-4) so I'll mark it as complete for now. Let me know if this issue is still present in the latest nightly build!

**Comment by everdred** [comment]
Just grabbed 0.2.5-4 and this is resolved.
