### ISSUE TITLE
Image upload buttons non-functional

### ISSUE THREAD

**Issue by cooperaj** [thunder-app/thunder#884]
**Description**  
Pressing either of the image upload buttons on a new post does nothing.

**How to Reproduce**  
1. Make a new post
2. Press image button next to URL field.
3. Nothing happens
4. Press image button on markdown field.
5. Nothing happens.

**Expected Behavior**  
Some sort of file selection dialog should appear?

**Device & App Version:**  
 - Device: Pixel 6 Pro
 - OS: Android 14
 - Version v0.2.5-3

**Comment by hjiangsu** [comment]
Thanks for the bug report! I was able to reproduce the issue. A fix will be added in the next nightly build for this issue.

**Comment by hjiangsu** [comment]
This should be fixed in [0.2.5-4](https://github.com/thunder-app/thunder/releases/tag/0.2.5-4) so I'll mark it as complete for now. Let me know if this issue is still present in the latest nightly build
