### ISSUE TITLE
A Way to Edit Posts

### ISSUE THREAD

**Issue by KrispeeIguana** [thunder-app/thunder#892]
It would be quite nice to have either a button or a gesture to edit a post. I usually edit posts to place a solved tag in the title or provide extra information so people don't need to dig into the comments to find it. 
Currently, I need to leave the Thunder app and go to my lemmy profile in browser in order to edit anything. This is quite inconvenient.

**Comment by hjiangsu** [comment]
Hey there! Thanks for creating the issue. The ability to edit posts (and other general improvements to the post creation) are being actively worked on in this PR: #893. This is still a work-in-progress but will hopefully be coming to a nightly/pre-release version soon.

**Comment by K4LCIFER** [comment]
I noticed that the ability to edit a post from the profile doesn't exist (v0.2.8). Is this a separate issue, or just simply overlooked in the mentioned PR?

**Comment by KrispeeIguana** [comment]
I was mainly looking for any way at all to edit a post, so sure, I guess this would be a part my request.

**Comment by micahmo** [comment]
> I noticed that the ability to edit a post from the profile doesn't exist (v0.2.8).

Would you like this as a swipe action or maybe a long-press action?

Just FYI, you can always open the post from your profile and then press edit from there. Just one extra click. 😊

**Comment by KrispeeIguana** [comment]
What about a long press action? We already have quite a few swipe actions and  at some point, they will get confusing if they aren't already for some.
