### ISSUE TITLE
Comment Content Font Scale setting non-functional

### ISSUE THREAD

**Issue by everdred** [thunder-app/thunder#897]
**Description**  
Changing the setting for "Comment Content Font Scale" doesn't change the appearance of comments, but changing "Post Content Font Scale" changes _both_ post and comment text sizes.

**How to Reproduce**  
1. Set comment text size
2. Go back to the feed, tap a post, observe comment text size hasn't changed
3. Set post text size
4. Go back, observe both post _and_ comment text size has changed, both types of text matching what is set for post size

**Expected Behavior**  
The two types of text should be independently configurable.

**Additional context**
Post title and metadata settings are not affected by this, and changing them does not affect any other text type.

**Device & App Version:**  
 - OS: Android 13
 - Version 0.2.5

**Comment by hjiangsu** [comment]
Thanks for the report, this issue will be addressed alongside #896!

**Comment by everdred** [comment]
Thank you @hjiangsu, that's great to hear! In case it matters, I noticed one place where comment size seems to have an effect: in the "Load _n_ more replies…" placeholder.

**Comment by hjiangsu** [comment]
This has been released in 0.2.6-1. Let me know if you encounter any further issues!

**Comment by everdred** [comment]
Confirmed it works now in 0.2.6-1. Thank you!
