### ISSUE TITLE
Add Interface Language Selector in Settings

### ISSUE THREAD

**Issue by Kjev666** [thunder-app/thunder#899]
**Is your feature request related to a problem? Please describe.**
Due to unavailability of my desired language on my smartphone's (android 12) global settings. I have to rely on the translations and language selection system of an application to use it in the language I desire.

**Describe the solution you'd like**
A drop down menu being added in the settings to select which language the user wishes to use the application in is pretty much it.
Plus, it would also help in overall user accessibility if the language selector is shown during first time launch of the application.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hjiangsu** [comment]
>  if the language selector is shown during first time launch of the application.

The implementation in the PR only accounts for the drop down menu at this time! I think this specific request can be moved to a separate issue since it requires a bit more complexity (would need to start thinking about overall initial onboarding process for first time launch and how this fits in)
