### ISSUE TITLE
Support older versions of Lemmy (0.16)

### ISSUE THREAD

**Issue by retiolus** [thunder-app/thunder#9]
**Is your feature request related to a problem? Please describe.**
Older versions not supported.

**Describe the solution you'd like**
Support older versions, at least 0.16.*

**Additional context**
As seen on https://fedidb.org/software/lemmy, +50 servers are still running 0.16, these servers can't be used on the app.

**Comment by hjiangsu** [comment]
Thanks, I'll take a look at seeing how to support older versions of lemmy (although it is lower on my priority for now as I focus on some more core functions of the app)

Do you happen to know any information about what the differences between the major versions are? (different api calls, etc.?) This would help me better understand how to support those older versions!

**Comment by hjiangsu** [comment]
@retiolus Would it be possible for you to provide me some links to instances running on 0.16? This way, I can create a test account on them and try to dig a bit deeper into potentially adding support for those instances

**Comment by micahmo** [comment]
@retiolus Is this still a consideration? I noticed the example you gave, [lemmy.cat](https://lemmy.cat/), is now on 0.18.2.

**Comment by hjiangsu** [comment]
I'll close this issue since it no longer seems to be relevant. As mentioned previously, we'll have a best effort basis to support the most popular version(s) based on stats from https://fedidb.org/software/lemmy
