### ISSUE TITLE
Links are opening in a chromium browser instead of default

### ISSUE THREAD

**Issue by tibert01** [thunder-app/thunder#902]
**Description**  
When clicking a link, and the setting to open in external browsers is disabled, the link will open in any chromium browser installed on the device.

Chrome seems to have priority on other browsers (Chrome and Brave are installed on the device). 

If Chrome is disabled, the links will open in brave, and so on until no chromium browsers are left installed. Then it will open in Firefox. 

**How to Reproduce**  
1. Disable open in external browser. 
2. Set Firefox as default browser in android. 
3. Have a chromium browser installed/Chrome. 
4. Open a link from a post. 

**Expected Behavior**  
The link should open in the default browser as an integrated page. 

**Device & App Version:**  
 - Device: OnePlus 8 pro
 - OS: Oxygen os 13.1 (android 13)
 - Version v0.2.5

**Comment by hjiangsu** [comment]
Thanks for the report! I don't think there was a large change in terms of how we handle custom tab links, so this may be a result of the underlying package that we use.

I'll attempt to look into this, but it might be more difficult since I don't have a physical Android device to test with.

**Comment by hjiangsu** [comment]
For devs: This will become an option in an upcoming update for the package. Until then, this will be on hold!

https://github.com/droibit/flutter_custom_tabs/issues/143
