### ISSUE TITLE
Enable link preview thumbnails for compact view

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#91]
**Description**  
In compact view, thumbnails are empty on posts that would load an image preview in normal view. The box is present regardless of whether there is content to display in it, wasting space.

**How to Reproduce**  
1. Enable compact view
2. Compare link posts to their appearance in normal view

**Expected Behavior**  
The thumbnails should show the same images as in normal view. For text posts, there should be no "thumbnail box" at all, like in normal view. Links should be marked with a small banner, same as normal view. Images that can be opened, should have no markings, or a icon indicating it is an image post.

**Screenshots**  
![image](https://github.com/hjiangsu/thunder/assets/4365015/f9fe6fa6-569c-475d-973c-7bea372e3d12)

**Device & App Version:**  
 - Device: ZenFone 6
 - OS: Android 11
 - Version 0.2.1+7

**Comment by CTalvio** [comment]
@hjiangsu Are link previews broken in the latest release? I'm not seeing images on any links at all, even in normal view.

Regardless, you can assign this one to me.

**Comment by micahmo** [comment]
It would also be nice if there were some way to distinguish a link from an image in compact view. I know Relay used little colored triangles in the corner (blue = gif, green = slideshow, gray = image, none = link). For now, maybe just having the link icon hovering somewhere around the preview would be sufficient.

**Comment by CTalvio** [comment]
I'll likely make some kind of indicator for links, yes.

**Comment by hjiangsu** [comment]
> Are link previews broken in the latest release? I'm not seeing images on any links at all, even in normal view.

I don't think any logic was touched for the link previews since last release but I may be wrong - I'll take a look at it and see
