### ISSUE TITLE
Option to hide read posts by default

### ISSUE THREAD

**Issue by tj9fu5bu** [thunder-app/thunder#913]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option to automatically hide read posts in subscriptions or per community.

**Describe alternatives you've considered**
Manually hiding all posts when the page is refreshed or app is reloaded.

**Additional context**
Issue might be encountered if a huge number of posts are already read.

**Comment by hjiangsu** [comment]
I think the first step to this is to add an option which syncs up to your Lemmy account settings. Lemmy already has a setting to allow hiding or showing read posts.

This option wouldn't be as granular has being able to choose to hide posts in Subscriptions or on a community-basis, but that might be something to be explored in the future.

**Comment by tj9fu5bu** [comment]
@hjiangsu this feature seems to be broken with v0.19.0 instances.

**Comment by hjiangsu** [comment]
Just wondering, but did your instance recently upgrade to 0.19.0? If so, you may have to log out and log back in for things to work! There were authentication changes made behind the scenes so this might be what's causing the issues.

Let me know if that fixes the issue or not.

**Comment by hjiangsu** [comment]
It seems like this may actually be on Lemmy's end with the 0.19.0 update: https://github.com/LemmyNet/lemmy/issues/4290

**Comment by tj9fu5bu** [comment]
Oh yes, I've logged out and logged back in to get back my subscribed communities. I guess it's really on Lemmy's end then!

**Comment by hjiangsu** [comment]
Could you let me know if this is fixed? It seems like a fix was pushed in Lemmy 0.19.1. If it is fixed, I'll mark this issue as closed!

**Comment by tj9fu5bu** [comment]
I can indeed confirm that this has been fixed in 0.19.1 instances!

@hjiangsu
