### ISSUE TITLE
Support User Display Names

### ISSUE THREAD

**Issue by CTalvio** [thunder-app/thunder#92]
**Is your feature request related to a problem? Please describe.**
Currently, users are identified using their handles, not their self-chosen display names.

**Describe the solution you'd like**
Respect user display names.

In the future, user avatars and home instances would also be nice.

**Comment by hjiangsu** [comment]
Do you think this is better as a toggle in the settings to switch between them, or should the current user handles be directly replaced with the display names?

**Comment by wildebeest3** [comment]
> Do you think this is better as a toggle in the settings to switch between them, or should the current user handles be directly replaced with the display names?

I think it would be better as a toggle

**Comment by CTalvio** [comment]
A toggle. Display names by default.

**Comment by CTalvio** [comment]
I am looking into this.

Assign to me @hjiangsu ?

**Comment by hjiangsu** [comment]
Sounds good! Thanks!
