### ISSUE TITLE
Issues with creating post from share.

### ISSUE THREAD

**Issue by micahmo** [thunder-app/thunder#922]
**Description**  

There are now issues trying to create a new post from a share. I believe this is related to #893.

**How to Reproduce**  
1. From an external app, share a link to Thunder.
2. Notice that the post body has an issue.
3. Pick a community and try to post.
4. Notice that there is a Lemmy error related to the language selection.

**Expected Behavior**  

No errors when trying to share/post.

**Screenshots**  

https://github.com/thunder-app/thunder/assets/7417301/df23f086-ff9b-44bc-b64e-ac50ee1de334

**Device & App Version:**  
 - Device: Android Emulator
 - OS: Android 13
 - App Version: `develop` branch

**Additional Context**  
N/A

**Comment by hjiangsu** [comment]
I'll test it out on an Android emulator when I can later - thanks for catching this!

**Comment by micahmo** [comment]
I did some checking into the second part of this (the `language_not_allowed` error), and I still don't know why it's happening, but I can sort of "reproduce" on the web. If I select "Undetermined" while making a post in technology@lemmy.world, it ignores the selection.

https://github.com/thunder-app/thunder/assets/7417301/dc05ea4c-6f88-4d14-954d-e13a251c0097

That said, I can post without any selection ("Select language"), so I was thinking maybe that should be the default in Thunder instead of "Undetermined".

**Comment by micahmo** [comment]
I can't reproduce this any more after PRs #932 and #933, so I'm gonna say it's all set!
