### ISSUE TITLE
App Language set to Arabic after Update (RTL Layout)

### ISSUE THREAD

**Issue by justTOBBI** [thunder-app/thunder#929]
**Description**  
After I updated Thunder to 0.2.7-1 the app started in the RTL Layout, since my language was set to Arabic

**How to Reproduce**  
1. Install 0.2.6
2. Update to 0.2.7-1
3. Open the updated App

**Expected Behavior**  
My previous language setting should be respected

**Device & App Version:**  
 - Device: Xiaomi Redmi Note 8 Prp
 - OS: Android 11 (Miui 12.5.7)
 - App Version 0.2.7-1

**Comment by hjiangsu** [comment]
Hey, thanks for the report! Just to clarify, is your system language set to Arabic? or did you set Thunder's app language to be Arabic?

If it's your system's language, and you want to enforce English within Thunder, you can go to Settings -> General -> App Language, and select English. This should force the layout to be LTR.

**Comment by hjiangsu** [comment]
If you'd prefer, there might also be a way to force LTR layout for any RTL layout localizations.

**Comment by hjiangsu** [comment]
Hmm, that's weird. I'll take a closer look into this but for now, please use "English" as the app language to fix this issue while a fix is applied!
