### ISSUE TITLE
Option to move the Floating Action Button

### ISSUE THREAD

**Issue by hilmarp** [thunder-app/thunder#930]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Option to move the Floating Action Button (FAB), at least move it to the left.

**Describe alternatives you've considered**
Could be an option to move it to any of the four corners.

**Additional context**
It's because I keep hitting the FAB when I'm scrolling, it's exactly where my thumb goes, but I'd still like to have it enabled.

**Comment by micahmo** [comment]
Is this a dup of #722?

**Comment by hilmarp** [comment]
> Is this a dup of #722?

Yes it is, didn't find it because I searched for "floating", I'll close this one.
