### ISSUE TITLE
Create Post view does not present all fields

### ISSUE THREAD

**Issue by josevh** [thunder-app/thunder#94]
**Description**  
The Create Post view is not displaying all fields. 

**How to Reproduce**  
1. Go to any community. 
2. Click on PLUS floating button.
3. Observe the Create Post view.
4. See error, not all fields are visible.

**Expected Behavior**  
I would expect to see form fields:
- photo upload
- URL input
- language input

**Screenshots**  
![Screenshot_20230625_185818](https://github.com/hjiangsu/thunder/assets/8278253/a192d2ea-7d34-4812-b0bf-14b2327c7794)

**Device & App Version:**  
 - Device: Samsung Galaxy S22
 - OS: Android 13
 - Version: v0.2.1+7

**Additional Context**  
I cannot scroll the form. Cannot move the "Clear" and "Show Preview" buttons away from the center of the screen.

**Comment by josevh** [comment]
@hjiangsu regarding your question, the buttons stay there regardless of whether the keyboard is shown. With the keyboard shown, one can scroll the form but only a few pixels.

A similar issue occurs when creating comments (screenshots attached). Although, when the keyboard is up you _can_ scroll to show the buttons when hidden by the keyboard.

![Screenshot_20230626_060413](https://github.com/hjiangsu/thunder/assets/8278253/5da14a78-1735-46e1-bcec-513f294f1cf2)

![Screenshot_20230626_060436](https://github.com/hjiangsu/thunder/assets/8278253/72017aea-77b5-4d19-8c6c-eca848f2fe0a)

![Screenshot_20230626_060448](https://github.com/hjiangsu/thunder/assets/8278253/39ab031b-2a87-499a-ab7a-c90923d16e67)

![Screenshot_20230626_060459](https://github.com/hjiangsu/thunder/assets/8278253/64cf1ec8-54c9-45a8-aa2d-15d9cbe067e3)

![Screenshot_20230626_060856](https://github.com/hjiangsu/thunder/assets/8278253/126bc778-df39-4f03-9e6e-50ee251fcd0d)

**Comment by hjiangsu** [comment]
Thanks for the detailed response! That seems to be generally what should be happening (although the clear and preview buttons shouldn't be stuck to the middle of the screen)

I'll take a closer look at it, but from first glance, it might be a padding issue since it seems as if the markdown text editor is slightly cut off at the bottom

This is how it should look like: ![image](https://github.com/hjiangsu/thunder/assets/30667958/98fdf8e6-09b1-43da-8445-593752770e0c)

**Comment by josevh** [comment]
Ah ok, the editor being cutoff at the bottom gave me the impression that there was a longer form and the buttons were covering it due to being pushed up by space reserved for the keyboard.

**Comment by ajsosa** [comment]
Create post page was completely redesigned in https://github.com/thunder-app/thunder/pull/455 which addresses most of these issues. The only remaining issue is the ability to set language which is currently being tracked here in the following issue. https://github.com/thunder-app/thunder/issues/157
