### ISSUE TITLE
Enabling "Compact List View" doesn't automatically disable unavailable options

### ISSUE THREAD

**Issue by malfisya** [thunder-app/thunder#942]
**Description**  
 I noticed that thunder is very slow on start up. Per matrix discussion @hjiangsu suggest to disable "View Full Height Images". That suggestion works. But I am always using "Compact List View" , so it might be that all unavailable options didn't get automatically disabled when "Compact List view" enabled. 

**How to Reproduce**  
1. Open Thunder
2. Go to settings => General
3. Enable "View Full Height Images" then Enable "Compact List view"
4. Close Thunder
6. Open thunder and estimate start up time
7. Go to settings => General
8. Disable "Compact List view", Disable "View Full Height Images" , then Re-enable "Compact List view"
9. Close Thunder
10. Open thunder and estimate start up time
11. Noticed that it became much faster

**Expected Behavior**  
Start up time should be the same

**Screenshots**  
Will edit if needed

**Device & App Version:**  
 - Device: Infinix Hot 11S NFC
 - OS: Android 11
 - App Version 0.2.6

**Comment by hjiangsu** [comment]
Thanks for writing up the issue! A PR is done for this particular issue and should be fixed in the next pre-release version.
