### ISSUE TITLE
Image dismissing smoother animation 

### ISSUE THREAD

**Issue by fedikhatib** [thunder-app/thunder#948]
When dismissing an image the action happen very fast that it's like flashing.

https://github.com/thunder-app/thunder/assets/34138112/27876ad9-646e-4a1b-bbf8-80b9af015fab

**Describe the solution you'd like**

Maybe a smoother animation.

**Describe alternatives you've considered**

Here's the sync Lemmy client behavior also the background color is the dominant image color

https://github.com/thunder-app/thunder/assets/34138112/3a31fa0f-6f11-4aaf-845f-12f8fbb4b904

**Comment by micahmo** [comment]
Hey @fedikhatib, if you still use Thunder, can you let us know if the animation looks better to you in the latest version (0.3.0)? Thanks!
