### ISSUE TITLE
Unable to click drop-down list

### ISSUE THREAD

**Issue by malfisya** [thunder-app/thunder#951]
**Description**  
Whenever I try to make a post from home screen and try to choose community, the drop-down list cannot be clicked. The same behaviour also found when try to post from community page. I cannot click the title suggestion. Cheers!

**How to Reproduce**  
1. Open Thunder
2. Flick FAB and choose "Create Post"
3. Click "Select a community"
4. Pick any community (with search or whithout)
5. Drop-down appear to be clicked but no community was selected

**Expected Behavior**  
A community is selected

**Screenshots**  
https://github.com/thunder-app/thunder/assets/101771435/6c4ab4ee-e60f-43ec-b3be-6474224e21e5
https://github.com/thunder-app/thunder/assets/101771435/dd5767e0-b360-43fd-97f4-318833c2d1c8

**Device & App version:**  
 - Device: Infinix Hot 11S NFC
 - OS: XOS (Android 11)
 - App Version : 0.26

**Comment by micahmo** [comment]
I happened to see this once today on my physical decide, but that's it. Now I can't reproduce on the emulator or physical. 😞

**Comment by hjiangsu** [comment]
Thanks for creating this issue!

Like @micahmo, I haven't been able to reproduce this issue myself. I'll keep an eye out for this issue though and please update us with any more information that you have which might help us reproduce the issue more consistently!

**Comment by hjiangsu** [comment]
I labelled this issue as on-hold since there's no clear reproducible steps we can take to trigger this issue.

**Comment by hjiangsu** [comment]
See https://github.com/thunder-app/thunder/issues/1120#issuecomment-2028436186 for an update on this!
