### ISSUE TITLE
Long app initial load times (>6s)

### ISSUE THREAD

**Issue by Coehill** [thunder-app/thunder#983]
**Description**  
I'm finding that the app is slow to load, especially compared to Jerboa.  I have tried closing all apps and tested this on a flagship Android device.  I tested force stopping Jerboa before launching it and the image of the first post loaded in 88ms whereas Thunder took 6.8s.  Anything over 2s causes most users to bounce so it makes sense to optimize it.

**How to Reproduce**  
1. Close Thunder / Force Stop
2. Launch Thunder and wait for image of first post to load.

**Expected Behavior**  
Initial app load < 2s

**Device & App Version:**  
 - Device: Galaxy S23
 - OS: Android 14
 - App Version v0.2.6

**Comment by hjiangsu** [comment]
Thanks for creating the issue! There were some changes made in the latest pre-releases which hopefully fix some of the issues with slow app startup.

Could you try those out and let me know if you see any improvements?

**Comment by Coehill** [comment]
Hi @hjiangsu, the apk you provided launched in ~2.5-3s which is a big improvement!

**Comment by hjiangsu** [comment]
Do you think this is still an issue? Or can it be marked as completed?

**Comment by Coehill** [comment]
I think it makes sense to mark it as completed. 🙂

**Comment by realeatham** [comment]
this still happens to me as of the latest version

**Comment by hjiangsu** [comment]
@realeatham Which version are you running, and can you describe any more information on the issue? Maybe something else was missed during the fix/testing.

Things that would be useful to know:
- Thunder version
- Instance name and version
- Whether the issue shows up when you're logged in or using anonymous account (if possible, test with both anonymous and logged in accounts so that I can track down the issue further)
- How often does this issue occur

**Comment by realeatham** [comment]
1. Thunder Nightly 0.2.7-5
2. aussie.zone 1.19.0, lemmy.world 1.18.5
3. Both
4. Everytime I open the app, switch account, view a feed, community or profile.

**Comment by hjiangsu** [comment]
Interesting, are you able to send a screen recording of it? I use `lemmy.world` and haven't encountered long delays on the latest pre-release version.

Generally speaking, How long are the load times? (0-3 seconds, 3-6 seconds, longer). Additionally, what is the ping time to the servers? You can see that information on the account switcher.

**Comment by hjiangsu** [comment]
As an example, this is my load time. This is on `aussie.zone` on 0.2.7-5.

https://github.com/thunder-app/thunder/assets/30667958/0501609b-f21f-4e41-98e3-3cd91cf8ca92

**Comment by realeatham** [comment]
I cannot upload the file to GitHub as it is too big, should I send it to you via matrix?

**Comment by hjiangsu** [comment]
Feel free to send it to me via Matrix!

**Comment by hjiangsu** [comment]
I'll close this for now as it seems like the majority of issues with long load times are somewhat resolved.

As mentioned previously, and in the matrix channel, one main issue that is still unresolved with regards to long load times has to do with determining the image height/width as it's not provided by Lemmy's API (which requires us to perform extra network requests to determine the height/width).
